### ISSUE TITLE
VSCode EDGE Devtools "blob problem" again

### ISSUE THREAD

**Issue by vronkain** [microsoft/vscode-edge-devtools#1000]
**Environment (please complete the following information):**

MacOS 11.6.5

**Describe the bug:**

Edge Devtools does not work but gives an error message about: BlobNotFound 

**Repro steps:**

click F5 (debug) in VScode

**Expected behavior:**

**Additional context:**

![IMAGE 2022-04-29 11:35:35](https://user-images.githubusercontent.com/14953272/165911171-fb1eed99-0d86-492d-88b6-43dce8e88a66.jpg)

**Comment by codepo8** [comment]
I ran into the same issue earlier and the reason was that Canary needed an update. If you do that, it will go away.

**Comment by vronkain** [comment]
I updated and restarted both Edge and VS, still the same error. Strangely MS autoupdater didn't offer update, but it was available in the browser.

**Comment by vronkain** [comment]
Now it seems to be working
