### ISSUE TITLE
the bug

### ISSUE THREAD

**Issue by usermynamehere** [microsoft/vscode-edge-devtools#1001]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by usermynamehere** [comment]
package-lock.json

**Comment by codepo8** [comment]
Hello there, can you please tell us more about the bug?
