### ISSUE TITLE
Error while fetching list of available targets 

### ISSUE THREAD

**Issue by DavidTDC3377** [microsoft/vscode-edge-devtools#1025]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): 2.0.0

**Describe the bug:**
Error while fetching list of available targets shows when launching without debugging

**Repro steps:**
1: Make a JavaScript file
2: Get the extension
3: Run it

**Expected behavior:**
For Edge to open and start the script there.

**Additional context:**
![vscode-screenshot](https://user-images.githubusercontent.com/40366903/167593326-30831ee8-0660-4251-bb1b-c740bfd80b87.png)

**Comment by codepo8** [comment]
Hello there, what would you expect a browser to do with a JavaScript file without any HTML? This workflow would be a success if you embedded the JS inside an HTML document, and then open this inside the browser. If all you want to do is to run and debug a JavaScript, you can select Node as the debugger and you don't need the browser extension.

**Comment by DavidTDC3377** [comment]
Oh okay, thank you.
