### ISSUE TITLE
DIDWW Webtechnicom Project

### ISSUE THREAD

**Issue by NETwork-Inc** [microsoft/vscode-edge-devtools#1029]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by NETwork-Inc** [comment]
https://github.com/microsoft/vscode-edge-devtools/issues/1029#issue-1232601479

**Comment by captainbrosset** [comment]
This issue does not have any actionable information in it, so I have to close it. If you do have an issue with our vscode extension, please provide details about it.
