### ISSUE TITLE
destructuring e.g. in HtmlInputElement (jsx) brings up wrong error

### ISSUE THREAD

**Issue by bertutron** [microsoft/vscode-edge-devtools#1031]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): macos
 - Extension version (*e.g.,* 1.2.3):Last updated
05/04/2022, 22:35:16

**Describe the bug:**

when destructuring an object in an htmlinputelement (like <input {...someObject}....) with someObject having properties like title, value, name etc, The extension brings up error of category axe/forms:
Element has no title attribute Element has no placeholder attributeMicrosoft Edge Tools[axe/forms](https://dequeuniversity.com/rules/axe/4.4/label?application%3DaxeAPI)

i understand that attributes are not propeties, but the code would be working fine and i think this is done pretty often and shouldnt bring up an error
**Repro steps:**

- yarn create react-app --template typescript
- replace App component with 
```
function App() {

  const [test, setTest] = useState( {title: 'hi', placeholder:'blubb', type:'text', name:'a', value:'value'} as HtmlInputData)

  return (
    <div className="App">
      <label htmlFor={test.name}></label>
      <input {...test} onChange={e => handleChange(e.target.value)} />
    </div>
  );

  function handleChange(value: string): void {
    throw new Error('Function not implemented.');
  }
}
```
**Expected behavior:**

dont show error
**Additional context:**

**Comment by antross** [comment]
Thanks @bertutron! This is definitely a false-positive that shouldn't happen. 

I created a bug in the webhint project we depend on to track this there as well (since that's where we'll need to make the fix first). We'll take a look and see if we can get this fixed.

**Comment by Latha303** [comment]
https://github.com/webhintio/hint/issues/5166
