### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by Hood-Ninja** [microsoft/vscode-edge-devtools#1033]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out @Hood-Ninja, unfortunately there isn't enough information in this issue for us to act on it. 
Could you please describe what the problem is exactly, and the steps you took to encounter it.
