### ISSUE TITLE
debug toolbar

### ISSUE THREAD

**Issue by riadshazly** [microsoft/vscode-edge-devtools#1034]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out @riadshazly. Unfortunately there isn't enough information here for us to act on this issue.
Please do add information about the problem you are having or the feature you would like to add.

**Comment by codepo8** [comment]
Closing as there is not more information coming in.
