### ISSUE TITLE
newfolder

### ISSUE THREAD

**Issue by agungprasetiyo2899** [microsoft/vscode-edge-devtools#1036]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately this seems like an incomplete issue. There isn't enough information for us to do animation here. So I'll close the issue now.
Please feel free to comment with more information if you have any issues with the extension.
