### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Maha10009** [microsoft/vscode-edge-devtools#1038]
- Issue Type: `Bug`
- Extension Name: `vscode-edge-devtools`
- Extension Version: `2.0.0`
- OS Version: `Darwin x64 21.5.0`
- VS Code version: `1.67.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by captainbrosset** [comment]
Hi @Maha10009, thanks for reaching out. Could you please provide more details about what issue you are having?
The version and environment info is useful, but we need to know what problem you're having before we can investigate.
