### ISSUE TITLE
Allow modifiying cursor style

### ISSUE THREAD

**Issue by andresbm05** [microsoft/vscode-edge-devtools#104]
When using "Elements" tab the cursor transforms to a dot which is not very precise.
Moreover, when debugging desktop versions you may want to check the cursor styles when hovering buttons or any other action that changes cursor style.

It should be an option to use default cursor instead of this dot cursor.

**Comment by lateau** [comment]
This feature is most essential I wish the team support it soon. Because I have responsive mode through external Edge(Chromium) browser, touchable device minded mouse cursor as default is little bit annoying. I want it to goes to be configurable.
