### ISSUE TITLE
edge isnt doing what its suposed to

### ISSUE THREAD

**Issue by HarleyVader** [microsoft/vscode-edge-devtools#1048]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing this issue as it appears to be empty. There isn't information in the title or description for us to do anything here. Please feel free to comment with more information.
