### ISSUE TITLE
Option to change elements to dark mode

### ISSUE THREAD

**Issue by sparsh238** [microsoft/vscode-edge-devtools#105]
Hi,
I couldn't find an option to make the elements window appear in dark mode. It appeared in the dark mode for me when I started the extension for the first time, then something happened and I have it in light mode now and I rather have it in the dark mode. So I would suggest there be an option or setting to specify the theme. I have tried setting my default theme in my computer as dark, and the theme is dark even in my Edge Dev browser.

**Comment by codepo8** [comment]
Hey there, for now the extension matches the setting of the operating system and there is no way to override that. So if you set your OS to dark mode, the devtools in VS Code should match. Thank you for the suggestion though, we're looking into this.

**Comment by mliao95** [comment]
The linked PR adds a settings option for changing the extension's themes.  Closing out this issue.
