### ISSUE TITLE
PQ[BOLTS

### ISSUE THREAD

**Issue by box4443** [microsoft/vscode-edge-devtools#1053]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
This is an empty issue. Closing now. Please feel free to comment with more details if you have any issue with the extension.
