### ISSUE TITLE
New Edge Icon 

### ISSUE THREAD

**Issue by betancour** [microsoft/vscode-edge-devtools#106]
Is there an Update to change the Icon from Microsoft Edge based on Chromium? 

![image](https://user-images.githubusercontent.com/283403/68442392-9b063000-01af-11ea-968a-3fd936089fa4.png)

![image](https://user-images.githubusercontent.com/283403/68442402-a22d3e00-01af-11ea-9453-da71dad7dcdc.png)

**Comment by jalissia** [comment]
Yes, we will have an update soon to change to the new icon.

**Comment by betancour** [comment]
> Yes, we will have an update soon to change to the new icon.

When will be released this update?

I think is something easy to deploy....
