### ISSUE TITLE
Detach Edge instance to seperate window

### ISSUE THREAD

**Issue by gernot-at-etron** [microsoft/vscode-edge-devtools#1060]
**Is your feature request related to a problem? Please describe.**
The browser window cannot be detached from vscode such that it can be moved to another display/monitor. At the moment it works like having multiple tabs in vscode like in a browser, but you cannot convert a "tab" to a new window at the moment and move it to another screen.

**Describe the solution you'd like:**
The browser window should be detachable from vscode such that it can be moved to another display/monitor. You should be able to have vscode lets say on display/monitor 1 and the edge instance on display/monitor 2.

**Describe alternatives you've considered:**
There is no alternative except buying one huge screen instead of 2 small ones. Many people run multiple screens and this is actually a quite common developer setup to have lets say two or three fullhd screens.

**Additional context:**
This is how it looks like at the moment on a fullhd screen. This is obviously not very comfertable. Not everybody uses one 4 to 8k screen instead of two or threen fullhd ones.
![vscode](https://user-images.githubusercontent.com/106426773/171927787-7793e1f6-af69-4d71-bf2c-89507ed966c6.png)

**Comment by codepo8** [comment]
Hi there, you can open the browser in an own window. This used to be the default and you can reset it in the settings:
If you untick the "headless" setting, opening a new instance will open it in an own window.
If you use the generated launch.json, you can select from "launch headless Edge" and "launch Edge", the latter being an own window.


![image](https://user-images.githubusercontent.com/13508/172202062-f075f879-43f7-4db1-92d1-326413d54c96.png)

**Comment by gernot-at-etron** [comment]
Thank you very much, this works.
