### ISSUE TITLE
[BUG] webhint ignores .browserslistrc in subfolder

### ISSUE THREAD

**Issue by gunnarburmeister** [microsoft/vscode-edge-devtools#1065]
**Environment (please complete the following information):**
 - OS: Windows 10
 - Extension version: 2.0.0

- Angular application (13.1.0)

**Describe the bug:**

I have an angular application and browsers are restricted to `last 2 Edge versions` in `.browserslistrc`. There are still hints (warnings/errors) about browser compatability.
E.g. scss `width: fit-content` produces
> width: fit-content' is not supported by Firefox, Firefox for Android. 
Add 'width: -moz-fit-content' to support Firefox 3+, Firefox for Android 4+.Microsoft Edge Tools [compat-api/css](https://developer.mozilla.org/docs/Web/CSS/width)

Adding a `.hintrc` with 
```
{
  "browserslist": [
    "last 2 Edge versions"
  ]
}
```
didn't help either.

(When I open a folder with only a scss file with such a property and the .hintrc it does work as expected.)

**Repro steps:**

1. Create new angular application
2. Restrict `.browserslistrc` to `last 2 Edge versions` (or major)
3. Add `.test {
  width: fit-content;
}` to `app.component.scss`

**Expected behavior:**

Only hint warnings/errors for browsers supported by the application.

**Additional context:**

**Comment by captainbrosset** [comment]
That's weird, according to this comment from @antross, this should work: https://github.com/microsoft/vscode-edge-devtools/issues/663#issuecomment-1042378169

I am not very familiar with the `browserslist` syntax, but one difference I see is that you've used specified your target browsers as a string in an array, however in the issue I linked to, it's only a string (no array container).
Maybe that makes a difference? Worth a try.

**Comment by gunnarburmeister** [comment]
> That's weird, according to this comment from @antross, this should work: [#663 (comment)](https://github.com/microsoft/vscode-edge-devtools/issues/663#issuecomment-1042378169)
> 
> I am not very familiar with the `browserslist` syntax, but one difference I see is that you've used specified your target browsers as a string in an array, however in the issue I linked to, it's only a string (no array container). Maybe that makes a difference? Worth a try.

There are basically three places I can put this. `package.json`, `.browserslistrc` and `.hintrc`. I have tried all of them (though, since I want to restrict the whole application, either `package.json` or `.browserslistrc` is the correct choice (`package.json` takes precedence)).

Currently I'm using `.browserlistrc`, the comment from antross uses `package.json` (single string or array of strings doesn't matter, just tried it) and I've tried with `.hintrc` (additionally).

I'm really not sure what might be the cause here, but something seems to be clashing.

**Comment by antross** [comment]
@gunnarburmeister, it looks like webhint isn't automatically picking up changes to `.browserslistrc`, but if I restart VS Code (Ctrl+Shift+P, then choose "Developer: Reload Window") after updating the list it appears to work correctly. Does this work for you too after restarting VS Code?

**Comment by gunnarburmeister** [comment]
@antroos Sorry for the late reply. I got sick and will only be able to check on this next week again on work.
I didn't update the `.browserslistrc` for this originally though. I just switched from the deprecated edge debugger to the new extension.

I did a quick test on my home machine and it seems to work fine here (not my work projekt though). Maybe I have some other conflicting extension installed on my work machine.

**Comment by antross** [comment]
@gunnarburmeister thanks for the update. I'll keep this active for now and hopefully we can figure out what's different about your work project or environment. If you can even strip it down enough to be able to share it that'd be great, but I understand that may not be possible.

I will note that if there's a `.hintrc` file and that contains a `browserslist` entry then webhint will force that one to override anything provided anywhere else (so any other entries in `.browserslistrc` or `package.json` would effectively be ignored regardless of the precedence browserslist itself gives them).

**Comment by gunnarburmeister** [comment]
@antross Hmm, apparently it is not related to another extension. I tried disabling every other extension one by one (with reloads after each) until only the edge extension was remaining - still getting the warnings/errors.

I'm only using a `.browserlistrc` file, no entry in `package.json` and no `.hintrc` (the project itself is like 2.5 years old and the browserrestriction maybe 1.5).

I incidentally seem to have found the reason now (been testing some more stuff while writing this comment):
I have a brand new angular test project (like in the initial post, just created a new angular app inside a folder, restrict version in `.browserslistrc` (with reload) and added a test case). This creates the following folder structure:
```
test
- test-app 
-- src
-- .browserlistrc
-- angular.json
-- package.json
-- tsconfig.json
-- ...
```

When I open the top level folder `test` in VSCode I get the errors, if I open the sub folder `test-app` everything is fine. It seems like it can't resolve the paths correctly like this (wrong root/not relative?).
