### ISSUE TITLE
Unable to start webhint. Ensure you are using the latest version of the `hint` package.

### ISSUE THREAD

**Issue by Eesahy** [microsoft/vscode-edge-devtools#1068]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Do you have an old install of hint? Did you try updating it? When that happens, it is normally a clash of versions.
