### ISSUE TITLE
look

### ISSUE THREAD

**Issue by box4443** [microsoft/vscode-edge-devtools#1072]
![OIP (3)](https://user-images.githubusercontent.com/106244400/173177834-0321b0a3-a891-4ddb-80dd-fc35719bfe8d.jpg)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing this as incomplete.
