### ISSUE TITLE
Copy and paste does not work in the embedded Edge DevTools browser

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-edge-devtools#1075]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11 22H2 
 - Extension version (*e.g.,* 1.2.3): 2.0.0

**Describe the bug:**

Copy and paste and even context menu (right click) does not work in the embedded browser.

**Repro steps:**

https://user-images.githubusercontent.com/29582865/173495518-c9f672b9-fa6d-4083-8c08-bb8cf8fead6c.mp4

**Expected behavior:**

To work, because often I have to access live websites which require login, and having to type in long passwords is a very boring procedure.

**Additional context:**

N/A

**Comment by codepo8** [comment]
We're looking into this. There is an architectural issue in VS Code we need to work around, but thanks for bringing this up.

**Comment by mliao95** [comment]
We actually have text-only clipboard functionality coming down the pipeline in [this PR](https://github.com/microsoft/vscode-edge-devtools/pull/1035).  It will be available in the next release!

**Comment by felipecrs** [comment]
Oh wow, that will be very helpful! I will close this issue then as duplicate of #998 and closed by #1035.

Thank you very much!
