### ISSUE TITLE
`skipFiles` not passed on to Edge's DevTools and no other way to ignore source files in console output

### ISSUE THREAD

**Issue by ksmth** [microsoft/vscode-edge-devtools#1080]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): macOS 12.4
 - Extension version (*e.g.,* 1.2.3): v2.0.0

**Describe the bug:**

`skipFiles` is being ignored. Further, only the compiled files and not source mapped files can be added to Edge's "ignore this file" feature, so I can't ignore files in the call stack.

Current use case is that I have a custom logger lib which is used instead of direct calls to `console.log`. Now when I call `logger.log(...)` and it prints to the console, you'll see the `logger.ts` file as the source of the log, which is not very useful. In Chrome, you can right click and ignore logs from that file, which will then reveal the true source of the log statement, the file where `logger.log(...)` got called, not `console.log(...)`. I would've assumed, setting `skipFiles` would forward this info to Edge.

**Repro steps:**
I think the steps to repro should be pretty clear from the bug description already - if not, please let me know

**Expected behavior:**

`skipFiles` should be forwarded to Edge and configure it in such a way, that the files will also be ignored in it's DevTools

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for the issue @ksmth. We've added a task on our backlog for this.

**Comment by codepo8** [comment]
Thank you for reporting this, we will look into it.
