### ISSUE TITLE
WebView messaging relies on exception

### ISSUE THREAD

**Issue by jalissia** [microsoft/vscode-edge-devtools#110]
We have an issue with how our postmessage works for communicating between the webview and the extension. Currently we rely on an exception being thrown to determine the direction of the message. We should find a better way to solve this.

See: https://blog.mattbierner.com/vscode-webview-web-learnings/

**Comment by bgoddar** [comment]
This has been resolved with the update to cdn architecture: https://github.com/microsoft/vscode-edge-devtools/pull/449
