### ISSUE TITLE
I cant start debugging

### ISSUE THREAD

**Issue by michael100S** [microsoft/vscode-edge-devtools#1104]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately there isn't quite enough information here for the team to start investigating. I'll close this issue as incomplete for now, and can re-open it when you provide more information. Thanks.
