### ISSUE TITLE
How to connect to Edge vs version

### ISSUE THREAD

**Issue by Saidimukasa** [microsoft/vscode-edge-devtools#1109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
Hi there, can you please tell us more what you mean? You can change the version of edge to debug with (canary, dev, stable) in the settings. Is that it?

**Comment by Saidimukasa** [comment]
Yes i this i will do what you have said
