### ISSUE TITLE
Prompt and alert

### ISSUE THREAD

**Issue by Gifted-Dev** [microsoft/vscode-edge-devtools#1111]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):  Windows 10
 - Extension version (*e.g.,* 1.2.3):  v2.1.0

**Describe the bug:**

prompt and alert function not working on the browser

**Repro steps:**

simply link a JS file to HTML. and then try the prompt function, you would see no prompt is given.

**Expected behavior:**

A prompt pop up should show  in the browser where I can input a value.

**Additional context:**

**Comment by codepo8** [comment]
I will try this and I am surprised that it doesn't. You can, however, instead of using prompt or alert use console.log() and debug with the built-in Console tool. 
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-log?branch=pr-en-us-2050

**Comment by codepo8** [comment]
Verified, this isn't working.
