### ISSUE TITLE
i unable to execute our html cde

### ISSUE THREAD

**Issue by Harrybhai1** [microsoft/vscode-edge-devtools#1123]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you explain more what you mean? HTML isn't an language that needs execution. Can't you open an html document when you right-click it?
