### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sega2804** [microsoft/vscode-edge-devtools#1125]
- Issue Type: `Bug`
- Extension Name: `vscode-edge-devtools`
- Extension Version: `2.1.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by codepo8** [comment]
Hello there, what is the bug you encountered?
