### ISSUE TITLE
Do not open live server in crome

### ISSUE THREAD

**Issue by Surajrwt** [microsoft/vscode-edge-devtools#1126]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Hello there, can you please explain what you mean? Live server isn't this extension, and Chrome isn't the browser this relates to either.

**Comment by codepo8** [comment]
3 day timeout, closed.
