### ISSUE TITLE
Microsoft Edge could not be found - Unable to launch a file

### ISSUE THREAD

**Issue by manuartero** [microsoft/vscode-edge-devtools#1127]
**Environment (please complete the following information):**
 - OS: **MacOS v12.14 - Monterey**
 - Extension version: **`2.1.0`**

**Describe the bug:**

When trying to launch - even the simplest configuration - vsCode raises the error

> 🛑 
> `Microsoft Edge could not be found. Ensure you have installed Microsoft Edge and that you have selected 'default' or the appropriate version of Microsoft Edge in the extension settings panel.`

even this configuration fails: 

```json
    {
      "type": "msedge",
      "name": "Launch Microsoft Edge",
      "request": "launch",
      "file": "${workspaceFolder}/.vscode/blank.html",
    },
```

while changing `msedge` by `firefox` DOES work

**Repro steps:**

- Install the extension
- Click on the activity panel
- Configure launch.json
- change the URL
- Launch Instance
- FAILS

![Captura de Pantalla 2022-07-28 a las 11 32 30](https://user-images.githubusercontent.com/2211052/181476174-1d6b554c-74bd-4b9d-a2ed-c2b5e385a67c.png)

**Expected behavior:**

I expect a new Edge instance to run my blank.html (firefox is able to launch it)

this is the file I'm trying to open: 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body></body>
</html>
```

**Additional context:**

The extension seems to be installed just fine.:

![Captura de Pantalla 2022-07-28 a las 11 32 55](https://user-images.githubusercontent.com/2211052/181474223-01a15cda-e942-4898-a253-af903158f2ee.png)

**VIDEO**

https://user-images.githubusercontent.com/2211052/181476029-61e27943-450c-4023-b557-591efe7407e6.mov

In this video:

 - I have configured the simplest launch possible.
 - try to run it with `msedge` -> fails 🔴 
 - try to run it with `pwa-msedge` -> fails 🔴 
 - change to `firefox` -> OK ✅

**Comment by codepo8** [comment]
Hi there, did you download and install Edge? On a Mac, it isn't available by default, you need to get it at:

https://www.microsoft.com/en-us/edge

This extension _needs_ Edge to work, it doesn't support any other browsers. Sorry if that wasn't clear. Firefox will open the file, but none of the communication between browser and VS Code will work.

**Comment by codepo8** [comment]
Also <3 for your incredibly detailed issue post!

**Comment by manuartero** [comment]
ok this is embarrassing 😭 .

Works like a charm, thanks !

![Captura de Pantalla 2022-08-01 a las 9 29 03](https://user-images.githubusercontent.com/2211052/182095991-7258b036-9cfb-476f-960e-9f7e8242e1c2.png)

***



<img src="https://media.giphy.com/media/DUtVdGeIU8lmo/giphy.gif" width=400 />
