### ISSUE TITLE
Screencast for Electron app in WSL is not working properly

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode-edge-devtools#114]
Scenario: debugging an Electron application running in WSL, with an X server running in Windows.

Debugging the main Electron process works just fine - however, trying to attach the Elements extension to the renderer process yields flaky results - the visible rendered page is black, until the dev tools pane is closed.
The behaviour is consistent even when the Electron app is started without the developer tools pane opened.

![Hnet-image](https://user-images.githubusercontent.com/13103165/69587376-44b03400-0f9a-11ea-87ff-d583148b1813.gif)

**Comment by mliao95** [comment]
Hey Radu!  Sorry for the delayed response.  I wanted to check in to see if this issue still repros on the most recent version of the extension.  If it does, I can take a deeper look into the issue.

**Comment by mliao95** [comment]
Closing.  Can re-open the issue if needed.
