### ISSUE TITLE
add auto reload on edge pls ! pls ! pls!

### ISSUE THREAD

**Issue by Simrat0707** [microsoft/vscode-edge-devtools#1140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
@Simrat0707 can you please describe in more detail what you would like us to add? Also, this repository is about the vscode devtools extension, not about Edge itself. Is your reload feature request about Edge?

**Comment by codepo8** [comment]
I suppose the idea is to reload Edge on every change of the code, much like the live reload extension does. Is that right?

**Comment by frigvid** [comment]
I'm quite certain the user means an automatic page reload on file changes, the title is rather self explanatory even if somewhat lacking. I'd find this feature rather nice to be built-in as well. Even though you can combine the functionality of multiple extensions to achieve much of the same, it'd be nice to need less configuration for things like this.

**Comment by codepo8** [comment]
Tracked and closing this
