### ISSUE TITLE
new_vue

### ISSUE THREAD

**Issue by sulahamza3** [microsoft/vscode-edge-devtools#1143]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please add more details if you are encountering an issue with the extension. As is, we can't do anything with this issue.
