### ISSUE TITLE
vs won't run my code in chrome always shows msg " can;t find the adapter "

### ISSUE THREAD

**Issue by gmd2022** [microsoft/vscode-edge-devtools#1147]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you please give us some more information or a screeenshot? This extension only works with Edge, not with Chrome.

**Comment by codepo8** [comment]
Nothing to work with here.
