### ISSUE TITLE
Uploading Operations cannot be done.

### ISSUE THREAD

**Issue by AlicanAKCA** [microsoft/vscode-edge-devtools#1151]
**Is your feature request related to a problem? Please describe.**

I'm currently using Gradio. When I wanted to start it locally, I have to upload something to the interface. But I couldn't find anything that provides to select files. 

**Describe the solution you'd like:**

There may be something to select files like an OpenFileDialog object.

Thanks in advance! ^^

**Comment by codepo8** [comment]
Hello there, 
I am confused about this. Are you trying the in-extension browser to try and debug a web site that needs you to upload something and it doesn't work?

**Comment by AlicanAKCA** [comment]
Hello sir, thanks for your quick response.
I have no problem with debugging any of my code. I cannot do image upload or drag events in the interface I run locally. When I press Submit, I cannot select any file, nor can I add any files by dragging.
Here is the screenshot.
![Screenshot_11](https://user-images.githubusercontent.com/27694294/185476361-cb5d52a4-3588-4657-85e7-0fbd2b56b330.png)

As you mentioned, edge tools may not be designed for exactly this kind of functionality. But, I just wanted to let you know.

**Comment by codepo8** [comment]
Ah, thanks, that makes more sense. I will investigate. This could be a problem as the browser embedded is a screencast. Great catch, thank you!

**Comment by AlicanAKCA** [comment]
Glad to hear that, have a good day. ^^
