### ISSUE TITLE
corrupt ios file

### ISSUE THREAD

**Issue by Salvadorballs** [microsoft/vscode-edge-devtools#1155]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
There isn't enough information here for the team to investigate. Closing the issue as incomplete for now, but feel free to add a comment with a description of your exact problem and we can re-open the issue.
