### ISSUE TITLE
It does not go to https://localhost:3000. Instead it takes it to http://https//localhost:3000.

### ISSUE THREAD

**Issue by Alimazharsultan** [microsoft/vscode-edge-devtools#1163]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.

**Comment by captainbrosset** [comment]
Sorry, I closed this too quickly. Thanks for filing this issue. It seems like the code should do some detection to see if the URI scheme is already present.
