### ISSUE TITLE
C:\Windows\AppReadiness\S-1-5-21-1619065065-2187187050-3738180804-1001

### ISSUE THREAD

**Issue by satou859** [microsoft/vscode-edge-devtools#1167]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.
