### ISSUE TITLE
Skip tests

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode-edge-devtools#1168]
**Is your feature request related to a problem? Please describe.**

Microsoft Edge Tools keeps complaining about `'input[type=datetime-local]' is not supported by Firefox < 93.`

**Describe the solution you'd like:**

Is there a way to disable that check/test?

**Describe alternatives you've considered:**

None yet, but there are online HTML validators and probably linters as well.

**Additional context:**

Tools like PyLint can be configured to skip certain tests.

**Comment by captainbrosset** [comment]
Yes, I believe there is a way to define your own custom target browsers configuration.
You can do this either in a package.json file, or .browserslistrc file, or .hintrc file. The way this works is by using the [browserlist](https://github.com/browserslist/browserslist) syntax, here is an example:

```json
{
  "browserslist": "defaults, Firefox > 100"
}
```

**Comment by captainbrosset** [comment]
@codepo8 do you know if this is already documented somewhere? If not, we should work on adding this to [our docs](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension).

**Comment by codepo8** [comment]
The next version of the extension will allow you to do these changes directly in the code. You will be able to discard reports you don't want to see.

**Comment by codepo8** [comment]
But for now, we can add it to the docs.

**Comment by CTimmerman** [comment]
`.browserslistrc` from [here](https://github.com/microsoft/vscode-edge-devtools/issues/1168#issuecomment-1237769096) gives me ```Unable to start webhint. Ensure you are using the latest version of the `hint` package.``` and ```Found hint at c:\Users\C\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
AnalyzerError: Invalid configuration. Unknown browser query `{`. Maybe you are using old Browserslist or made typo in query..
    at Object.create [as createAnalyzer] (c:\Users\C\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:63:19)
    at t.Analyzer.initWebhint (c:\Users\C\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:561)
    at async t.Analyzer.initWebhint (c:\Users\C\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:612)
    at async t.Analyzer.validateTextDocument (c:\Users\C\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1083)
    at async c:\Users\C\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'ConfigurationError'
}
Checking if shared version of "hint" needs updated
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@8.11.0
npm info using node@v16.16.0
npm timing npm:load:whichnode Completed in 1ms
[...]
npm timing reify Completed in 89980ms

added 25 packages, removed 56 packages, changed 112 packages, and audited 568 packages in 2m

75 packages are looking for funding
  run `npm fund` for details

66 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm timing command:install Completed in 90116ms
npm verb exit 0
npm timing npm Completed in 90945ms
npm info ok 
```

**Comment by codepo8** [comment]
We will release a new version of the extension tomorrow, that should fix that issue.

**Comment by codepo8** [comment]
2.1.1 is out - update and filter away:

![hint-fixing](https://user-images.githubusercontent.com/13508/189297213-287808d6-ecc6-4c8d-a468-484e9afefac9.gif)

**Comment by CTimmerman** [comment]
Looks like the `package.json` doesn't work anymore and has been replaced by the quick fix `.hintrc`:
```json
{
  "extends": [
    "development"
  ],
  "browserslist": [
    "defaults",
    "not ie 11",
    "not firefox <= 91"
  ]
}
```

Thanks!
