### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by LuhMaths** [microsoft/vscode-edge-devtools#1170]
- Issue Type: `Bug`
- Extension Name: `vscode-edge-devtools`
- Extension Version: `2.1.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by captainbrosset** [comment]
Hi @LuhMaths, thank you for these details, however you didn't say what was the issue exactly? 
Can you reply with a comment saying what issue you are experiencing exactly, and what steps you took to get there.

**Comment by captainbrosset** [comment]
Going to close this as incomplete. Feel free to reply with more information if/once you have it.
