### ISSUE TITLE
i cant run html or css or... 

### ISSUE THREAD

**Issue by bifidus0** [microsoft/vscode-edge-devtools#1171]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Feel free to comment back with more information and we can reopen the issue.
