### ISSUE TITLE
Help me see png files to build a Robot Avatar Generator https://www.youtube.com/watch?v=L1E_7FoTrik&t=1013s

### ISSUE THREAD

**Issue by rbyrdsmith** [microsoft/vscode-edge-devtools#1172]
**Is your feature request related to a problem? Please describe.**

This is my first attempt at coding. I need the practice before building an encyclopedia app in AWS. I'm trying to build a Robot Avatar Generator (https://www.youtube.com/watch?v=L1E_7FoTrik&t=1013s) using my own pngs. I'm nearly at the end of the tutorial (I still need to make sure the parts are measured proportionally), and the only thing that's visible is the word "Generate!" and the border outline. I'm almost sure I'm making one rooky mistake after the other and the solution is probably right in front of my face.
**Describe the solution you'd like:**

Please help me finish this simple project. It will provide a lot of bang to my landing page (https://www.relikessentials.com/) and serve as the first real complex element of my app.

**Describe alternatives you've considered:**

I am trying to avoid purchasing the completed package from the creator. I want my own identity and I created robot parts in Photoshop and Illustrator. I feel like I'm taking really weird baby steps, but I'm determined to just throw myself in there. I am surely making one avoidable mistake after the next.  You have to start somewhere! Give me guidance...

**Additional context:**

**Comment by rbyrdsmith** [comment]
Sorry Christian. Just panicked. I'll be more judicious about how I use the
forum in the future.

Thanks.

Regina

**Comment by codepo8** [comment]
I wish to help you but I'd need a URL to check your product - from the video there is no way to help out.

**Comment by rbyrdsmith** [comment]
Oh. Duh. I'm still working on it. This is as far as I've gotten. I can't
view the images. I still need to complete the tutorial and configure them
as well.

I think this is what you mean,,,

Thanks for getting back to me!
