### ISSUE TITLE
Support edge extensions that are installed for vs code edge dev tools

### ISSUE THREAD

**Issue by maharshiAditya** [microsoft/vscode-edge-devtools#1184]
**Is your feature request related to a problem? Please describe.**

I really like this extension within vscode I'd like to use react dev tools extension within the vscode extension.

**Describe the solution you'd like:**

Add a support that would enable edge extension that are already installed be supported with vscode edge devtools

**Describe alternatives you've considered:**

Open edge and use dev tools for now. Instead of using this extension.

**Additional context:**

**Comment by codepo8** [comment]
Hi there, this is a common request and it is on our backlog. It is an uphill battle, and we are aware of it.
