### ISSUE TITLE
full image display on website header

### ISSUE THREAD

**Issue by buzne** [microsoft/vscode-edge-devtools#1192]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you explain more what you mean by that? Do you mean the tab preview? The in-built browser has no tabs.
