### ISSUE TITLE
Reporting of HTMLElement["ariaHasPopup"] in Dev Tools are false positive returning a Type Issue

### ISSUE THREAD

**Issue by polent** [microsoft/vscode-edge-devtools#1212]
While creating Web Components and defining proper Props in Stencil we found that Edge Dev Tools false positive report the given String values as expecting Booleans. Not sure where to sort this bug. 

```Bash
(property) JSXBase.IntrinsicElements.input: JSXBase.InputHTMLAttributes<HTMLInputElement>
ARIA attributes must conform to valid values: Invalid ARIA attribute value: aria-haspopup="{expression}"Microsoft Edge Tools[axe/aria](https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value?application%3DaxeAPI)
IDs used in ARIA and labels must be unique: Document has multiple elements referenced with ARIA with the same id attribute: {expression}Microsoft Edge Tools[axe/parsing](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria?application%3DaxeAPI)
```

![image](https://user-images.githubusercontent.com/4612123/193873431-25d1ae68-9512-4e1b-ad88-051f4f08e50d.png)

The Proporty is set properly to   @Prop() dataAriaHasPopup?: HTMLElement["ariaHasPopup"];

![image](https://user-images.githubusercontent.com/4612123/193873825-c011c908-4559-4d38-ac1e-0a1bb0458e6e.png)

See reference: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaHasPopup

**Comment by captainbrosset** [comment]
This seems to be coming from the axe, which is used by webhint, itself used by the DevTools VSCode extension to display warnings in the code.

Pinging @vidorteg for confirmation and/or investigation here.

**Comment by codepo8** [comment]
This is an issue within webhint, and we reported it there. Thanks for bringing this up.
