### ISSUE TITLE
Cannot close targets

### ISSUE THREAD

**Issue by ralef-ea** [microsoft/vscode-edge-devtools#1215]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): 2.1.1

**Describe the bug:**
I cannot delete a target for some reason.  When I press the close button the small progress bar on the left side shows up for a 1/2 second but nothing happens.

**Repro steps:**
1. Open up a target and then try to delete lit.

**Expected behavior:**
I should be able to delete targets.
**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for filing this bug. I'll make sure it shows up on the team's radar for investigation and prioritization.

**Comment by codepo8** [comment]
Can it be a refresh issue? Have you tried the refresh icon to see if it goes away?
