### ISSUE TITLE
Não funciona nenhum comando

### ISSUE THREAD

**Issue by Rhoterex44** [microsoft/vscode-edge-devtools#1222]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Rhoterex44** [comment]
Eu dou entre para escrever um novo comando no html não escreve nada teclo p para paragrafo e não acontece nada só pula de linha

**Comment by codepo8** [comment]
Hi there, can you give us more details what you are trying to do? It seems you are trying to have a live change in your source code show up in the browser?
