### ISSUE TITLE
[{ 	"resource": "/Users/macbook/Desktop/login/reset.css", 	"owner": "_generated_diagnostic_collection_name_#3", 	"code": "vendorPrefix", 	"severity": 4, 	"message": "Also define the standard property 'line-break' for compatibility", 	"source": "css", 	"startLineNumber": 67, 	"startColumn": 5, 	"endLineNumber": 67, 	"endColumn": 23 }]

### ISSUE THREAD

**Issue by tawen2019** [microsoft/vscode-edge-devtools#1229]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for the issue, however I think there isn't enough information here for us to investigate. I'll close the issue for the time being, but feel free to comment with more information and we can re-open.
