### ISSUE TITLE
I dont know want to do with this kind of notification 

### ISSUE THREAD

**Issue by Dhirajchaudari** [microsoft/vscode-edge-devtools#1231]
Type: <b>Bug</b>

I got the notification of this when i click on it . It took me to running Extension file and there few extensions like "Microsoft edge" and " Live server" showing Unresponsible please help we what should I do with this kind of notification and erro

Extension version: 2.1.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) 3558U @ 1.70GHz (2 x 1696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.92GB free)|
|Process Argv|--crash-reporter-id 028f39b7-1392-456c-a832-2d851bbb4fcf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
vsccc:30566497
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by captainbrosset** [comment]
Thanks for this issue. Unfortunately, I'm having a hard time understanding what the problem is exactly.
Could you please provide more detailed information for the team to repro this? 

What would help is a detailed set of steps that you took, that led to the notification.
And also a screenshot of the notification itself.

Thanks.

**Comment by codepo8** [comment]
Not applicable
