### ISSUE TITLE
font

### ISSUE THREAD

**Issue by jamiescoffee** [microsoft/vscode-edge-devtools#1232]
Hello

 I accidentally changed something in Dev Tools or Inspect Element
and now I cannot read anything  
[file:///C:/Users/jamie/AppData/Local/Temp/MicrosoftEdgeDownloads/c52cf51e-abfa-4f73-9c95-04e3a4851f49/dev%20tools11.pdf]()

**Comment by captainbrosset** [comment]
Hi @jamiescoffee, thanks for reaching out. Unfortunately the link you shared is a local file from your computer. We can access it here.
Can you please explain what you are seeing exactly? Maybe pasting an image here would help.

**Comment by codepo8** [comment]
Can't reproduce because of local url
