### ISSUE TITLE
auto reloader for better flow 😀

### ISSUE THREAD

**Issue by Arkapro1** [microsoft/vscode-edge-devtools#1240]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
@Arkapro1 thank you for reaching out and filing this issue.

I can kind of tell, from the title of the issue, that you would like the extension to auto-reload the page. But could you please edit your first comment and tell us more?
The more we understand about your exact problem and workflow, the better we can think about and track this feature proposal.

**Comment by codepo8** [comment]
tracked
