### ISSUE TITLE
BlobNotFound error message shown in 'Edge DevTools' tab

### ISSUE THREAD

**Issue by gilesep** [microsoft/vscode-edge-devtools#1243]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Mac Montery 12.6 (Apple Silicon M1)
 - Extension version (*e.g.,* 1.2.3): v 2.1.1

**Describe the bug:**

When I open the 'Edge DevTools' tab in vs code it just displays this error message:

BlobNotFound The specified blob does not exist.
RequestId:8e5ddf73......etc
Time:2022-11-01T......etc

**Repro steps:**

Install latest 'Edge' browser on the mac m1 (I installed 107.0.1418.28, arm64).
Install latest 'Microsoft Edge Tools for VS code' extension on in vs code (I installed 1.2.2).
Create a new folder with a simple index.html file inside and open it in vscode.
In the vscode Explorer window, right click on the index.html file.
Select 'Open with Edge | Open Browser with DevTools'.

**Expected behavior:**

I expected two tabs to pop up here, as follows:
* 'Edge DevTools: Browser', which should contain the webpage.
* 'Edge DevTools', which should contain development/debug tools (I assume).

Both tabs did pop up ok, but the 'Edge DevTools' tab just contained the error message mentioned in the description.

**Additional context:**

This is my first time installing 'Edge' and 'Microsoft Edge Tools for VS code' (or submitting a GitHub issue).
The issue seems similar to this one: https://github.com/microsoft/vscode-edge-devtools/issues/1000
The vscode-edge devtools plugin looks amazing, but unfortunately I cannot get it to work.
I've attached a screen shot of what I see. Thanks for your time.
<img width="1439" alt="Screenshot 2022-11-01 at 13 19 54" src="https://user-images.githubusercontent.com/6206311/199243653-cba21da5-0f05-43a1-b9e9-c909a3f78922.png">

**Comment by Luo-En** [comment]
The same problem ( on Linux though) started for me a couple of days ago. I downgraded Microsoft Edge browser back to to 107.0.1418.24  and the problem was gone.

**Comment by captainbrosset** [comment]
Thanks for filing, and for the detailed explanations. Let me make sure this is tracked by the team.

**Comment by Tim-OuY** [comment]
Is there any update? I still have the same problem.

OS: macOS 13.0.1
Extension version: v2.1.1
Edge Browser Version: 107.0.1418.68

**Comment by ivanschuetz** [comment]
Same problem here, macOS 12.6, extension v2.1.1, Edge 108.0.1462.41 (arm64)

**Comment by PublicTrades** [comment]
Same issue here, any real fix for this issue?

**Comment by vidorteg** [comment]
Putting out a fix for this issue, for anyone currently hitting this a workaround can be:
- Go to `VSCode Settings` -> `Extensions` -> `Microsoft Edge Tools`
- Change `Browser Flavor` to `Stable`

Reopen VSCode and try again.

**Comment by muzammal-noble** [comment]
> Putting out a fix for this issue, for anyone currently hitting this a workaround can be:
> 
> * Go to `VSCode Settings` -> `Extensions` -> `Microsoft Edge Tools`
> * Change `Browser Flavor` to `Stable`
> 
> Reopen VSCode and try again.

not working i have been faceing the same issue
