### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by HappyHG122** [microsoft/vscode-edge-devtools#1245]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.

**Comment by HappyHG122** [comment]
I'm still a student learning to understand github
Thank you for asking
