### ISSUE TITLE
html page not opening

### ISSUE THREAD

**Issue by pgreen24** [microsoft/vscode-edge-devtools#1246]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please add a comment with more information about your exact problem and we can re-open.
