### ISSUE TITLE
HTML select dropdown is not working

### ISSUE THREAD

**Issue by mahfuz225bd** [microsoft/vscode-edge-devtools#1248]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately there isn't nearly enough information here for us to investigate a potential issue.
Could you please comment and explain what your use case is exactly. What you were trying to do, and what happened. A screenshot could help too.

**Comment by codepo8** [comment]
This is a duplicate of a known bug. #1221

**Comment by mahfuz225bd** [comment]
I mean <select> element is not working.
