### ISSUE TITLE
flatpak issue

### ISSUE THREAD

**Issue by kiradevgmr** [microsoft/vscode-edge-devtools#1249]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

flatpak edge don't work with the extension
**Repro steps:**

**Expected behavior:**

**Additional context:**
\

**Comment by captainbrosset** [comment]
Thanks for reaching out, however this issue doesn't contain enough information for us to act on it.
Can you explain what flatpak is in more details, and describe what you are trying to do, and what is failing.
