### ISSUE TITLE
When using discord or an app that prompts you to use microphone notification doesn't show up to enable audio and mic

### ISSUE THREAD

**Issue by PyGuy13** [microsoft/vscode-edge-devtools#1256]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

Doesnt let me use discord and slack calls with audio and video because it doesn't prompt to allow microphone and camera

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out about this.
Just to double check: you are using discord (or slack) in the embedded browser in VSCode, right?

**Comment by PyGuy13** [comment]
Yeah, this is the extension I am using. https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools&ssr=false

**Comment by PyGuy13** [comment]
Os is windows 11 home, extension v2.1.1
