### ISSUE TITLE
Provide internet access also

### ISSUE THREAD

**Issue by kNIG132103** [microsoft/vscode-edge-devtools#1259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kNIG132103** [comment]
I want to create a clone website, I want to see the website side by side so no need to go browser again and again...

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please explain in more details what you mean? I'm not sure what you are looking for exactly. Would you like to have two embedded browsers in our VS Code extension? 
Also, would you mind rephrasing the title of this issue? The current title doesn't seem related to your issue.

**Comment by codepo8** [comment]
Closing this as there is no newer information.
