### ISSUE TITLE
how do I view the console output?

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode-edge-devtools#126]
not sure if it's supported yet or not, but I couldn't find anywhere that fetch the console outputs into the elements

**Comment by vidorteg** [comment]
Hi @mhamri 

Sorry for the late response, this is currently not supported. Just curious, were you looking for the drawer with the console or for the console tab?

**Comment by vidorteg** [comment]
Thanks for replying @mhamri ,sounds like we could have some area of improvement, maybe there could be a way to connect VsCode console and devtools output. I'll transform this into a feedback request and assign it. Thanks again for the great feedback @mhamri

**Comment by codepo8** [comment]
Thank you for your request @mhamri, we're looking if that is a use case that more people want and then see if we can do that easily. One worry I have is that a lot is happening in the console in browsers these days (we already have a lot of requests in the browser developer tools to provide filter mechanisms because of the noise) which makes you wonder if it isn't more distracting than helpful. Just out of curiosity: why not use breakpoints? Then you don't have to specify a lot of console messages but can get insight into the flow of the code and the state of the whole app.

**Comment by mhamri** [comment]
@codepo8, unfortunately, I couldn't attach to the browser. look like the attach mechanism for some reason doesn't work with the typescript and edge. though chrome is fine

i'm using angular 9, typescript 3.8.3

**Comment by mhamri** [comment]
also, most of the code that I'm debugging is rxjs, putting breakpoint there is really hard 😄

**Comment by codepo8** [comment]
Interesting points, we'll take a look into what is possible.

**Comment by billie-spektor** [comment]
I would also appreciate this functionality. My use-case is quickly checking properties for DOM-elements. Let's say I want to debug why an absolutely positioned element in a nested html tree doesn't behave as expected. In the browser, I can easily debug this by selecting the element in the elements panel and executing $0.offsetParent in the console. Currently I can get the same information in the extension, but not as quick:

![image](https://user-images.githubusercontent.com/69010225/90330741-8319d300-dfaf-11ea-861a-001575523ce6.png)

However, I'm not sure if this functionality remains available in the extension, as it's deprecated in the browser:

![image](https://user-images.githubusercontent.com/69010225/90330819-09ceb000-dfb0-11ea-9de2-e463819ef76a.png)

It would be nice to have the console in the extension for that kind of quick debugging. To keep the default clean, I would vote for the same approach as the implementation of the network tab: the console in its own tab and not visible by default.

**Comment by darthwalsh** [comment]
Another argument for making printf debugging work: it's the lowest common denominator for external libraries. JS libraries you call into will often output important errors and warnings on the console, and seeing that console output is much much easier than trying to find sourcemaps or debugging through minimized source.

**Comment by codepo8** [comment]
There are some technical barriers to overcome, but we hear you loud and clear that this is a good next step to take.

**Comment by mliao95** [comment]
The PR above will allow users to see the console output within the VSCode output window.  I will track the work to make this interaction bi-directional in issue #274
