### ISSUE TITLE
Very blurry preview not clear

### ISSUE THREAD

**Issue by abdarker** [microsoft/vscode-edge-devtools#1260]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

<img width="270" alt="image" src="https://user-images.githubusercontent.com/14371506/201517991-52ebdd90-003e-4820-a600-4aa724a6e320.png">

**Comment by captainbrosset** [comment]
Thanks for filing this!

@codepo8 didn't we have another similar issue at some point? Otherwise it seems like we should track this.

**Comment by codepo8** [comment]
This is a known issue and we're tracking it. Thanks for bringing it up again. Right now, the issue is when you use a zoom level more than 100.
