### ISSUE TITLE
I made a program in V. S. Code but it didn't responding to some of the program but some can run...why?

### ISSUE THREAD

**Issue by Saurav-pundir** [microsoft/vscode-edge-devtools#1262]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
I have a hard time understanding your problem, can you give us more information?
