### ISSUE TITLE
I want to use my Live Server Reviewer but my F1 function will not respond.

### ISSUE THREAD

**Issue by Talm009** [microsoft/vscode-edge-devtools#1263]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
I have no idea what that means, but here is a video how to use the extension with live server:
https://www.youtube.com/watch?v=HRpG_LLx0fI&feature=youtu.be
