### ISSUE TITLE
live server problem, mathod problems

### ISSUE THREAD

**Issue by ShaplaCoder** [microsoft/vscode-edge-devtools#1264]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

in many case mathods don't work properly such as alert, confirm and many more
the extension also doesn't start with live server directly

**Comment by codepo8** [comment]
Hello there, you are correct that some methods of the browser don't work, including alert(). However, these are pretty outdated and basic ways to debug and terrible to interact with end users anyway. We will work on a list of things that don't work in the embedded browser to work around these confusions.

Live server is a different extension and not part of this (yet - we are working on a solution). However, for now all you need to do is copy and paste the address of the live server into the embedded browser. That also gives you the developer tools and the console for debugging - so you don't need any alert(). 

You can see it in action in this video: https://www.youtube.com/watch?v=HRpG_LLx0fI&feature=youtu.be
