### ISSUE TITLE
Dev tools not responding

### ISSUE THREAD

**Issue by Aerom1** [microsoft/vscode-edge-devtools#1267]
**Environment**
 - OS Windows 10
 - Extension version v2.1.1

**The bug:**
I was working on my project on VSC and Edge. 
I work with the browser window of Edge, not the headless version in VSC.
I was browsing the z-index of my php page with the 3D-view in dev-tools.
Everything was working fine.
Then I started to do other stuff, maybe directly in VSC (I don't remember). I don't really know what happened but at some point, dev-tools was not responding.
Since then, dev-tools is still dead. Edge works fine, the problem is only with dev-tools.

I rebooted the computer, cleaned cache, repaired edge with microsoft tool... nothing.
I suppose there's a problem with 3D-view (when starting, it's opened by defaut because it was the last tool opened).

When I open dev-tools (F12), the sidebar is showing up, I can see then menus (Elements, console, sources, network...) but i can't open them :
**Clicking on anything in dev-tools has no effect**. 
There are 2 devtool tools displayed (but empty) : Console and 3D-view.

**Repro steps:**
I don't know.

**Expected behavior:**
Dev-tools working.

Hey, guess what ! I was explaining this problem to someone, and suddenly **it worked again !**
I don't know why... After repairing it was still not working, but i left the window opened in order to do the screenshot (hereafter), and 5 minutes later i come back to the window and it works. I 've closed edge and restarted the debug session, it still works. So cool, and sorry for the long reading :)

**Additional context:**
![image](https://user-images.githubusercontent.com/65051479/203414596-a85c5ca7-d7a4-40b4-b16f-81903681fbd3.png)

**Comment by captainbrosset** [comment]
Thanks so much for reaching out. Some bugs are just really hard to repro, and then automagically fix themselves 😂
Still, we should keep an eye on this. There could indeed be something with the 3D View.

If this ever happens again, could you please do the following:

- Undock DevTools so it's in its own window.
- Open DevTools on DevTools (press ctrl+shift+I again after having focused the undocked DevTools window).

This will open a second DevTools window that debugs the first one, and in it, there will probably be console errors that would help us a lot understand the issue.

**Comment by Aerom1** [comment]
Hello Captain, the problem happened again tonight.
I clicked on 3D view and immediately the window froze.
Impossible to undock DevTools, impossible to open DevTools' debuger, sorry :/

Like yesterday, everything went to normal after 5-10 minutes waiting, leaving edge opened with the link to vsc active.

**Comment by captainbrosset** [comment]
Oh, I see. Then one thing you can do is undock devtools while things are running normally, and keep it this way.
This way, every time you open devtools, it will be undocked, and you should be able to open the other devtools window from it. Unless, of course, if the freeze is so bad that even opening devtools on devtools doesn't work. In which case, you'd need to have the devtools on devtools also opened at all times, until the freeze happens, which isn't super convenient.

A few questions that might help the team investigate:
- Does it always happen now when opening the 3D View?
- Which operating system and Edge version are you using?
- When launching the project from VSCode, do you use the DevTools embedded in VSCode, or just the ones in the browser window?

@codepo8 seems like an important crasher bug to triage with the team.

**Comment by codepo8** [comment]
Seems the 3D viewer is a performance issue in the tool, I will add it to the backlog.

**Comment by Aerom1** [comment]
![image](https://user-images.githubusercontent.com/65051479/203855864-26dbde7a-bfae-445c-b3b8-0e27738495d0.png)

**Comment by Aerom1** [comment]
![image](https://user-images.githubusercontent.com/65051479/203856004-85a010cb-3e23-4749-8830-2d1499202e87.png)
Microsoft Edge - Version 107.0.1418.56 (Version officielle) (64 bits)

**Comment by Aerom1** [comment]
When launching the project from VSCode, I use the DevTools in the browser window. It's the one that freezes. The one that is embedded in VSCode works, even when the other one fails.

**Comment by Aerom1** [comment]
When I launch DevTools in DevTools, this is what's written in VSC terminal : 
![image](https://user-images.githubusercontent.com/65051479/203856321-c17ea38a-b258-4ed8-9b2f-5b4a3848178d.png)

There is a lot of messages, I can't copy-paste all of them at once (selection doesn't work properly)
Here are some others :
![image](https://user-images.githubusercontent.com/65051479/203856514-e3ea7f23-eeae-4da4-b3d1-ed224d5de616.png)

**Comment by Aerom1** [comment]
When all the error messages have finished to be displayed, the DevTools in DevTools closes itself.

**Comment by codepo8** [comment]
I would opt for moving this out of this repo and into the main DevTools one as it isn't related to the VS Code integration, but happens on the main browser window.

**Comment by Aerom1** [comment]
The problem now happen's each time I click on 3D view.

**Comment by Aerom1** [comment]
Maybe my website is so shitty that it broke Edge 😂

**Comment by robpaveza** [comment]
Hey @Aerom1 ! Thanks for reporting this issue. I want to triage it a bit more, and maybe you've already answered this in one way or another, but I want to make sure we're narrowing it down to 3D View if that's actually the issue. Can you do the following?

 - Close all instances of DevTools
 - Open another site or application (even this one), and open DevTools
 - In that new instance of DevTools, make sure 3D View is closed. You can do this by right-clicking on the tab for 3D View and choosing "Close". (If you're in Focus Mode and it happens to be in the Quick View pane, please select a different tool for the Quick View pane).
 - Close that, and go back to your application
 - Can you activate DevTools now? Are you able to navigate the tools, e.g., Elements, Sources, Console, and Performance?
 - If you then activate 3D View, is that when it breaks?

Thanks!

**Comment by Aerom1** [comment]
Hey Rob,
Here are the steps done :

1. I opened the browser and navigated to www.github.com
2. Last instance of 3D view in devtools was still active, so when I opened devtools, it froze for ~15min.
3. When devtools responded, I made sure 3D view tab was closed and no other 3D view tab were opened even in the quick view pane. I selected other tools in devtools : all other tools work (Elements, Sources, Console, and Performance)
4. I close devtools.
5. I navigate to my application and open devtools : all other tools work (Elements, Sources, Console, and Performance)
6. I activate 3D view -> it breaks

**Comment by Aerom1** [comment]
7. After 10-20min 3D view opens up. Everything seems to work well, I can move the 3d view, highlight elements on the html view by hovering them in the 3D view, etc...
8. I close edge and reopen it.
9. Click on 3D view -> it breaks.

**Comment by captainbrosset** [comment]
Thanks for taking the time to test and reporting your findings. This is going to be super useful.

**Comment by vidorteg** [comment]
[Cleaning] I took a look and this issue seems to be in the browser Devtools as 3d view is not available in the extension, still I tested and seems it has been so far fixed as 3d view is working as expected in the Edge browser. Please feel free to open a new issue if you encounter any related problems.
