### ISSUE TITLE
alert()/prompt()/confirm() doesn't work in the DevTools

### ISSUE THREAD

**Issue by TianYuanSX** [microsoft/vscode-edge-devtools#1271]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11 Home Edition 22H2
 - Extension version (*e.g.,* 1.2.3): v.2.1.1

**Describe the bug:**

No pops-up is shown as expected in Edge DevTools: Browser.

**Repro steps:**

1. Create a html file.
2. Write the following code within <script> section
`window.alert("Hello World!")`
3. Right click this file, Open with Edge, Open with Browser
**Expected behavior:**

A window would pop up saying hello world, but nothing happened. 
**Additional context:**

![Uploading pops-up-bug.gif…]()

**Comment by captainbrosset** [comment]
Thanks for reaching out. We'll make sure this bug shows up on the team's radar for prioritization and investigation.

**Comment by codepo8** [comment]
This is a known limitations of the browser preview right now and we are looking into making this work in future versions. For now, using console.log() is the much better way to log messages. Thank you for reporting, marking this as a duplicate.

**Comment by Asoftyn** [comment]
I dont think this issue should be closed as completed as this is a issue that still persists in current version of browser preview.
