### ISSUE TITLE
running executables path

### ISSUE THREAD

**Issue by Wiltorres73** [microsoft/vscode-edge-devtools#1276]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

typing new code and running executables continues to fail. Using another kind works fine. Let me know what should do for the further due to this not being the only time building sites. 
**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Hi, thanks for reaching out, unfortunately I don't think there's enough information here for the team to investigate a potential issue.
Could you please comment again explaining exactly what you were doing and what you expected to happen, and what happened instead?
I don't understand what you mena by typing new code, and running executables. Could you please clarify?
