### ISSUE TITLE
Go live doesn't work

### ISSUE THREAD

**Issue by AmenAllah08** [microsoft/vscode-edge-devtools#1279]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

My go live didn't work , each time i press on it, it doesn't work, i don't know why

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please comment back here and explain in more details what you do that doesn't work?
What button do you press? A screenshot would actually help too. What do you expect should happen, and what happens instead?
Is there any error shown anywhere?
Thanks a lot for your help!
