### ISSUE TITLE
.main{     width: 100%;     background: linear-gradient(to top, rgba (0,0,0,0.5) 50% ,rgba (0,0,0,0.5)50%), url(1.jpg)     background-position: center;     background-size: cover;     height::after 109vh;

### ISSUE THREAD

**Issue by dimaryorina** [microsoft/vscode-edge-devtools#1304]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.
