### ISSUE TITLE
my live servers arn't displaying live or showing any changes. 

### ISSUE THREAD

**Issue by HpFontenot1993** [microsoft/vscode-edge-devtools#1305]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks @HpFontenot1993, could you please describe in more details the issue that you are facing?

**Comment by HpFontenot1993** [comment]
Hello,

The problem has sense then been fixed. I uninstalled the extension on vs
code. At the time it was showing on my tasks that the window was being
suspended. Causing the functions not to work. So, I just reinstalled the
extension. Thank you.

Hpf
