### ISSUE TITLE
OUTPUT

### ISSUE THREAD

**Issue by kassefallou** [microsoft/vscode-edge-devtools#1310]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by kassefallou** [comment]
OUTPOT c'est application de jeux gratuit

**Comment by captainbrosset** [comment]
Closing as incomplete.
