### ISSUE TITLE
the browser color no fit theme

### ISSUE THREAD

**Issue by morning-start** [microsoft/vscode-edge-devtools#1313]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:** Set the browser color to be the same as the theme

**Describe alternatives you've considered:** Add a setting to control the default color

**Additional context:** 
![image](https://user-images.githubusercontent.com/76601464/210224262-3974f72e-7d0e-4eeb-8ffe-74ca3c764db2.png)

**Comment by codepo8** [comment]
This isn't a bug, but a confusion it seems. The colour schemes here are an accessibility feature of the operating system. not the theme of the browser.

**Comment by captainbrosset** [comment]
Chris is right, this option is simply a convenience for you to test your CSS code when you use the `prefers-color-scheme` media feature. It won't automatically change anything.
I'll close this issue for now. Please feel free to comment if you still have an issue with this option.
