### ISSUE TITLE
Doesnt working "<select> and <option>"

### ISSUE THREAD

**Issue by BurakYavass** [microsoft/vscode-edge-devtools#1315]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out. From the title of the issue, it seems that using `<select>` elements in the browser preview embedded in the extension does not work. Is this a correct interpretation of the issue you are having?
Can you please provide more information?

**Comment by BurakYavass** [comment]
![select option](https://user-images.githubusercontent.com/57116587/210359365-e1792938-21bf-4102-872a-007b358ac01f.png)

Hi , Thanks for your answer. I have to say i am new in this field so please correct me if i am wrong. As seen in the image, the area where I write the <select> command, but the  browser preview does not work either. But my code works in normal Edge browser.

**Comment by codepo8** [comment]
Hello and thank you for that report. We are aware of this issue and are trying to find a workaround for it.

**Comment by OptimBro** [comment]
Same here. The options don't open in devtools instance. I have to select options via keyboard.
![image](https://user-images.githubusercontent.com/52219366/210754498-3adf19ad-9fbe-4ccf-87a9-83d23d780273.png)
