### ISSUE TITLE
mehroj

### ISSUE THREAD

**Issue by mehrojj** [microsoft/vscode-edge-devtools#1319]
![free-icon-whatsapp-3670302](https://user-images.githubusercontent.com/116469582/210592770-85cbcf28-3ac8-4b0c-ae99-c152bf97c03c.png)

**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.
