### ISSUE TITLE
Detection of no-inline-styles has too wide blast radius, fails to account for undefined

### ISSUE THREAD

**Issue by hoijnet** [microsoft/vscode-edge-devtools#1325]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): macOS Ventura 13.0 (VSC 1.74.2)
 - Extension version (*e.g.,* 1.2.3): 2.1.1

**Describe the bug:**

The plugin warns when adding the style attribute, even if it is set to undefined, when undefined, it should not warn.

This may need an explanation. What I am doing is to remove a style element from an SVG, and applying the style directly to the elements instead of using the style. Which is the secure and correct thing to do in this case, as I need to make my html pass CSPs as the styles are dynamic.

For each element, something like `<rect {...props} style={undefined} />` is used in React to remove the style element, but keep the remaining properties of the SVG rect. In this case, the Edge tools should not warn, as the style will effectively be removed instead of added. At least it should be possible to add a line comment (like in eslint) that it is a false positive and should be dismissed.

**Repro steps:**
Add `style={undefined}` to a react element, such as `<rect/>`

**Expected behavior:**
Edge should not warn as there is no issue in this case, no style will be applied, and thus the warning is incorrect.

**Additional context:**
N/A

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. I feel like we've had this feedback in the past already. @codepo8 is this tracked already by any chance?

**Comment by codepo8** [comment]
This isn't tracked and should be a webhint bug. I will file accordingly.

**Comment by hoijnet** [comment]
Thanks, makes sense 🤩

**Comment by captainbrosset** [comment]
Closing this issue since @codepo8 said he filed a webhint bug instead.
