### ISSUE TITLE
hi who is that man????....  i limit and limit  and disconnected my personal system !!! help me   please help me... please ....

### ISSUE THREAD

**Issue by Sajadsanamzadeh** [microsoft/vscode-edge-devtools#1330]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as spam.
