### ISSUE TITLE
vs code chrome launch problem

### ISSUE THREAD

**Issue by Abhinavkrishna1223** [microsoft/vscode-edge-devtools#1334]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Abhinavkrishna1223** [comment]
problem in launching the code in chrome browser

**Comment by captainbrosset** [comment]
Hi @Abhinavkrishna1223, thanks for reaching out. However there isn't enough information here for us to investigate a potential issue.

Can you please describe your problem in more details? What do you mean by "launching the code"?
Also, this extension embeds the Edge DevTools in VSCode, so I'm a bit confused by the "chrome browser" part in your last comment.

**Comment by codepo8** [comment]
This is an edge extension, chrome won't work.
