### ISSUE TITLE
Many javascript commands are not working

### ISSUE THREAD

**Issue by Its-anand** [microsoft/vscode-edge-devtools#1339]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

There are so many feature that dont work in this extension like javascript alert, confirm, prompt and so many javascript events please fix them.

**Comment by captainbrosset** [comment]
Thanks for reaching out. The problems with alert, confirm, or prompt not working are known already, please see #1317.
You also mentioned that many JS events do not work, can you please clarify what you mean?

**Comment by Its-anand** [comment]
JavaScript events are html attributes which occure when we perform certain
task like onClick, onMouseLeave, onBlure etc. Many of them work perfectly
but most of them don't
