### ISSUE TITLE
Minify extension bundle

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-edge-devtools#1343]
`ms-edgedevtools.vscode-edge-devtools-2.1.1`

Looking over `extension.js` in the shipped extension build, I noticed that it is not minified:

<img width="806" alt="Screenshot 2023-01-25 at 3 55 53 PM" src="https://user-images.githubusercontent.com/12821956/214721218-a7b710d0-bd0d-446e-a48b-2d7912480dfa.png">

Can this file minified to reduce the extension size?

**Comment by captainbrosset** [comment]
Thanks for reporting this!
