### ISSUE TITLE
my live server is not running properly

### ISSUE THREAD

**Issue by kishork18** [microsoft/vscode-edge-devtools#1344]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out. We'd love to help but could you please provide more information about your particular issue? There isn't really enough information for us to investigate the problem here.

**Comment by kishork18** [comment]
Hello sir,
           Here is the information about my issue. When I try to run my
code through live server, it gets started on a respected port but doesn't
open in the browser. To open it in the browser I have to open it manually.
So what should I do? open it automatically in the browser.
