### ISSUE TITLE
High cpu usage + temp

### ISSUE THREAD

**Issue by Brent-prod** [microsoft/vscode-edge-devtools#1363]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. If you have more information, like a specific scenario for us to reproduce a problem, please comment and we can re-open the issue.
