### ISSUE TITLE
unable to open https links

### ISSUE THREAD

**Issue by Max-Lumnar** [microsoft/vscode-edge-devtools#1364]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**
just trying to open a https:// link and it redirects me to http://https//domain..

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Max-Lumnar** [comment]
just trying to open a https:// link and it redirects me to http://https//domain..

**Comment by captainbrosset** [comment]
Thanks for reporting!
Would you be so kind and try to fill in some of the info in the issue description above? In particular your OS and extension version would be helpful!

**Comment by codepo8** [comment]
This was an issue before and we fixed it. Seems we forgot the s in https when redirecting…

**Comment by captainbrosset** [comment]
Ah, cool, thanks Chris. Let me close this out then. @Max-Lumnar if this still happens for you, make sure you have the latest version of the extension. If it still occurs after that, please comment here and provide as much information as you can for us to reproduce the issue.
