### ISSUE TITLE
LIBYA

### ISSUE THREAD

**Issue by GODLHEART** [microsoft/vscode-edge-devtools#1370]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by GODLHEART** [comment]
![received_597072895584918](https://user-images.githubusercontent.com/84987920/219501129-39adef4d-50ac-40ba-9e1e-011e7b678827.jpeg)

**Comment by GODLHEART** [comment]
**TEST**

**Comment by GODLHEART** [comment]
HI

**Comment by GODLHEART** [comment]
`HELLOWORD`

**Comment by captainbrosset** [comment]
Closing as incomplete.
