### ISSUE TITLE
Not able to see the script file content after linking it

### ISSUE THREAD

**Issue by Dhirajchaudari** [microsoft/vscode-edge-devtools#1375]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for the report. However, could you please more information about the problem you are facing with the extension?
What do you mean by "linking it"? Where are you not seeing the content?
The best way to help us would be to provide a clear list of steps to follow to replicate the problem. Screenshots also help a lot.
