### ISSUE TITLE
Can't understand the good workflow to debug a chrome extension

### ISSUE THREAD

**Issue by 4x10m** [microsoft/vscode-edge-devtools#1378]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): 2.1.1

# FR

**Describe the bug:**
Donc je suis conscient que l'utilisation de vscode pour débugger une extension de navigateur semble sortir des cas d'utilisations les plus usuels pour lesquels les solutions déjà en place semblent plus fiables.
Ce que je voudrais c'est que la sortie de console du service worker de l'extension pour navigateur que je suis en train développer soit affichée dans la console de remote debug de vscode accompagnée de, si possible, une console REPL et le stockage mais la console reste l'élément le plus "difficile" à avoir lorsque l'on développe une extension Edge. En effet, même si il y a plusieurs façon d'y parvenir, aucune n'est confortable. La manière normal consiste à ouvrir la gestion des extensions pour cliquer sur le service worker et voir une fenêtre s'ouvrir, celle-ci étant une console de débuggage connecté au service worker (cette fenêtre se déconnecte (mais ne se ferme pas LOL) à chaque rechargement de l'extension LOL). Perso j'ai rusé puisque la première page ouverte après le rechargement de l'extension est ELLE connecté à tout ce qu'il se passe dans l'extension donc j'ai fais en sorte qu'elle s'ouvre toute seule et il me restera alors à F12 (et oui, à chaque rechargement de l'extension puisque le service worker ferme tous les onglets qu'il a ouvert LOL).

Bref tout cela est d'une galère sans nom et je compte y rajouter vscode LOL.
J'ai donc, déjà, deux façons différentes de lancer Edge en passant par l'extension Edge Devtool ou par un launch.json. Alors déjà c'est marrant parce que faut comprendre que les paramètres de Edge Devtool n'agissent QUE sur les instances lancées via le bouton de celle-ci. Oui parce que le fameux paramètre headless, on ne peut pas le mettre dans un lancement {type:"msedge", request: "launch"} (ha si, si, je t'assure et c'est pas comme si le linter te le disait, c'est juste que RIEN ne se passe pendant que tu attends comme un poireau, mais c'est pas la meilleure, CE PARAMETRE MARCHE SUR UN LANCEMENT DE TYPE "pwa-msedge" (l'ancienne (?) syntaxe). En fait, je ne sais pas si vous voyez ou je veux en venir mais tout cela s'emboite de façon très naturel quand on fait l'histoire à l'envers (autrement dit de la syntaxe la plus ancienne à la plus récente) et arrivé à la fin on a juste envie de se tirer une balle car on a l'impression que y'a un mec il a tout changé parce que c'était ultra worth sur son cas d'utilisation quitte à ce que ça détruise tout le reste (rien à voir mais coucou Manifest V3 =)).
Doit-on évoquer que les templates par défaut et donc la méthode recommandé par Microsoft pour faire tout cela sont DEPRECIES d'office.
Doit-on évoquer la non possibilité d'ajouter des extensions à un Edge headless ? Je sais que c'est en route.
Mais j'ai gardé le meilleur pour la fin. Alors vous m'excuserez, je n'ai pas trouvé de référence plus verbeuse que celle-ci (https://code.visualstudio.com/docs/editor/debugging, le lien en haut du fichier dans le template par défaut) mais, par exemple, la propriété prelaunchtask, on ne sait ni ses sous propriétés, ni leurs détails, ni rien, en fait, à part l'autocomplétion (merci de m'avoir éviter d'aller dans le code) mais puisqu'on l'évoque, parlons en de l'auto complétion. Que dit-elle pour le paramètre "userDataDir": "set to false to launch with your default user profile", alors peut-être que j'ai mal compris et que ça veut très précisément dire de "ne pas lancer edge avec l'utilisateur que tu utilises d'habitude en dehors de cette utilisation de développeur" mais sinon c'est complément FAKE FAKE FAKE et c'est, actuellement, totalement l'inverse. C'est à dire, que moi, il faut que je mette true pour que mon profile usuel se charge LOL. Bon et puis "vscode-edge-devtools.userDataDir" dans les paramètres d'utilisateur, c'est la petite cerise hein, ce paramètre ne fait rien du tout.

Bon j'ai quand identifié des choses qui me plaisent même si, en l'état, elle ne me serviront à rien dans mon cas d'utilisation puisque le peu que je gagne à avoir mon service worker dans vscode, je le perd dans la longueur du workflow.
Donc je lance mon edge via launch.json (oui parce que il ouvre le port de remote debugging tout seul) avec seulement mon userdatadir, ensuite, je vais dans la vue Microsoft Edge Tools de vscode, je fais rafraichir, je cherche mon service dans les (frames?) qui apparaissent, je prend l'adresse websocket de mon serviceWorker et je la met dans mon launch.json > attach node > websocketaddress et la on commence à être bien. Là ou vscode ferait la différence pour moi, ça serait si il était capable d'aller chercher et de se connecter à cette websocketurl tout seul.

**Repro steps:**

not appropriate

**Expected behavior:**
Avoir la sortie de console du service worker de mon extension navigateur dans les edge tools de vscode en pressant F5

**Additional context:**

Donc, oui, j'imagine que le ton employé dans ce message laisse transparaitre mon agacement mais j'ai perdu trop de temps, pour tester tout cela et je le regrette. J'espère que vous saurez faire la part des choses et ne pas le prendre personnellement voir, même, avec humour.

Finalement, en dehors de l'aspect purement technique du problème, c'est mon syndrome de l'imposteur qui se réveille et j'en vient à me demander si je fais bonne route et si les solutions que je développe correspondent répondent correctement à mes besoins, à savoir un user script et si je n'ai pas raté un truc dans l'air du temps

# EN

**Describe the bug:**

So I'm aware that using vscode to debug a browser extension seems to be out of the most usual use cases for which the solutions already in place seem more reliable.
What I would like is that the console output of the service worker of the browser extension I'm developing is displayed in the vscode remote debug console along with, if possible, a REPL console and the storage but the console remains the most "difficult" element to have when developing an Edge extension. Indeed, even if there are several ways to get it, none of them is comfortable. The normal way is to open the extension management to click on the service worker and see a window opening, this one being a debugging console connected to the service worker (this window disconnects (but doesn't close LOL) each time the extension reloads LOL). Personally, I've done a trick since the first page opened after the extension reload is connected to everything that happens in the extension so I've made sure that it opens by itself and I'll have to F12 (and yes, at each reload of the extension since the service worker closes all the tabs that it has opened LOL).

In short, all this is a pain in the ass and I intend to add vscode LOL.
So I already have two different ways to launch Edge, using the Edge Devtool extension or a launch.json. It's funny because you have to understand that the parameters of Edge Devtool act ONLY on the instances launched via the button of this one. Yes, because the famous headless parameter, you can't put it in a launch {type: "msedge", request: "launch"} (yes, yes, I assure you and it's not as if the linter told you, it's just that NOTHING happens while you're waiting like a leek, but it's not the best, THIS PARAMETER WORKS ON A LAUNCH OF TYPE "pwa-msedge" (the old (?) syntax). In fact, I don't know if you see what I'm getting at but all this fits together in a very natural way when you do the story in reverse (in other words from the oldest syntax to the most recent one) and when you get to the end you just want to shoot yourself because you have the impression that there's a guy who changed everything because it was ultra-worthy for his use case even if it destroys everything else (nothing to do with that but hello Manifest V3 =)).
Should we mention that the default templates and therefore the method recommended by Microsoft to do all this are already depreciateds.
Should we mention the lack of ability to add extensions to an Edge headless? I know it's on the way.
But I saved the best for last. So you'll excuse me, I couldn't find a more verbose reference than this one (https://code.visualstudio.com/docs/editor/debugging, the link at the top of the file in the default template) but, for example, the prelaunchtask property, we don't know its sub-properties, nor their details, nor anything, in fact, except for the autocompletion (thanks for saving me from going into the code) but since we're talking about it, let's talk about the autocompletion. What does it say for the "userDataDir" parameter: "set to false to launch with your default user profile", so maybe I've misunderstood and it means precisely "don't launch edge with the user you usually use outside of this developer use" but otherwise it's FAKE FAKE FAKE completion and it's, actually, totally the opposite. That is to say, that I have to set true for my usual profile to load LOL. Well and then "vscode-edge-devtools.userDataDir" in the user parameters, it's the little cherry eh, this parameter does nothing at all.

Well, I have some things I like even if, as it is, they won't help me in my use case since the little I gain by having my service worker in vscode, I lose it in the length of the workflow.
So I launch my edge via launch.json (yes because it opens the remote debugging port by itself) with only my userdatadir, then I go to the Microsoft Edge Tools view of vscode, I refresh, I look for my service in the (frames?) that appear, I take the websocket address of my serviceWorker and I put it in my launch.json > attach node > websocketaddress and we start to be good. Where vscode would make the difference for me, it would be if it was able to fetch and connect to this websocketurl by itself.

**Repro steps:**

not appropriate

**Expected behavior:**
Have the console output of the service worker of my browser extension in vscode edge tools by pressing F5

**Additional context:**

So, yes, I guess the tone used in this message shows my annoyance but I wasted too much time, to test all this and I regret it. I hope you will be able to see the difference and not take it personally or even with humor.

Finally, apart from the purely technical aspect of the problem, it's my impostor syndrome that's waking up and I'm wondering if I'm doing the right thing and if the solutions I'm developing correspond to real needs, namely a user script, and if I haven't missed something in the air of time

**Comment by codepo8** [comment]
Thanks for the detailed report. My guess is as the browser instance by default is headless, you also have no access to your extensions. Even more, the extension fires off a brand new instance. If you already have an instance with your extension running, it should show up in the targets list. does it?

**Comment by captainbrosset** [comment]
> What I would like is that the console output of the service worker of the browser extension I'm developing is displayed in the vscode remote debug console along with, if possible, a REPL console and the storage.

That would indeed be a pretty nice development tool. Unfortunately, this isn't a use case that our VS Code Edge DevTools extension has set out to tackle.

> The normal way is to open the extension management to click on the service worker and see a window opening, this one being a debugging console connected to the service worker (this window disconnects (but doesn't close) each time the extension reloads)

That is indeed the normal way to do this. Can you please help me understand what you mean by the window disconnecting? This sounds like a bug to me that we should fix. I just tried locally with a sample extension that has a service worker, and the window seemed to continue working after I reloaded the extension. To test this, I added a breakpoint in the service worker file, and it got hit correctly, even after a reload.

Sorry you feel frustrated with this development environment, but I think the right course of action for your request is:

1. Closing this issue as I don't think this project will evolve to answer your need.
2. Opening a new issue on the DevTools repo instead to investigate fixing the disconnected window problem you mentioned. Here is that other repo: https://github.com/MicrosoftEdge/DevTools/
