### ISSUE TITLE
remoteHub.logLevel not working ....repository button error on operation

### ISSUE THREAD

**Issue by Shamim-Nkatha** [microsoft/vscode-edge-devtools#1381]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please add more information about your exact problem for us to investigate.
