### ISSUE TITLE
Pagina inicial

### ISSUE THREAD

**Issue by hiergrs** [microsoft/vscode-edge-devtools#1391]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by hiergrs** [comment]
ajud

**Comment by captainbrosset** [comment]
Closing as incomplete.
