### ISSUE TITLE
Looks like extensions are not enabled n the tools.

### ISSUE THREAD

**Issue by MiguelSchneider** [microsoft/vscode-edge-devtools#1392]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by MiguelSchneider** [comment]
I'd like to test some Apps that work with Metamask

**Comment by captainbrosset** [comment]
Hello, can you please explain in more detail what you mean by extensions not being enabled? 
Our VS Code DevTools project is already an extension in itself, so I'm not understanding your question.

**Comment by MiguelSchneider** [comment]
Maybe this snapshot helps: It is an App which requires that I connect a Metamask (https://metamask.io/download/) wallet. A Metamask wallet is basically a browser extension. It turns out that the browser in Visual Studio (provided by the Edge tools) does not have a way to enabling the extensions, so I cannot connect the wallet.

As a side note, I have the Metamask extension installed in my Edge browser and it works like a charm. 

![image](https://user-images.githubusercontent.com/2051119/223683862-db92b5b7-4d70-4bf9-9573-5f6ddc993db0.png)

**Comment by HendrikThePendric** [comment]
I like using the "Microsoft Edge Tools" in VSCode but also like using DevTools extensions like "React DevTools" and "Redux DevTools". Currently it seems these can't be used together, which is a shame. I think a lot of frontend developers would benefit from being able to access these extensions from within vscode-edge-devtools.

Here's a screenshot of my standalone Edge, with React and Redux DevTools:
<img width="1726" alt="Screenshot 2023-09-05 at 11 55 15" src="https://github.com/microsoft/vscode-edge-devtools/assets/353236/82a1da53-af1a-46d8-bae7-6143dc02bb9a">

And here's a screenshot of my DevTools window within VSCode:
<img width="958" alt="Screenshot 2023-09-05 at 11 55 30" src="https://github.com/microsoft/vscode-edge-devtools/assets/353236/c70f4833-659d-42f6-9dbe-ad2aa6f075fe">

**Comment by captainbrosset** [comment]
Let's use #1039 to track the work of using extensions in the embedded Edge browser and embedded DevTools.

**Comment by lopugit** [comment]
Ohh wait so the vscode edge browser is a different instance to your personally installed one? :( 

https://github.com/microsoft/vscode-edge-devtools/issues/2256
