### ISSUE TITLE
spkac <string> | <ArrayBuffer> | <Buffer> | <TypedArray> | <DataView> encoding <string> The encoding of the spkac string. Returns: <Buffer>

### ISSUE THREAD

**Issue by Haitham103** [microsoft/vscode-edge-devtools#1393]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete.
