### ISSUE TITLE
Can't view a page

### ISSUE THREAD

**Issue by khal-at-github** [microsoft/vscode-edge-devtools#1395]
I tried viewing a Youtube Video on the Dev tools but I couldn't view it, so I guess you won't be able to view a webpage with a video.

**Comment by captainbrosset** [comment]
I have a feeling that you're right and that the browser preview that's embedded in VS Code when using the extension can't stream videos.
You can also configure the extension to use an external browser instead. And that should make it possible to view videos.
See https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/external-browser-window

@vidorteg am I correct in my assumption above? If so, this might be worth adding to the list of known issues and won't fix issues in #1317.

**Comment by captainbrosset** [comment]
Closing as inactive. Please feel free to comment and we can always re-open the issue if there's anything that needs to be fixed here.
