### ISSUE TITLE
liveserver starts port but doesn't load the default browser and i have tried all settings and configuration online but to no avail

### ISSUE THREAD

**Issue by ayodamani** [microsoft/vscode-edge-devtools#1408]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, but I'm afraid there isn't enough information for us to investigate a potential issue here.
Are you able to share your steps that lead to the problem? Perhaps your VS Code project configuration too? Also the version of the extension that you're using.
These would be useful in investigating.
