### ISSUE TITLE
# Note: you need to be using OpenAI Python v0.27.0 for the code below to work import openai  openai.ChatCompletion.create(   model="gpt-3.5-turbo",   messages=[         {"role": "system", "content": "You are a helpful assistant."},         {"role": "user", "content": "Who won the world series in 2020?"},         {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},         {"role": "user", "content": "Where was it played?"}     ] )

### ISSUE THREAD

**Issue by huanghaivip** [microsoft/vscode-edge-devtools#1411]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by huanghaivip** [comment]
# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

**Comment by captainbrosset** [comment]
Closing as incomplete.

**Comment by huanghaivip** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
