### ISSUE TITLE
EDGE BROSWER NOT RUNING TO DEBUGING IN WINDOWS 11 OS

### ISSUE THREAD

**Issue by SidhiqAbu** [microsoft/vscode-edge-devtools#1423]

**Comment by SidhiqAbu** [comment]
vs code edge broswer not runing for debuging code in windows 11 os

**Comment by captainbrosset** [comment]
Hi @SidhiqAbu, thanks for reporting this.
Could you please give us a bit more information about your problem? There isn't enough here yet for us to investigate.

Some things that would be helpful:

* Version of the vscode-edge-devtools extension you are using.
* Version of VS Code.
* A precise description of the problem. For example: how is your project set up, how did you try to run edge, what steps did you take, what did you expect, and what happened instead?

The more you can tell us, the easier it will be for us to fix the issue. Thanks a lot!
