### ISSUE TITLE
Restore all default settings

### ISSUE THREAD

**Issue by afceben** [microsoft/vscode-edge-devtools#1425]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by afceben** [comment]
Only one file in a document keeps loading when i click on run without debugging

**Comment by afceben** [comment]
Only one file in a document keeps loading when i click on run without debugging

**Comment by afceben** [comment]
when i edit an html file and i click on run it either keeps on opening the
same file or it doesn't come at all. I found out that it had something to
do with the configuration which says launch program, attach and some other
commands when i click on them the same thing happens .I also tried editing
the settings.json file but i was told its not an editor i'm using so i
can't make any changes to settings.json.I deleted the contents of
launch.json and the problem seems to have been solved. Now i can load all
html files

**Comment by captainbrosset** [comment]
Oh ok, glad that you figured it out. I'll close the issue now.
