### ISSUE TITLE
prompt function not working

### ISSUE THREAD

**Issue by leoyenet** [microsoft/vscode-edge-devtools#1435]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): 2.1.1

**Describe the bug:**

when opening file/.../.html if you try to use prompt() it crashes extension 

**Repro steps:**

when opening file/.../.html if you try to use prompt() it crashes extension 

**Expected behavior:**

pop up a prompt that helps while experimenting.
**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for your feedback. This is a known current limitation of the extension, which is already tracked in #1317. So I'll close this duplicate issue.
