### ISSUE TITLE
Undockable panes

### ISSUE THREAD

**Issue by badde-media** [microsoft/vscode-edge-devtools#1437]
**Is your feature request related to a problem? Please describe.**

I have a dual monitor setup and I want to use VSCode's internal Edge and Devtools. I want the Devtools to be on the second display. That's not possible now.
**Describe the solution you'd like:**

I'd like to be able to drag and drop any sub-window to another location, independent from the main window.
**Describe alternatives you've considered:**

Stretching thémain window over the different monitors, but since the displays are arranged vertically, the Windows Taskbar is in the way. For now, I'm using the system's Edge and its devtools, but these don't integrate as well with VSCode.
**Additional context:**

**Comment by captainbrosset** [comment]
Interesting, thanks for filing this.
Just a question: is it possible to drag and drop other VS Code panels to another monitor as you mention? In other words: is this a problem with our devtools extension, or with VS Code all up?

**Comment by badde-media** [comment]
Oh, it's a general VSCode problem. Sorry for posting in the wrong corner.
