### ISSUE TITLE
Configuration 'Launch Edge Headless and attach DevTools' is missing in 'launch.json'.

### ISSUE THREAD

**Issue by nibuhuigenzheduba** [microsoft/vscode-edge-devtools#1440]
Configuration 'Launch Edge Headless and attach DevTools' is missing in 'launch.json'

**Comment by captainbrosset** [comment]
Thanks for reaching out. Based on what you're saying, it seems like you should be able to just add this configuration again yourself, or re-generate a new launch.json file.
More information: https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/get-started-launch-project

I'm not sure that this is helpful. If not, please do send more details over so the team can investigate a potential problem.
