### ISSUE TITLE
Unable to Debug Angular app

### ISSUE THREAD

**Issue by stephenburrows** [microsoft/vscode-edge-devtools#1442]
**Environment (please complete the following information):**
 - OS  Windows 10
 - Extension version  2.1.1

When trying to launch the dev debug with VS code the extension is unable to open the browser window and gives a error

this issue has only occurred with the update of to VSCode 1.77 the extension work as expected in version 1.76*

the output for the Microsoft Edge tools  is as follows'

> Error loading "hint" package from "c:\APM-Final"
> 
> Trying to load shared version
> 
> Found hint at
> c:\Users\sburrows\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
> 
> Checking if shared version of "hint" needs updated
> 
> Last check for "hint" updates was less than 24 hours ago, skipping

and I get the following notification
> Error processing requestCDPProxy: TypeError: (void 0) is not a
> constructor
>     at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:25819
>     at Na (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:25298)
>     at ib (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:26321)
>     at Lp.createServer (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:28797)
>     at Lp.proxy (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:102:28606)
>     at ml._requestCDPProxy (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:157:7130)
>     at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:156:3613
>     at $h._onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:71:4699)
>     at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:71:3128
>     at X.fire (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:67:31984)
>     at Socket._handleData (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:153:706)
>     at Socket.emit (node:events:526:28)
>     at addChunk (node:internal/streams/readable:315:12)
>     at readableAddChunk (node:internal/streams/readable:289:9)
>     at Socket.Readable.push (node:internal/streams/readable:228:10)
>     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

the following is my lauch.json and task.json

## launch.json

```Json
{
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Frontend",
      "type": "msedge",
      "request": "launch",
      "preLaunchTask": "Serve Frontend",
      "runtimeArgs": ["--headless"],//If you only want with to debug in vscode
      "url": "http://localhost:4200/#",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
      "skipFiles": [
        "${workspaceFolder}/<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
      ]
    }
  ]
}
```

[temp](https://go.microsoft.com/fwlink/?linkid=830387)

## tasks.Json

```Json
  {
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Serve Frontend",
      "type": "npm",
      "script": "start:frontend",
      "isBackground": true,
      "presentation": {
        "focus": true,
        "panel": "dedicated"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": {
        "owner": "typescript",
        "source": "ts",
        "applyTo": "closedDocuments",
        "fileLocation": [
          "relative",
          "${cwd}"
        ],
        "pattern": "$tsc",
        "background": {
          "activeOnStart": true,
          "beginsPattern": {
            "regexp": "(.*?)"
          },
          "endsPattern": {
            "regexp": "Compiled |Failed to compile."
          }
        }
      }
    }
  ]
}
```

## Add New Script to package.jason

```Json
"start:frontend": "ng serve --host=127.0.0.1",
```

any help would be appreciated

**Comment by captainbrosset** [comment]
Thanks for the detailed report. I'll make sure this shows up on our team's radar for investigation and prioritization.

**Comment by stephenburrows** [comment]
This looked like a VSCode issue as of version 1.77.1 , my issue seems to have been resolved

**Comment by captainbrosset** [comment]
Great, thanks for reporting back. Closing.
