### ISSUE TITLE
div is not moving right

### ISSUE THREAD

**Issue by Rav9jsn** [microsoft/vscode-edge-devtools#1451]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
