### ISSUE TITLE
when i try to change svg by css animation , it's use a lot of memory and CPU

### ISSUE THREAD

**Issue by stermso** [microsoft/vscode-edge-devtools#1478]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
