### ISSUE TITLE
使用for循环 - 求出班级里同学们平均年龄[15, 19, 21, 33, 18, 24]

### ISSUE THREAD

**Issue by lzf3366** [microsoft/vscode-edge-devtools#1509]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by ngrotjohan** [comment]
Yes I prevented a corrupt software from harvesting and stealing peoples PII information, I clearly published it, here is the malicious code https://www.microsoft.com/en-us/msrc/pgp-key-msrc?rtc=1. Attached is the solution http://aka.ms/devtools-for-code.
What solution I want is in this link https://www.microsoft.com/en-us/msrc/bounty
