### ISSUE TITLE
PS C:\Users\aravi\.vscode\java files>  & 'C:\Program Files\Java\jdk-19\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:50140' '@C:\Users\aravi\AppData\Local\Temp\cp_8k424vbxhda4nk0i83u773ryj.argfile' 'collections.array_list' Error: Could not find or load main class collections.array_list Caused by: java.lang.ClassNotFoundException: collections.array_list PS C:\Users\aravi\.vscode\java files> 

### ISSUE THREAD

**Issue by ravikumar435** [microsoft/vscode-edge-devtools#1512]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
