### ISSUE TITLE
glitch  when scrolling over icons in vs code

### ISSUE THREAD

**Issue by kelvin-owino** [microsoft/vscode-edge-devtools#1525]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete for now. But please feel free to add more information if you have any and we can re-open the issue.
Right now, the issue doesn't contain enough information for us to investigate.
