### ISSUE TITLE
refactor webViewVersion polyfill

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#153]
webViewVersion polyfill requires to be refactored in the same way simpleView was refactored so that it uses the actual code and not the hardcoded text

**Comment by mliao95** [comment]
It looks like we do not use the getWebviewVersion function anywhere in the code outside of the test file.  Should we just remove webviewVersion.ts/webviewVersion.test.ts or hold onto it for some reason?
