### ISSUE TITLE
auto update the browser when saving a file

### ISSUE THREAD

**Issue by Kristopher12** [microsoft/vscode-edge-devtools#1554]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
If I understand correctly, you're looking for a live server feature. Something that will refresh the page whenever you make a change.
According to #1317 this is on the roadmap. We unfortunately don't have anything new to report on this at the moment. But in the meantime, you can use one of the VS Code extensions to preview and live reload your HTML, as explained here: https://code.visualstudio.com/docs/languages/html#_does-vs-code-have-html-preview
