### ISSUE TITLE
class Human {   constructor(name) {     this.name = name;     this.sureName = 'Smith';     this.speed = 0;     this.state = undefined;   }    run(speed) {     this.speed = speed;     alert(`Name: ${this.name}, Speed: ${this.speed}`);   }    stop() {     this.speed = 0;     alert(`${this.name} is stopped.`);   }    changeState(state) {     this.state = state;   } }  // Creating an instance of the Human class const john = new Human('John');

### ISSUE THREAD

**Issue by Hovo4686** [microsoft/vscode-edge-devtools#1565]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Hovo4686** [comment]
class Human {
  constructor(name) {
    this.name = name;
    this.sureName = 'Smith';
    this.speed = 0;
    this.state = undefined;
  }

  run(speed) {
    this.speed = speed;
    alert(`Name: ${this.name}, Speed: ${this.speed}`);
  }

  stop() {
    this.speed = 0;
    alert(`${this.name} is stopped.`);
  }

  changeState(state) {
    this.state = state;
  }
}

// Creating an instance of the Human class
const john = new Human('John');

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
