### ISSUE TITLE
powershell en visual studio code

### ISSUE THREAD

**Issue by angelcruzr** [microsoft/vscode-edge-devtools#1567]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by angelcruzr** [comment]
No puedo  usar powerhell el la terminal de visual studio code. No puedo iniciar el local host

**Comment by captainbrosset** [comment]
This seems more like a question/issue for the VSCode team. This repository here is specific to the Edge DevTools extension of VSCode.
I suggest reaching out to the team on their official repository here: https://github.com/Microsoft/vscode.
Thanks for your understanding.
