### ISSUE TITLE
I suggest to have extensions from Microsoft Edge Add-ons on vscode edge devtools

### ISSUE THREAD

**Issue by OmarMOHMD** [microsoft/vscode-edge-devtools#1578]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Can I ask a little clarification on this? I'm not sure I understand what you're asking.
It seems to me like you would like extensions such as React DevTools, or Vue DevTools, etc. to also be installable in the VSCode Edge DevTools extension. Is this correct?

**Comment by OmarMOHMD** [comment]
Exactly, that's what I mean. It would be great to add React DevTools, or Vue DevTools. to also be installable in the VSCode Edge DevTools extension.

**Comment by captainbrosset** [comment]
Thanks for the reply. In that case, this improvement is already tracked in #1039. So closing this one as a duplicate. Thanks again!
