### ISSUE TITLE
video.streams.filter(file_extension='mp4').first().download()

### ISSUE THREAD

**Issue by carlospard** [microsoft/vscode-edge-devtools#1580]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by carlospard** [comment]
video.streams.filter(file_extension='mp4').first().download()

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
