### ISSUE TITLE
I need to install node for visual studio but am a total newbie, can anyone help?

### ISSUE THREAD

**Issue by Bigbobcohen** [microsoft/vscode-edge-devtools#1586]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Bigbobcohen** [comment]
Guys, I'm lost have just installed visual studio and am informed I need to install nose and npm & was directed here to download them.
I've never programmed in anything more complex than bog standard html over 30 years ago and now have to rewrite my whole site to do with it what I need to do now I am an old man with failing faculties. LOL it's all getting a bit too much for this old fella. Have to take a relief break. Cheers 4 now. Hope you can point me in some other direction other than out->

**Comment by captainbrosset** [comment]
To work on rewriting your site with HTML, using VS Code, you don't need node and npm.
If you installed our VS Code Edge DevTools extension though, then yes, you will need to install these dependencies because the extension needs them.
To do this, you cna follow the instructions at https://nodejs.org/en. Installing node will also install npm automatically.
I hope this helps.

**Comment by Bigbobcohen** [comment]
Thanks so much Patrick, I've asked questions before and have found that saying I am a newbie does not guarantee that anyone will answer- so Cheers mate for that. Please tell me, whether or not I install node and npm, what I am hoping to accomplish is to be able to see within the bounds of the program is a graphical representation of the site so I can adjust things more in a WYSIWYG type of way. Will I actually need  node/nbm to accomplish that or can I do that using something within the menu system somehow. I have seen others demonstrate online with a WYSIWYG element displayed on the RH side of the screen but have not been able to work out how they turned it on.. 
I do hope I have made myself clear enough for you or someone else to give me an answer I can understand.
Many many thanks again for your answer- Regards Robert

**Comment by captainbrosset** [comment]
> a graphical representation of the site so I can adjust things more in a WYSIWYG type of way

You certainly do not need node and npm for this type of work. 
In fact, you don't need our VS Code DevTools extension either (which this repository is about). This extension gives you inspection and debugging tools to work on your HTML, CSS, and JavaScript code. But for this extension to be useful, you need to have knowledge of these programming languages in the first place.
It sounds like you, instead, are more interested in a no-code approach, where you can manipulate the elements in a graphical tool instead.
I'm not sure I can give you good advice on how to proceed. Maybe give webflow a try: https://webflow.com/
