### ISSUE TITLE
CSS Mirroring Not Working in WSL

### ISSUE THREAD

**Issue by chris-mcdonald-dev** [microsoft/vscode-edge-devtools#1589]
**Environment (please complete the following information):**
 - OS: Windows 11 WSL - Ubuntu
 - Extension version: 2.1.2

**Describe the bug:**

Trying to change CSS properties has no effect on the linked CSS file in VS code.

**Repro steps:**

Start any server in WSL and open it in the extension's browser.
Change any CSS property in the DevTools panel that has a link to the stylesheet you're editing in VS Code.

**Expected behavior:**

Expected the updated devtools styles to reflect in VS Code (CSS Mirroring feature).

**Additional context:**

This was mentioned in feedback for the initial CSS Mirroring issue (#476), but I wasn't able to find any comments addressing it or references to it in the pinned Known Issues (#1317). Is this something that isn't planned on being fixed? Thanks for everything!

**Comment by captainbrosset** [comment]
Thanks for reporting this. Let me copy your message over to #436 and close this issue, because I believe they're duplicate.
