### ISSUE TITLE
how can I increase the font size of the  Edge devtool's plugin in visual studio code ?

### ISSUE THREAD

**Issue by Elie77350** [microsoft/vscode-edge-devtools#1595]
how can I increase the font size of the Edge devtool's plugin in visual studio code ?

**Comment by captainbrosset** [comment]
I don't think there is a way to increase the font size of just the extension. But if you increase the font size in VSCode, globally, then the DevTools extension will also adapt.

To do this:
1. Click anywhere in VS Code (in a text editor for example).
2. Press Ctrl+ to bump the font-size.

Does this help?
