### ISSUE TITLE
IEChooser debugging in VSC

### ISSUE THREAD

**Issue by FluffyGhoster** [microsoft/vscode-edge-devtools#1611]
**Is your feature request related to a problem? Please describe.**
To debug some applications, it is necessary to use IEChooser.exe (%windir%\SysWOW64\F12\IEChooser.exe), which is not as a nice environment to work in as visual studio code

**Describe the solution you'd like:**
I would like to be able to debug said applications in visual studio code, with all the tools it brings, using this extension (or any that can do this, really)

**Describe alternatives you've considered:**
Keep using IEChooser, due to a lack of other alternatives that I'm aware of

**Additional context:**
N/A

**Comment by captainbrosset** [comment]
Pinging @bwalderman on this issue as I think he can advise on this.
My understanding is that if the app you're debugging needs IEChooser, then that means it's running on the IE browser engine, not the Edge one. 
The newer DevTools only work with Edge unfortunately. The APIs that DevTools requires to work simply do not exist in IE, only in Edge. So I don't think what you're asking is technical feasible without a really big adaption project to map the IE APIs to the Edge ones.

**Comment by FluffyGhoster** [comment]
To my understanding of this tool (F12, IEChooser), it is Edge in legacy mode, not IE, if it helps

**Comment by bwalderman** [comment]
> My understanding is that if the app you're debugging needs IEChooser, then that means it's running on the IE browser engine, not the Edge one.

That's correct. If you are debugging an application with IEChooser, then that application is using the IE engine. This is also true if your application is running in Edge in IE Mode. IEChooser continues to be the recommended approach for debugging these apps. VSCode Edge DevTools is fundamentally incompatible with the IE engine.

**Comment by FluffyGhoster** [comment]
I understand, thank you for the insight!
