### ISSUE TITLE
Test should return the total number of replaced items

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#163]
Return should be an object with two(At least) 2 properties.
{
result,
count
}

where count is the number of replaced items, this is needed as any changes on the polyfill should guarantee that the same number of functions on the devtools code are replaced. In this case if we make changes on the polyfill so that some of the items are replaced (lets say 3/5 items get patched and 2/5 do not), this test will still pass, while it should not (5/5 should be replaced).

**Comment by bgoddar** [comment]
This system has been replaced with https://github.com/microsoft/vscode-edge-devtools/pull/449 and is no longer needed
