### ISSUE TITLE
Avoid Edge code actions on save

### ISSUE THREAD

**Issue by Suniron** [microsoft/vscode-edge-devtools#1630]
Sometimes, this extension runs code actions on save (typescript files):

![image](https://github.com/microsoft/vscode-edge-devtools/assets/36677774/0a0d19d5-c2cb-415d-bb28-28bddc945d0e)

How can I disable it? Because it takes a long time (almost 10s) to save my files with that.

This is my `.vscode/settings.json` configuration:

```
  "prettier.enable": false,
  "editor.formatOnSave": false,
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": false,
      "source.fixAll.eslint": true,
    },
  },
```

**Comment by captainbrosset** [comment]
@vidorteg what code actions does the extension run on save, do you know?
Is there a way to disable them?

**Comment by sanket-bhalerao** [comment]
is there any update on this question?

**Comment by vidorteg** [comment]
it has been some time  without reply, so I'm going to close the issue for now, but feel free to reopen it if new information comes up or you have the issue again. 👍
