### ISSUE TITLE
my < tag isnt working

### ISSUE THREAD

**Issue by Whyales247** [microsoft/vscode-edge-devtools#1643]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Whyales247** [comment]
please i need my < fixed as soon as possible

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
