### ISSUE TITLE
Can I request a feature? Thank you!

### ISSUE THREAD

**Issue by Nalini1998** [microsoft/vscode-edge-devtools#1648]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1647
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1646
```

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
