### ISSUE TITLE
Cursor Pointer Issue

### ISSUE THREAD

**Issue by FumI4096** [microsoft/vscode-edge-devtools#1656]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

I have an issue with the microsoft edge devtool visual studio, I don't know if this happen to others but a cursor pointer won't pop even though I a css property and its value "cursor: pointer"

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reporting this.

The extension streams the webpage from a headless Edge process into VS Code. So essentially, what you're seeing is a series of screenshots that are taken of the actual running webpage, being displayed in a panel in VS Code. 
So, for the cursor to change, the headless browser would need to send events for when the cursor is hovering over an element that has `cursor:pointer` (or other). The extension would then have to listen to those events and change the cursor in VS Code accordingly.

So, not impossible to do I guess. But pretty technically involved.

If you need to test something related to cursors right now, I suggest switching your setup to use an actual external browser window as described in the docs: https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/external-browser-window

@vidorteg what are your thoughts on the above? I have a feeling this could be a candidate to add to our WONTFIX list in #1317 .
