### ISSUE TITLE
https://github.com/Zws-China/WSLoginView.git

### ISSUE THREAD

**Issue by wkaahhhhhh** [microsoft/vscode-edge-devtools#1675]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by vidorteg** [comment]
Hi, please provide additional context and feel free to reopen
