### ISSUE TITLE
my javascript code is not running on my vs code 

### ISSUE THREAD

**Issue by Buzzydenez** [microsoft/vscode-edge-devtools#1677]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/187
```

**Comment by vidorteg** [comment]
Hi, please provide additional context and feel free to reopen
