### ISSUE TITLE
que tengo que hacer para que se vea la imagen

### ISSUE THREAD

**Issue by enziitoo10** [microsoft/vscode-edge-devtools#1698]
#hero{
        display: flex;
        align-items: center;
        justify-content: center;
        text-align: center;
        flex-direction: column;
        height: 90vh;
        color: white;
        background-image:linear-gradient(
         0deg,
         rgba(0,0,0,0.5)
         rgba(0,0,0,.5)   
        )
         ,url("media/porro.jpg");

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
