### ISSUE TITLE
remove the usage of environment variables and automate variable value assigment.

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#171]
With the inclusion of a npm run download-edge we have a way to know the source files path, so the variables:
EDGE_CHROMIUM_PATH
EDGE_CHROMIUM_OUT_DIR

can be set automatically, so we should discourage (and the remove) the "traditional method", we should also include a config file for overriding.

**Comment by codepo8** [comment]
Sounds good, and we should update the docs to remove the extra step. This helps making contribution easier.
