### ISSUE TITLE
Open Bing Chat in VCode

### ISSUE THREAD

**Issue by mohamedthe1** [microsoft/vscode-edge-devtools#1715]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Bing Chat isn't integrated in VSCode. However, if you're interested in using an AI assistant like Bing Chat, you might be interested in GitHub Copilot: https://code.visualstudio.com/blogs/2023/03/30/vscode-copilot

For info, though, this repository is related to the Edge DevTools extension in VS Code. It's not related to either Bing Chat or GitHub Copilot. So I'm going to close this issue.
