### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by papel61** [microsoft/vscode-edge-devtools#1743]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.

**Comment by papel61** [comment]
Grazie ho chiuso perché avevo problemi gravi e non per capriccio.


Il lun 18 set 2023, 09:16 Patrick Brosset ***@***.***> ha
scritto:
