### ISSUE TITLE
Dev Tools do not show up after port forwarding

### ISSUE THREAD

**Issue by ConteClaudioSalvatore** [microsoft/vscode-edge-devtools#1749]
**Environment (please complete the following information):**
 - OS: Windows 10 22H2 build 19045.3448
 - Extension version: 2.1.3

**Describe the bug:**

when trying to open dev tools inside vs code, and after authorizing github for the port forwarding system ecc. they don't show up, instead an empty tab is showed

**Repro steps:**

this is my configuration:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "msedge",
      "name": "some name",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
    }
  ]
}
```
(the application runs with a 'npm run start or yarn start', so the debug attaches to it)

then click 
![image](https://github.com/microsoft/vscode-edge-devtools/assets/74454087/3f0e6e16-fe50-40d4-9069-6c7b0d29f7ce)
this button 

result: 
![image](https://github.com/microsoft/vscode-edge-devtools/assets/74454087/c0a2b235-0058-40f6-a2c2-a2709e159cda)

**Expected behavior:**
when opening dev tools thy should show like they are supposed to:
![image](https://github.com/microsoft/vscode-edge-devtools/assets/74454087/52143d7a-2a6c-4350-a9c6-1f893a7263a6)

**Additional context:**

https://github.com/microsoft/vscode-edge-devtools/assets/74454087/63abf7ac-0ede-45b7-9de1-abe62c61194b

(i have also tried this on different devices and versions (vscode and vscode insiders)

**Comment by ConteClaudioSalvatore** [comment]
update: 
(this bug has been goin on for several days)
suddenly, today, after some time debugging, the extension "shut down" or at least that's the notification VSCODE thrown.
after that Dev tools popped up (on vscode insiders) i also tried opening them on vscode stable but nothing has gone the right way there...

**Comment by sumbad** [comment]
I have the same problem. The only one workaround is turned off the Local Tunnel Port Forwarding extension inside a workspace.

<img width="1594" alt="image" src="https://github.com/microsoft/vscode-edge-devtools/assets/10432330/806f0e48-150e-4e4b-a559-eb5ff236f297">

- OS: macOS 13.5.2 
- Extension version: 2.1.3

**Comment by captainbrosset** [comment]
Thanks all. Please do test again after the nightly build update and let us know if the problem goes away.

**Comment by ConteClaudioSalvatore** [comment]
I tested it right now and it seems to be going fine
