### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by caiosantoos05** [microsoft/vscode-edge-devtools#1758]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1754
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1757
```

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.

**Comment by caiosantoos05** [comment]
Em seg., 25 de set. de 2023 às 04:19, Patrick Brosset <
***@***.***> escreveu:

**Comment by caiosantoos05** [comment]
Problema bug no sistema

Em ter., 26 de set. de 2023 às 16:11, Kaio Henrique ***@***.***>
escreveu:
