### ISSUE TITLE
I request for a feature that I can access my program files anywhere or at any system where I logged in. By doing so I can work on the same project or another project which is in my other system. Thank you! 

### ISSUE THREAD

**Issue by LakshyaMaharshi** [microsoft/vscode-edge-devtools#1767]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
