### ISSUE TITLE
Thanks for the helpful extention for vscode., I want to open the chat.openai.com in my vscode use edge-devtools, but stuck in the CloudFlare verification

### ISSUE THREAD

**Issue by ali-yuze** [microsoft/vscode-edge-devtools#1776]
**Is your feature request related to a problem? Please describe.**

Thanks for the helpful extention for vscode.
**Describe the solution you'd like:**  open the website like in a normal webbrowser, and don't stuck in  the CloudFlare verify loop.

**Describe alternatives you've considered:**

**Additional context:**

![Screenshot 2023-10-05 105652](https://github.com/microsoft/vscode-edge-devtools/assets/74637003/8c9d3b45-527e-4076-bf1d-bbe0c85caa3e)

**Comment by captainbrosset** [comment]
@ali-yuze this seems like a valid bug of the embedded browser. Not sure if it's fixable, but it seems like something we should look into anyway. Why did you close the issue?
