### ISSUE TITLE
VSCode EDGE Devtools "blob problem" again

### ISSUE THREAD

**Issue by bl5ck** [microsoft/vscode-edge-devtools#1824]
https://github.com/microsoft/vscode-edge-devtools/issues/1000
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): MacOS Sonoma 14.0
 - Extension version (*e.g.,* 1.2.3): 2.1.3

**Describe the bug:**

Edge Devtools does not work but gives an error message about: BlobNotFound

**Repro steps:**

click F5 (debug) in VScode

**Expected behavior:**

**Additional context:**

![image](https://github.com/microsoft/vscode-edge-devtools/assets/23395733/75556285-d095-46cb-86d9-27c949f420db)

**Comment by captainbrosset** [comment]
Thanks for filing. Marking this as tracked for the team to take a look.

**Comment by rezio-gary** [comment]
use edge-dev version could work

**Comment by Jim876633** [comment]
have the same issue in MacOS 13.4

**Comment by vidorteg** [comment]
Should be fixed in  v2.1.5
