### ISSUE TITLE
unable to load after setting up a text proxy sever

### ISSUE THREAD

**Issue by 633MEE** [microsoft/vscode-edge-devtools#1838]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete as there isn't enough information here for us to investigate a potential issue. Please feel free to add more information if you have any and we can re-open the issue.

**Comment by 633MEE** [comment]
I'm new to GitHub and posting feeds I probably have more than one account that's how bad it is for me I reset my pc and started over from scratch because the delay in response  I couldn't reply
________________________________
