### ISSUE TITLE
The run code is not working when i write it does not do anything

### ISSUE THREAD

**Issue by Nouman12343** [microsoft/vscode-edge-devtools#1843]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
