### ISSUE TITLE
Integration with XYZ Accounting Software

### ISSUE THREAD

**Issue by keenomvictor** [microsoft/vscode-edge-devtools#1848]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**
 

[Document Markup.pdf](https://github.com/microsoft/vscode-edge-devtools/files/13449031/Document.Markup.pdf)
[extensions.json](https://github.com/microsoft/vscode-edge-devtools/files/13449032/extensions.json)

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
