### ISSUE TITLE
folders

### ISSUE THREAD

**Issue by markmungaidrezz** [microsoft/vscode-edge-devtools#1856]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by markmungaidrezz** [comment]
the visual studio app is not rea
ding my files

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
