### ISSUE TITLE
devtoolsFrontendUrl - /devtools/inspector.html?ws=localhost/devtools/page/CBF729D5264430AF720AB9B5B980707B

### ISSUE THREAD

**Issue by dvdtok** [microsoft/vscode-edge-devtools#1859]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
```

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
