### ISSUE TITLE
adding new tab 

### ISSUE THREAD

**Issue by Jepther** [microsoft/vscode-edge-devtools#1877]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Jepther** [comment]
Trying to run a php file on the instant browser
Additional Tab: Suggesting if is possible to launch instance browser with other extensions.
considering multiple tabs with extensions

**Comment by captainbrosset** [comment]
Thanks for filing. Let me ask a question to make sure I'm understand this correctly:

What do you mean by extensions? Are you looking for a way to have Edge browser extensions work also in the browser preview that's embedded in VS Code?

**Comment by captainbrosset** [comment]
Closing for lack of response to the question above.

**Comment by Jepther** [comment]
Please Sir, sorry for not responding
