### ISSUE TITLE
Edge Tools , OOM error when ssh connects to a remote resource

### ISSUE THREAD

**Issue by NirvanaCh** [microsoft/vscode-edge-devtools#1882]
Type: <b>Bug</b>

Works fine locally but crashes when remote.
Task Manager shows VS Code memory gradually growing to about 3GB then crashing.
--------------------------------------------------------------
CPUs	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg)	
Memory (System)	7.73GB (2.94GB free)
Process Argv	--crash-reporter-id 1ec25f90-4b42-4e57-a40d-3c519fe4efec
Screen Reader	no
VM	0%

Extension version: 2.1.3
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+(hide remote IP)' could not be established

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
vscrpc:30673769
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259

```

</details>

**Comment by captainbrosset** [comment]
Thanks for filing. Marking as a tracked bug so our team can prioritize and take a look.

**Comment by NirvanaCh** [comment]
> Thanks for filing. Marking as a tracked bug so our team can prioritize and take a look.

I just tried it, and the issue did not reoccur. 
This month, I upgraded version of vscode (1.85.0>1.85.2) and Edge tools (2.1.3>2.1.4), including those on the remote server. Perhaps this issue can be closed now?

**Comment by captainbrosset** [comment]
Thanks so much for coming back and updating this issue. Yes, let's close it now, and we can always re-open it (or open a new one) if the issue occurs again.
