### ISSUE TITLE
Programming Languages

### ISSUE THREAD

**Issue by mohamed2015ali** [microsoft/vscode-edge-devtools#1912]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mohamed2015ali** [comment]
Programming all things programming

**Comment by mohamed2015ali** [comment]
Programming all things programming

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
