### ISSUE TITLE
Showing "cmd is not recognised as an internal or external command" fix this error

### ISSUE THREAD

**Issue by nameishyam** [microsoft/vscode-edge-devtools#1928]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): my os is Windows 11
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
