### ISSUE TITLE
Bad Webgl Performance, error: Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels

### ISSUE THREAD

**Issue by orazdow** [microsoft/vscode-edge-devtools#1957]
**Environment**
 - OS Windows 11
 - cpu : i7-1160G7
 - ram: 16gb
  - Extension version 2.1.3
 - Vscode: Version: 1.85.1 (user setup)
 - Electron: 25.9.7

I am trying to debug a webgl application using the edge devtools browser in vscode but the performance is very bad.
Upon loading the console displays this message each frame:

```
[.WebGL-00003E1C00E38E00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels 
```
The webgl program only displays a low poly model, and disabling webgl ereatures like `gl.BLEND` or `gl.CULL_FACE` has no effect.
The console will discontinue printing the error after a few frames, but the frame rate remains very low.

**Comment by captainbrosset** [comment]
The browser preview that's embedded in VS Code with this extension is not meant for this kind of work. It works by having Edge run in a headless manner, and then by essentially streaming screenshots of the rendered page on a regular basis.
If what you're working on is rendering performance intensive, I strongly suggest to not use the embedded browser preview, but instead the real browser (which you can still connect to from the DevTools VS Code extension): https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/external-browser-window
