### ISSUE TITLE
Remote Debug: Error while fetching list of available targets No available targets to attach

### ISSUE THREAD

**Issue by rzyns** [microsoft/vscode-edge-devtools#1968]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11 Pro (22635) (VS Code UI), macOS 14.2.1 (vscode-server)
 - Extension version (*e.g.,* 1.2.3): 2.1.3

**Describe the bug:**

When I try to debug using ms-vscode-remote.remote-ssh, the browser launches on the remote (UI) machine, but I get an error notification in VS Code that says:

> Error while fetching list of available targets No available targets to attach.

The remote Edge instance shows up in the "Call Stack" pane and the VS Code UI reflects what's going on in the remote devtools if I set breakpoints there (or put `debugger` statements in the code), but it shows the context as a separate file (as if the path mappings are incorrect) and any breakpoint I set in the code shows as unregistered. Also, none of the extensions UI shows up as it does when debugging locally.

**Repro steps:**

In a remote SSH session, launch Edge with the extension and debug some code

**Expected behavior:**

**Additional context:**

The same also happens if I just hit the "Launch Instance" button in the MS Edge Tools pane

**Comment by captainbrosset** [comment]
I think this is the same as #1120 which just got fixed by #1804. The fix hasn't been released yet, but a new version of the extension should be produced early next week. 
So, I'm going to close this now, but feel free to re-open it if the problem doesn't go away with the new version.
