### ISSUE TITLE
power function bug in vs code(c++)

### ISSUE THREAD

**Issue by DIPUN-1** [microsoft/vscode-edge-devtools#1969]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):Windows 11
 - Extension version (*e.g.,* 1.2.3):2.1.3

**Describe the bug:**

when we simply calculate the power function pow(5,3) it is showing 125.but, by taking variable to those element for (5 and 3) it gives 124.
**Repro steps:**

assign 5 to x and 3 to y. then take pow (x,y) and then print it
**Expected behavior:**

it should show 125
**Additional context:**

![image](https://github.com/microsoft/vscode-edge-devtools/assets/148847985/d9e34774-109e-47cb-ac1d-593bd7f9799c)

**Comment by CONDEVIRSMARK** [comment]
![WIN_20230905_18_44_31_Pro](https://github.com/microsoft/vscode-edge-devtools/assets/126905008/58400c8f-5b3b-48fd-a4d4-8b6473c1147e)

**Comment by CONDEVIRSMARK** [comment]
RaiseFailFastException({
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "rollForward": "Major",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }{"name":"https://developer.android.com/studio/releases/platform-tools","role":"document","actions":[],"value":"","nodeCssSelector":"","nodeType":9,"description":"","keyboardShortcut":"","childCount":1,"indexInParent":0,"states":["readonly","focusable","opaque","enabled","sensitive"],"children":[{"name":null,"role":"generic","actions":[],"value":"","nodeCssSelector":"#line1","nodeType":1,"description":"","keyboardShortcut":"","childCount":7,"indexInParent":0,"states":["selectable text","opaque","enabled","sensitive"],"children":[{"name":"1","role":"statictext","actions":[],"value":"","nodeCssSelector":"#line1#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":0,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":" ","role":"statictext","actions":[],"value":"","nodeCssSelector":"#line1#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":1,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":"Encontrada etiqueta de inicio sin ver primero un doctype. Se esperaba “<!DOCTYPE html>”.","role":"generic","actions":[],"value":"","nodeCssSelector":".error","nodeType":1,"description":"","keyboardShortcut":"","childCount":3,"indexInParent":2,"states":["selectable text","opaque","enabled","sensitive"],"children":[{"name":"<","role":"text leaf","actions":[],"value":"","nodeCssSelector":".error#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":0,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":"h1","role":"text leaf","actions":[],"value":"","nodeCssSelector":".start-tag#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":1,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":">","role":"text leaf","actions":[],"value":"","nodeCssSelector":".error#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":2,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}}],"attributes":{"margin-left":"0px","text-align":"start","text-indent":"0px","margin-right":"0px","tag":"span","class":"error","margin-top":"0px","margin-bottom":"0px","display":"inline","explicit-name":"true"}},{"name":"Service Unavailable","role":"text leaf","actions":[],"value":"","nodeCssSelector":"#line1 > span:nth-child(3)#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":3,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":"</","role":"text leaf","actions":[],"value":"","nodeCssSelector":"#line1 > span:nth-child(4)#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":4,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":"h1","role":"text leaf","actions":[],"value":"","nodeCssSelector":".end-tag#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":5,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}},{"name":">","role":"text leaf","actions":[],"value":"","nodeCssSelector":"#line1 > span:nth-child(4)#text","nodeType":3,"description":"","keyboardShortcut":"","childCount":0,"indexInParent":6,"states":["opaque","enabled","sensitive"],"children":[],"attributes":{"explicit-name":"true"}}],"attributes":{"margin-left":"35.75px","text-align":"start","margin-top":"0px","text-indent":"0px","margin-right":"0px","tag":"pre","id":"line1","margin-bottom":"0px","display":"block","formatting":"block"}}],"attributes":{"margin-left":"0px","text-align":"start","margin-top":"0px","text-indent":"0px","margin-right":"0px","tag":"body","class":"wrap highlight","id":"viewsource","margin-bottom":"0px","display":"block","explicit-name":"true"}}
}void)

**Comment by CONDEVIRSMARK** [comment]
https://ingenieriareversa-my.sharepoint.com/:o:/r/personal/equipo7_ingenieriareversa_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B705768D7-F100-4DCC-99F6-0C31B4FD5943%7D&file=JUANCARLOS%20en%20NEOTRAKINGMORALITY&action=edit&mobileredirect=true&wdorigin=Sharepoint

**Comment by captainbrosset** [comment]
This issue isn't related to the Edge DevTools VSCode extension. It seems more like something related to C++ directly. Please ask again on a C++ related forum.
