### ISSUE TITLE
hint package

### ISSUE THREAD

**Issue by AruDhavali** [microsoft/vscode-edge-devtools#1988]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/1987
```

**Comment by AruDhavali** [comment]
Im not founding latest version of hint package in vscode

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
