### ISSUE TITLE
css cursor property is not being respected its always default sad :(

### ISSUE THREAD

**Issue by TomieAi** [microsoft/vscode-edge-devtools#1996]
**Is your feature request related to a problem? Please describe.**
yeah css cursor are being ignored 

**Describe the solution you'd like:**
fix the cursor.. like simple browser does it respect cursor property css

**Describe alternatives you've considered:**
i dont know xD respect the cursor please xD

**Additional context:**
no more i already laid out all the details

**Comment by TomieAi** [comment]
## this is the simple browser built in .. it respect the cursor and changing quite cool. even if u hover on input the cursor change into cursor for typing

https://github.com/microsoft/vscode-edge-devtools/assets/111332073/ffd2e00f-bd18-4dc3-8774-79e9bc1199bb

## but then again on this edge plugin.. i like edge it has dev tool xD but it doesnt respect the cursor.

https://github.com/microsoft/vscode-edge-devtools/assets/111332073/5e947752-35d0-4167-b6df-69cca3b41b65

**Comment by captainbrosset** [comment]
Thanks for reaching out. This is a request we've heard before, see [this message about it](https://github.com/microsoft/vscode-edge-devtools/issues/1656#issuecomment-1658066947):

> The extension streams the webpage from a headless Edge process into VS Code. So essentially, what you're seeing is a series of screenshots that are taken of the actual running webpage, being displayed in a panel in VS Code.
So, for the cursor to change, the headless browser would need to send events for when the cursor is hovering over an element that has cursor:pointer (or other). The extension would then have to listen to those events and change the cursor in VS Code accordingly.
So, not impossible to do I guess. But pretty technically involved.

@vidorteg this isn't the first time we've had this request. Could you please take a look at the technical feasibility. My intuition is that it's a lot of added complexity (and potentially degraded performance) for something that might not be worth it.
The problem we keep having though, is that the embedded browser preview looks too much like a real browser and people therefore expect it to behave like one.

**Comment by TomieAi** [comment]
hmm thats sad.. ok I will close this.
