### ISSUE TITLE
Can you give us the ability to open tabs on a separte monitor?

### ISSUE THREAD

**Issue by Ray-de-light** [microsoft/vscode-edge-devtools#2007]
**Is your feature request related to a problem? Please describe.**

The problem is feeling cramped on one laptop screen with multiple tabs open.

**Describe the solution you'd like:**

It would be great to be able to open windows/tabs, such as the dev tools or the preview, on another monitor. At the moment if I drag the tab onto another monitor it tells me that I can't do this yet. When I close the window, instead of it returning to the original monitor, the tab is lost. (it would be better for now that it was just reinstated to the previous state. 
**Describe alternatives you've considered:**

**Additional context:**

Nothing else.

**Comment by vidorteg** [comment]
Hi @Ray-de-light ,

You can have the preview displayed in the full browser by **removing he check** in the "Launch Microsoft Edge in Headless mode" box in the Extension settings. Then you can move this window to a different monitor

![image](https://github.com/microsoft/vscode-edge-devtools/assets/43078681/63d8445d-5b9f-4b9a-81bf-090f7408c1fc)

**Comment by Ray-de-light** [comment]
Thank you. I'll check it out!
