### ISSUE TITLE
i am not able to push my code to vscode please help me

### ISSUE THREAD

**Issue by Kajal-Abacus** [microsoft/vscode-edge-devtools#2014]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Kajal-Abacus** [comment]
i am not able to push my code to github please help me

**Comment by Kajal-Abacus** [comment]
i am not able to push my code to f=github please help me

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
