### ISSUE TITLE
Import a Component in react Does not Works Properly Path Does not Import 

### ISSUE THREAD

**Issue by Jothi123venkat** [microsoft/vscode-edge-devtools#2018]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Jothi123venkat** [comment]
import component and autoimport does not works

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
