### ISSUE TITLE
CMD|Ctrl+Shift+P offers you to access all the features of Developer Tools 

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-edge-devtools#202]
They are not enabled though. Could we limit the options shown in the command palette? It is an important accessibility feature but we don't want to offer functionality that can't be reached.

**Comment by vidorteg** [comment]
I think that this is similar to #207 , so we can potentially enable the theme options and go from there?

**Comment by mliao95** [comment]
So this is actually a regression.  CTRL + P and CTRL + SHIFT + P menus should have been disabled via this pull request: https://github.com/microsoft/vscode-edge-devtools/pull/131/files

I believe that the location of the quick open/command menu has shifted around that this patch was not being applied correctly.  Plus, the tests that we have to test this patch was too general to catch that it was being applied to the wrong place.  I have updated both the patch and the tests in this PR: https://github.com/microsoft/vscode-edge-devtools/pull/219

We should fix this regression first and then make another PR to enable the options that we want.

**Comment by mliao95** [comment]
Fixed in linked PR.
