### ISSUE TITLE
Edge DevTools in vscode isn't showing as it should

### ISSUE THREAD

**Issue by Eduardo12X** [microsoft/vscode-edge-devtools#2044]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10 (Scholar PC)
 - Extension version (*e.g.,* 1.2.3): 2.1.4

**Describe the bug:**

I updated the vscode, since the older version didn't install the extensions, after that, I install the edge tools for Microsoft, everything is working fine, except the DevTools, it's with a bizzare bug, where it wasn't identified

**Repro steps:**

The scholar PC's in my case delete everything I did when it restarts or shut down, so I recommend configure to do it and the PC shouldn't be up to date, without any manitenance, like do a "sfc /scannow", "Dism /Online /Cleanup-image /Restore-health" and "chkdsk -f -r -b" commands. And who knows have a older version of the vscode, where it didn't install extensions

**Expected behavior:**

The PC should be more or less in usage experience, and the updates can give an error, depending of how configured the PC is, and many times, scholar PC's don't let you an administrator access, consequently, can happen the extension error and other issues as I reported

**Additional context:**

![Photo_Feedback1 1](https://github.com/microsoft/vscode-edge-devtools/assets/85649279/d0413e5c-4b07-455b-9e30-6eec0ec401f0)

AB#49237566

**Comment by vidorteg** [comment]
Hi @Eduardo12X , thank you for the report. I'm putting out a fix for this issue and should be released in the next version.

**Comment by vidorteg** [comment]
This has been fixed in v2.1.5
