### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by glyndelcuesta** [microsoft/vscode-edge-devtools#2058]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by glyndelcuesta** [comment]
never run the live server

**Comment by captainbrosset** [comment]
Closing as a duplicate of #1453.
