### ISSUE TITLE
provide a gcc to my visual studio 

### ISSUE THREAD

**Issue by yuvrajtiwari1978** [microsoft/vscode-edge-devtools#2066]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by yuvrajtiwari1978** [comment]
i am not able to run code because of my gcc showing trouble

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
