### ISSUE TITLE
multiple windows everytime i click the icon of vscode, like the unsaved or closed files kept appearing

### ISSUE THREAD

**Issue by mniez** [microsoft/vscode-edge-devtools#2069]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
This feedback should be shared on the VSCode github repo instead of on this devtools extension repo: https://github.com/microsoft/vscode
Thanks for your understanding.
