### ISSUE TITLE
Switching between dark and light theme with ctrl-shift-p stopped working

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-edge-devtools#207]
Before the latest update, I was able to switch between the dark and the light theme. This does not seem to work anymore (nothing happens when switching):

![image](https://user-images.githubusercontent.com/69010225/94966909-5a698080-04fe-11eb-99b4-fb2087f19de4.png)

**Comment by vidorteg** [comment]
Sounds like we can add setting to the Devtools extension preferences to enable light/dark mode based on user preference.
