### ISSUE TITLE
Switching between tools and editor with keyboard shortcut

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-edge-devtools#208]
Is there a fast way to navigate between the Edge DevTools extension and an open document in the editor? I like to use the keyboard (arrow keys) to navigate through the DOM in the Edge DevTools. Is there a keyboard shortcut that switches between the editor and the elements panel? Or a way to get to the VS code Command Palette when using keyboard navigation inside the Elements panel? Let's say the focus is on the H1 element in the devtools:

![image](https://user-images.githubusercontent.com/69010225/94970334-bcc57f80-0504-11eb-8808-01a82b124237.png)

The way I can go from there to my index.html is: shift + tab, tab, tab, tab. ctrl + page down. It would be nice if there is a faster way.

**Comment by codepo8** [comment]
Thank you, this is an excellent idea, we'll take a look what keyboard shortcuts are still available.

**Comment by mliao95** [comment]
Hi billie-spektor,  I checked in a change that will allow the `CTRL + PageDown` and `CTRL+PageUp`  command (cycle next/previous tab) to work within the DevTools.  It is a more complicated of a fix to create a shortcut that will focus a specific element in the DevTools, so I wanted to check in with you to see if this is a sufficient enough solution to your workflow.

**Comment by billie-spektor** [comment]
Thanks for looking into this! Your solution is very helpful for getting back to the editor from the DevTools. One thing I noticed is that CTRL + PageDown and Ctrl + PageUp does not necessarily take you back to the correct / expected tab. Steps to reproduce:

1. Have 3 tabs open
2. Activate the second tab
3. Move the focus to the DevTools with Ctrl + PageDown
4. Move the focus to an element in DevTools with TAB (4 times)
5. Move the focus back to the editor group with Ctrl + PageUp

Expected result: focus moves to the second tab
Actual result: focus moves to the third tab

**Comment by mliao95** [comment]
For clarification, is your repro set up look like this with the three tabs on the left side and the DevTools on the right?
![image](https://user-images.githubusercontent.com/14304598/101836259-e812af00-3af1-11eb-9ef8-ad3248a0eea6.png)

If this is the case, I believe it is working as expected since it will cycle through the tabs left to right with no regard to which tab is active in an editor group.  Pressing `Ctrl + PageUp` on the DevTools window would shift one tab to the left which would be the third tab.

Maybe the shortcut you are looking for is `Ctrl + K Ctrl + ArrowLeft/Right` which shifts focus between the left/right editor group.  Let me know if this answers your question or if this is the shortcut you were looking for and I'd be more than happy to implement it into the extension.

**Comment by billie-spektor** [comment]
Sorry about that, I totally forgot that I remapped those keys:

```
    {
        "key": "ctrl+pagedown",
        "command": "workbench.action.focusNextGroup"
    },
    {
        "key": "ctrl+pageup",
        "command": "workbench.action.focusPreviousGroup"
    }
```

Would be great if these two commands can be made available in the DevTools!

**Comment by mliao95** [comment]
Unfortunately, any custom mappings will be lost when within the DevTools extension.  The extension itself runs inside an iframe inside a webview which is known to trap keyboard events from propagating out of the extension.  Investigating this structural issue is in our backlog, but for now, we currently work around this by statically implementing these shortcuts.

I'll look into adding the `focusNextGroup` and `focusPreviousGroup` shortcuts within the next couple releases and update this thread with the progress.

**Comment by mliao95** [comment]
Checked in a change for `focusNextGroup` and `focusPreviousGroup` with `Ctrl + K Ctrl + ArrowLeft/Right`.  Let me know if this works for you.

**Comment by billie-spektor** [comment]
Nice! Thanks for implementing this.
