### ISSUE TITLE
Feature request: activate element picker when using ctrl+shift+c shortcut within Edge

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-edge-devtools#209]
I often toggle the element picker with ctrl+shift+c from within Edge. It would be really cool if it's somehow possible to activate the element picker in the VS code extension (as a result of using the keyboard shortcut inside Edge), instead of opening a second developer tools panel:

![image](https://user-images.githubusercontent.com/69010225/94971171-9accfc80-0506-11eb-8ee0-dfaf4e0f4146.png)

This would be a bit faster than first moving the mouse to VS code, activating the element picker there, and then moving the mouse back to the browser.

**Comment by codepo8** [comment]
Hello there, 
sadly enough we looked into this and this is a much larget issue than we considered before. As we are inside VS Code and not the browser, a lot of keyboard shortcuts clash with what's already used and some don't get sent to extensions. For now, we don't have a fix for this, so all you can do is use the mouse to select the element or pick it from the elements tree with the arrow keys.

**Comment by billie-spektor** [comment]
Alright, I can imagine the challenges. Thanks for looking into it!
