### ISSUE TITLE
Feature request: expose the currently selected element as $0

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-edge-devtools#210]
With the latest release, I don't see a way anymore to inspect the properties of the JS object that corresponds with the currently selected element in the elements panel. In a previous version of the extension, it was possible to check this information under properties. This panel is still available, but deprecated:

![image](https://user-images.githubusercontent.com/69010225/94986936-fdec7c80-0562-11eb-9510-953a88ccc894.png)

Is there a way to expose the currently selected element as $0, so that the JS properties can easily be inspected? I guess that would either be in a console panel / console drawer, or directly in VS code in the debug console.

**Comment by codepo8** [comment]
Hi there, 
this also happened in the developer tools in the browser and there is no way we can deviate from that. However, there are quite a few discussions on the Chromium bug list about this, so there is a chance that this will get reverted back to the old behaviour.
