### ISSUE TITLE
The Developer Tools Sometimes Fail to Load

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode-edge-devtools#2148]
**Environment (please complete the following information):**
 - OS Windows 10 Pro 22H2:
 - Extension version 2.1.5:

**Describe the bug:**
 The extension's developer tools sometimes fail to load
 
 
![Captura de pantalla (9)](https://github.com/microsoft/vscode-edge-devtools/assets/51484063/7abe7b4a-767b-46c2-a11f-5fc453f5726e)

**Repro steps:**
Open VSCode with a slow internet connection an open Edge Tools

**Expected behavior:**
It should load the developer options correctly always

**Additional context:**
The loading failure might be caused by an attempt to update, and if the internet connection is poor or nonexistent, that could be the source of the problem. 

AB#50580077

**Comment by captainbrosset** [comment]
Thanks for reporting this. Making sure this shows up on our team's backlog.

**Comment by vidorteg** [comment]
should be fixed by:
https://github.com/microsoft/vscode-edge-devtools/pull/2431
