### ISSUE TITLE
Please add support for cursor: pointer

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode-edge-devtools#2149]
Thank you for this incredible tool, it's very good. However, it doesn't display the hand cursor when a button or div in CSS has the property cursor: pointer. I hope this gets fixed soon, and if there isn't 100% compatibility with CSS or JS yet, I hope you add it so that it's fully functional, thanks

**Comment by captainbrosset** [comment]
Thanks for reaching out. This is a known limitation of our browser preview. What you see in VS Code is only a stream of what the browser renders. So it's expected that some things would not be supported, and `cursor:pointer` is one of them.

Please see https://github.com/MicrosoftDocs/edge-developer/issues/3075 for this particular problem, and other limitations.
Closing this one as a duplicate. Thanks again.
