### ISSUE TITLE
why my c++ code is not run in VS code

### ISSUE THREAD

**Issue by ankitgujre01** [microsoft/vscode-edge-devtools#2191]
*  Executing task in folder D:: C:/Windows/System32/cmd.exe /d /c g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference --std=gnu++14 -g3 -O0 -ID:\/** -IC:/MinGW/include/c++/3.4.5/backward -c 'employee management.cpp' -o '.build\Debug\employeemanagement.o' && g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference --std=gnu++14 -g3 -O0 -ID:\/** -IC:/MinGW/include/c++/3.4.5/backward   .build\Debug\employeemanagement.o -o .build\Debug\outDebug.exe 

g++: error: 'employee: No such file or directory
g++: error: management.cpp': No such file or directory
g++: fatal error: no input files
compilation terminated.

 *  The terminal process "C:\Windows\System32\cmd.exe '/d', '/c', 'g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference --std=gnu++14 -g3 -O0 -ID:\/** -IC:/MinGW/include/c++/3.4.5/backward -c 'employee management.cpp' -o '.build\Debug\employeemanagement.o' && g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference --std=gnu++14 -g3 -O0 -ID:\/** -IC:/MinGW/include/c++/3.4.5/backward   .build\Debug\employeemanagement.o -o .build\Debug\outDebug.exe'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by captainbrosset** [comment]
Sorry you're facing this issue, but this seems unrelated to the VS Code Edge DevTools extension. So closing the issue.
