### ISSUE TITLE
Right click launch edge from taskbar not loading default user profile

### ISSUE THREAD

**Issue by nicholaswong31415** [microsoft/vscode-edge-devtools#2224]
**Environment (please complete the following information):**
 - OS: Windows 11
 - Extension version: 2.1.5

**Describe the bug:**

After installing the extension and successfully executing the "Launch Edge and attach DevTools" launch configuration generated by the extension in my project, opening Microsoft Edge via right-clicking on the taskbar icon and selecting "New window" or "New inPrivate window" opens the browser profile created by the extension, instead of my default user browser profile.

**Repro steps:**
- Open any folder inside Visual Studio Code (can even be an empty folder)
- Go to the Microsoft Edge Tools tab and click "Generate launch.json"
- Go to the run and debug tab and run the "Launch Edge and attach DevTools" configuration (i.e. not the headless version, so that it opens up the actual Microsoft Edge browser)
- Exit out of the debug task and close Visual Studio Code
- If Microsoft Edge is pinned to the taskbar, right click the taskbar Microsoft Edge icon and select "New window" to open a new Edge browser instance
  - If you don't have it pinned to the taskbar, searching for edge in the windows menu and selecting the "New window" option from there also works

![Screenshot 2024-06-12 012219](https://github.com/microsoft/vscode-edge-devtools/assets/42924212/057f0e1a-31f2-473d-827a-691af8fb55c3)
![Screenshot 2024-06-12 012356](https://github.com/microsoft/vscode-edge-devtools/assets/42924212/e6dc80fa-2f58-457d-875d-4619c870f646)

**Expected behavior:**
The default user profile that is normally used when opening Microsoft Edge should be loaded.

**Additional context:**
To get my user profile path I enter "edge://version/" into the search url of Microsoft Edge, and for my default profile the path is something like "C:\Users\foo\AppData\Local\Microsoft\Edge\User Data\Default"

However when I launch the browser via the method I described above, the profile path shown in the "edge://version/" page is instead something like "c:\Users\foo\AppData\Roaming\Code\User\workspaceStorage\dd5084dfa1c8ebf459345d31c6af6a03\ms-vscode.js-debug\.profile\Profile 1"

This behaviour persists upon restarting as well, I have tried the following things with no luck:
- Repairing/reinstalling Microsoft Edge
- Uninstalling Visual Studio Code entirely 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

AB#51737617

**Comment by captainbrosset** [comment]
Thank you for reaching out and providing these details. Let me make sure this is seen and prioritized by our team.

**Comment by captainbrosset** [comment]
Our dev team tried the reproduce the steps but things worked as expected. We were not able to repro the issue you are experiencing.

It might be that you've used a browser session that VSCode had opened for web browsing and you might have unadvertedly updated your shortcut.

If there is a bug somewhere in there, it would need to be tracked under [the main VS Code repository](https://github.com/microsoft/vscode) as we rely on the mechanism they provide to launch Edge.

So, I'm closing this issue for now.

**Comment by nicholaswong31415** [comment]
Ok thanks for the update!
