### ISSUE TITLE
Allow for drag and drop of files

### ISSUE THREAD

**Issue by skeough** [microsoft/vscode-edge-devtools#2231]
One of the things I was trying to implement was a drag and drop feature in my code, but I had to open an actual browser to test it, as vscode itself kept trying to open it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Sorry about the inconvenience. The embedded browser preview in VSCode doesn't support all of the advanced interactions that a true browser window does. It's just a preview of the browser rendering, not the actual browser (as noted [here](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/external-browser-window#limitations-of-the-embedded-devtools-browser)). Drag and drop is one of the things that's not supported. We don't, at this point, have a planned fix for this.
