### ISSUE TITLE
Fix path mapping for Linux machines

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode-edge-devtools#224]
Linux machines cannot find Microsoft Edge executable.  Fix path mapping to account for Linux directories.

**Comment by tayambamwanza** [comment]
> Linux machines cannot find Microsoft Edge executable. Fix path mapping to account for Linux directories.

Any work around for the time being?

**Comment by mliao95** [comment]
Unfortunately not at the moment, but we are investigating the issue now.  This does bring to light that it would be nice to have a custom path input for the browser executable to avoid situations like this.  Apologies for the inconvenience.

**Comment by vidorteg** [comment]
> > Linux machines cannot find Microsoft Edge executable. Fix path mapping to account for Linux directories.
> 
> Any work around for the time being?

Thanks for using the extension, V1.1.1 has been published and it adds support for Dev Version of Microsoft Edge in Linux.

**Comment by tayambamwanza** [comment]
> > > Linux machines cannot find Microsoft Edge executable. Fix path mapping to account for Linux directories.
> > 
> > 
> > Any work around for the time being?
> 
> Thanks for using the extension, V1.1.1 has been published and it adds support for Dev Channel of Microsoft Edge in Linux.

Sorted! :smile:
