### ISSUE TITLE
PROJECTS

### ISSUE THREAD

**Issue by NavyaChowdary2003** [microsoft/vscode-edge-devtools#2261]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
