### ISSUE TITLE
issue in Method

### ISSUE THREAD

**Issue by SURAJ-TS** [microsoft/vscode-edge-devtools#2264]
Math. random is not working in JS.

**Environment (please complete the following information):**
 - OS Windows 11
 - Extension version 1.90.2

**Describe the bug:**

the method "Math.random()" is displaying the output properly.
![Screenshot 2024-06-28 155709](https://github.com/microsoft/vscode-edge-devtools/assets/174106956/867cbf7e-5d67-4758-ae91-8eba6f394ff7)

**Repro steps:**

**Expected behavior:**

**Additional context:**

![image](https://github.com/microsoft/vscode-edge-devtools/assets/174106956/24de1170-2beb-4686-91e1-05a59c9bb059)

OUTPUT OF THIS PROGRAM IS
![Screenshot 2024-06-28 155930](https://github.com/microsoft/vscode-edge-devtools/assets/174106956/64ee4bc6-fac0-46eb-93d5-91a45a29b29c)

```

**Comment by captainbrosset** [comment]
I will have to close this bug as it is unrelated to the VSCode Edge DevTools extension codebase.
Your first screenshot shows a syntax error however. You might want to remove the `: Number` part.
