### ISSUE TITLE
Bracket closing

### ISSUE THREAD

**Issue by Hekmat-akrami** [microsoft/vscode-edge-devtools#2267]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

I disabled auto closing bracket, but it still close brackets automatically.

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for your feedback, however this appears to be about VSCode, not about our VSCode DevTools extension.
I suggest re-opening an issue on the VSCode repo here: https://github.com/microsoft/vscode.
