### ISSUE TITLE
Error On Headless Instance: WebGL2 is required but not supported.

### ISSUE THREAD

**Issue by arbonaa** [microsoft/vscode-edge-devtools#2269]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): MacOS Sonoma Version 14.5 (23F79)
 - Extension version (*e.g.,* 1.2.3):  2.1.5

**Describe the bug:**

When running a project that uses WebGL2, the headless instance (the non headless works) fails with the error: 
"WebGL2 is required but not supported."

**Repro steps:**

Create a React Project and use a library that required WebGL2, for example I am using ArcGIS API for Javascript.

**Expected behavior:**

The webpage should load the component using WebGL2

**Additional context:**

AB#52139019

**Comment by captainbrosset** [comment]
Thanks for filing this. I'll mark this as tracked so that it's part of our dev team backlog. I don't know if this will be easy to technically fix however.

**Comment by vidorteg** [comment]
As mentioned this has technical limitations for the embeded version (screencast) but should work fine for the full browser (non headless). Should be partially fixed by:

https://github.com/microsoft/vscode-edge-devtools/pull/2432
