### ISSUE TITLE
Collapsible Headless Mode

### ISSUE THREAD

**Issue by tayambamwanza** [microsoft/vscode-edge-devtools#227]
When you run the extension mode in headless mode it works as expected but takes a lot of space, it would help if you could collapse (show/hide) the page/tab, in the same way that you can expand and retract the intergrated terminal window.

**Comment by vidorteg** [comment]
Hi @tayambamwanza, 
You can use the "toggle screencast" button for this behavior. It is located next to the "Elements" tab.
https://imgur.com/a/y9DcsQq

**Comment by tayambamwanza** [comment]
> Hi @tayambamwanza,
> You can use the "toggle screencast" button for this behavior. It is located next to the "Elements" tab.
> https://imgur.com/a/y9DcsQq

Thanks, that solves it partially but what I'm looking for is like how you can toggle the sidebar open/closed, with the screencast it hides the browser window, but the elements and network tab remain open still taking up half the space, I would basically like to reclaim almost all that space when toggling that window.

I've worked around it by merging it with my other tabs, so I just switch between them but maybe this issue should stay open for anyone who wants the side by side, and toggle the whole tool open/closed.

**Comment by codepo8** [comment]
Thanks for finding a way to fix that in the interim. We'll look into that when we get to our next enhancements

**Comment by codepo8** [comment]
We investigated the possibility, but this is a functionality that is not available in the webview, so there is nothing we can do to make that happen.
