### ISSUE TITLE
Add support to vscode.dev for remote tunnels

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode-edge-devtools#2295]
**Is your feature request related to a problem? Please describe.**

I like to use this extension on my local, but is very frustating when want to use it in my remote tunnel in vscode.dev

**Describe the solution you'd like:**

Add support to vscode.dev for remote tunnels to use the extension.

**Describe alternatives you've considered:**

Does not exist.

**Additional context:**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This enhancement is already tracked in #989. So I'm closing this one as a duplicate.
