### ISSUE TITLE
Add inspect element and related shortcuts to vscode

### ISSUE THREAD

**Issue by jalissia** [microsoft/vscode-edge-devtools#23]
From #22 
"I assume the devtools shortcuts don't work when they aren't focused, so you couldn't hit ctrl+shift+c while you're in the editor to inspect an element. Should we expose that and whatever other actions are relevant to Elements here so that vs code can define/handle shortcuts for them?"

We could add the ability to use the devtools shortcuts from the rest of vscode.

**Comment by paulgildea** [comment]
The interesting thing here is do folks want to use DevTool shortcuts or press Ctrl+Shift+P and type "Insp..." (Inspect Element) instead.

**Comment by codepo8** [comment]
Duplicate of a newer issue
