### ISSUE TITLE
How can I install extensions on the VS Code Edge Devtools browser version? 

### ISSUE THREAD

**Issue by lopugit** [microsoft/vscode-edge-devtools#2323]
When I try to install any extension I just get this error :O 

![Screenshot 2024-08-02 at 10 58 07 AM - Microsoft Edge - Microsoft Edge Add-ons](https://github.com/user-attachments/assets/3a010677-84d6-4b24-990b-4cbe009ab0a7)

Extensions work fine on my normal edge browser :'( 

But I can't attach the devtools to my standard edge browser :( 

AB#53153306

**Comment by captainbrosset** [comment]
Thanks for filing.
I know installing extensions that extend the devtools UI is not possible at the moment, see #1039.
However, I believe installing extensions that extend the browser UI should work. By the looks of it, you are using an external browser window, not the embedded browser preview in VS Code, so I don't see why installing extensions there should not work.

I'll mark this as tracked on our backlog for investigation.

**Comment by vidorteg** [comment]
Hi everyone 

Thanks for the feedback seems that most of it is already answered. For running on the vscode.dev version please see:
https://github.com/microsoft/vscode-edge-devtools/issues/2367
