### ISSUE TITLE
Ensure `node` and `npm` are installed ... Node is installed to WSL

### ISSUE THREAD

**Issue by givihuda** [microsoft/vscode-edge-devtools#2348]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11
 - Extension version (*e.g.,* 1.2.3): 2.1.5

**Describe the bug:**

The notification "Ensure `node` and `npm` are installed to enable automatically reporting issues in source files pertaining to accessibility, compatibility, security, and more." pops up at the bottom right when I open VS Code, after installing VSCode Essentials
v1.0.5. 

Node was already installed to WSL Ubuntu through Microsoft's instructions for both:
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl

I just went right down the list up through Step 9 of "Install nvm, node.js, and npm", and installed nvm first then node LTS and the latest default. I didn't go past that. All of that worked fine. 👏

It seems that the extension however isn't understanding where Node is, probably because it's looking for a normal Windows 11 install that Node's download MSI does, like from https://nodejs.org/dist/v20.16.0/node-v20.16.0-x64.msi.

Anyway, I'm not seeing where to tell the extension to look for Node, or if it can even see it in WSL.

**Repro steps:**

See the steps I went through in the "Describe" part.

**Expected behavior:**

Um, find Node automatically, or let me tell it where to find it, or make it easy to notice. When I click the gear icon from the notification, then Manage Extension, then click its gear icon then Extension Settings, I don't see anything about telling it where to find the Node install.

Note that I'll probably need to use multiple versions of Node on this computer, though I think I wouldn't manage a reference to the version of Node in the extension... I'm not sure, I'm a bit confused on this point.

**Additional context:**

I'm doing through the recommendations of a video tutorial.

AB#53153443

**Comment by captainbrosset** [comment]
Thank you for filing.

@vidorteg do you think this is similar to #1145 or is this a new problem, related to WSL?

**Comment by KaranocaVe** [comment]
This is definitely a bug. On a computer that has just had Windows reinstalled, I first used 'winget install OpenJS.NodeJS' to install NodeJS, and then installed this plugin, which resulted in this error.

**Comment by givihuda** [comment]
Please let me know a fix or workaround. I'm not seeing how to tell the extension where Node is installed.

**Comment by vidorteg** [comment]
Potentially fixed at the same time as #2390 feel free to reactivate if not.
