### ISSUE TITLE
Start multiple simulated device instances at a time

### ISSUE THREAD

**Issue by Gsonovb** [microsoft/vscode-edge-devtools#236]
*This is a great plugin!*

I'm making websites for others,
I need to observe what the website looks like on different devices (screens),

Now, I start an instance through the plug-in, and manually open two tags to set the simulation size (one mobile phone, one tablet).

Can add a startup option to start multiple (desktop, tablet, mobile) windows at the same time ?

**Comment by codepo8** [comment]
Hello there,
right now each instance is a single tab. You could open more than one instance but then you need to jump from one to the other, which isn't the most convenient way. 

Thank you for your idea, we'll take a look and see what we could do to help with this issue.
