### ISSUE TITLE
Unable to download DevTools for the current target - on vscode.dev

### ISSUE THREAD

**Issue by lethuyet** [microsoft/vscode-edge-devtools#2367]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): iPadOS
 - Extension version (*e.g.,* 1.2.3): 2.1.5 (customized from ‘ui’ to ‘workspace’ extension kind -  to be installed in vscode web) 

**Describe the bug:**

After being customized (by changing extension kind from ‘ui’ to ‘workspace’) and installed successfully (via vsix file) in vscode.dev, the browser pane is working correctly (with whatever webpages loaded correctly), but the DevTools pane isn’t working and showing “Unable to download DevTools for the current target”.

**Repro steps:**

- Customize the extension by changing extension kind from ‘ui’ to ‘workspace’.
- Install the extension via vsix file in vscode.dev
- load whatever webpages successfully (e.g microsoft.com) in the browser pane
- the DevTools pane isn’t working and showing “Unable to download DevTools for the current target”

**Expected behavior:**

- the DevTools pane should work

**Additional context:**

Vscode.dev editor accessing the vscode server (on remote macos machine) via Remote Tunnel Access.
On the remote macos machine:
- VSCode with Remote Tunnel Access is On
- Edge browser: Version 127.0.2651.105 (Official build) (x86_64)

AB#53333284

**Comment by captainbrosset** [comment]
Thank you for filing this issue.

**Comment by vidorteg** [comment]
Hi @lethuyet,

Thank you for the feedback, this does not seems a bug but a feature request as by design the extension is designed to be run only locally (at least for now), this is an interesting request and I'll leave it open as a feature request in case anyones wants to take over it. Thanks for using the extension.

**Comment by lethuyet** [comment]
thanks for looking into this @vidorteg

**Comment by lethuyet** [comment]
Hi @vidorteg 
I can see you have closed this as completed.
Does that mean we're now able to install and use Edge DevTools whether in vscode.dev or a browser-based vscode client which is served by a vscode server?
Could you share/reference to details?
Thank you!
