### ISSUE TITLE
Show browser's console.log in vscode debug console [Feature Request]

### ISSUE THREAD

**Issue by erikdemarco** [microsoft/vscode-edge-devtools#2384]
**Is your feature request related to a problem? Please describe.**
When you need to see console log in the browser you need to open another window, so each of my workarea view will be so little: Column 1: file explorer
Column 2:code editor
Column 3:browser view
Column 4: browser devtools

**Describe the solution you'd like:**
It will be great if the browser devtools console will be passed to vscode "debug console".

**Describe alternatives you've considered:**

**Additional context:**

AB#53513292

**Comment by captainbrosset** [comment]
Thank you for your request.
I'll add this to our backlog for review and prioritization.

**Comment by vidorteg** [comment]
We already had this behavior in the past but it was resulting confusing for some users so we decided to remove it in favor of the recentrly introduce `jsdebug` console, thanks you for using the extension.

https://github.com/microsoft/vscode-edge-devtools/pull/411
