### ISSUE TITLE
When i open  file with "open with edge"->"open browser" it opens the page but also opens a white screen i have to click out and in the window icon for t to go in the back, but it still there. 

### ISSUE THREAD

**Issue by Ang3Lhiem** [microsoft/vscode-edge-devtools#2444]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by vidorteg** [comment]
closing as dupplicate of #2445
