### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by irsadas** [microsoft/vscode-edge-devtools#2448]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] #2443
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2446
- [ ] array in c in visual stu
```

**Comment by vidorteg** [comment]
Hi, 
Please add more information and feel free to reopen.
