### ISSUE TITLE
always great to learn by creating mistake. 😂 

### ISSUE THREAD

**Issue by KislapCollections** [microsoft/vscode-edge-devtools#2453]
**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-edge-devtools/issues/2452
```

**Comment by vidorteg** [comment]
Hi and thank you for using the extension, 
Could you provide more information in the expected format and reopen? thanks

**Comment by KislapCollections** [comment]
VS Code version: Code 1.93.1 ([38c31bc](https://github.com/microsoft/vscode/commit/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40), 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.8.0-1014-azure
Remote OS version: Linux x64 6.8.0-1014-azure

extension 12



sorry. i was looking for your email i cloud not find it.


tell me if i missed up

info@kislapcollections.com
