### ISSUE TITLE
Ilyas

### ISSUE THREAD

**Issue by Abdramany** [microsoft/vscode-edge-devtools#2454]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Abdramany** [comment]
![WhatsApp Image ali](https://github.com/user-attachments/assets/e64215da-c749-4c7d-86d8-d62276b7be3d)

**Comment by Abdramany** [comment]
ali

**Comment by vidorteg** [comment]
Hi and thank you for using the extension, 
Could you provide more information in the expected format and reopen? thanks
