### ISSUE TITLE
Edge DevTools stops working freezes on "The tab is inactive"

### ISSUE THREAD

**Issue by IgorGanapolsky** [microsoft/vscode-edge-devtools#2456]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): MacOS Sequoia 15.0
 - Extension version (*e.g.,* 1.2.3): 2.1.6

**Describe the bug:**
I installed the plugin in VSCode.  It was behaving properly for a few webpages, letting me browser through different sites in the DevTools browser.  Then it froze and stopped working.  
<img width="1728" alt="Screenshot 2024-09-29 at 6 08 44 PM" src="https://github.com/user-attachments/assets/f907c7ef-c356-42bf-b423-b33be352ed6a">

**Repro steps:**
Launch DevTools browser for the first time right after installing the plugin.  Go to the default webpage it gives - AI Skills challenge.  Go through a couple of pages, clicking on forms.  Observer that the browser freezes and cannot interact with it.

**Expected behavior:**
Should be able to navigate through as many pages in the browser I want.

**Additional context:**

**Comment by vidorteg** [comment]
Hi, 
As mentioned on the banner in the preview window. The preview window is intended for previewing changes in the UI of your app/site. It does not support advanced capabilities like webgl or authentication. For this you can use the full browser by  going into the extension settings and unchecking "Launch in headless" that way you will have a full browser and still continue to use the extension. Please feel free to reopen if this did not fixed your issue.
