### ISSUE TITLE
won't let me close instance. just stays there until I restart my pc

### ISSUE THREAD

**Issue by dimitri84-git** [microsoft/vscode-edge-devtools#2457]
**Environment**
 - OS: Windows 11
 - Extension version 2.1.6
 - 
**Describe the bug:**
when I go into the sidebar in vs code, click on the edge icon, and try to close out an instance. it won't let me.

**Repro steps:**
1. open the sidebar
2. click the edge icon
3. open an instance of edge
4. in the sidebar click the X icon on an item in the instance list.

if this is just me, sorry

**Expected behavior:**
I expected it to simply close. but it didn't

**Additional context:**

**Comment by vidorteg** [comment]
Hi I have seen this happening from time to time, it is usually associated with another tab or window keeping the process open. If this is the case please:
- Close all Edge instances
- Open Windows Task Manager and validate that there are no Edge instances running.
- Once you validated this, click on refresh on the Edge Devtools for VsCode extension and they should dissapear.

Thank you for reporting this issue and feel free to reopen if this does not work.
