### ISSUE TITLE
>skills hability<( time =stop- meanwhile-- training)( control velocity)///(  range- movement)>improve<=done

### ISSUE THREAD

**Issue by TecnoSpacialAstro999** [microsoft/vscode-edge-devtools#2458]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by TecnoSpacialAstro999** [comment]
just invest features in my extensions{arms-legg-flexibility-when ill be ready to champaign profesional only me name will be there the way its so simple╝)

**Comment by vidorteg** [comment]
Hi and thank you for using the extension, 
Could you provide more information in the expected format and reopen? thanks
