### ISSUE TITLE
toda vez que tento iniciar a deputação aparece uma mensagem de erro para criar um arquivo json mas quando eu crio só consigo deputar um arquivo da pasta e os outros não 

### ISSUE THREAD

**Issue by SuzartEduarda** [microsoft/vscode-edge-devtools#2459]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by SuzartEduarda** [comment]
![image](https://github.com/user-attachments/assets/e45e6b07-617c-4c4e-8829-ff48001918ec)

**Comment by vidorteg** [comment]
Hi and thank you for using the extension, 
Could you provide more information in the expected format and reopen? thanks
