### ISSUE TITLE
chat gtp

### ISSUE THREAD

**Issue by kempdogg** [microsoft/vscode-edge-devtools#2469]
**Is your feature request related to a problem? Please describe.**
I just wish this whole thing would have chat gtp running inside of vs code, it would make alot of people days easier

**Describe the solution you'd like:**
Implementation of openai.com in a box that you can right click and all of your problems should be solved. 

**Describe alternatives you've considered:**
Really any good code chat bot should suffice i just like openai

**Additional context:**
no

**Comment by vidorteg** [comment]
Hi, This seems to be intended for the vscode team, so please report it on their github repo, thanks
https://github.com/microsoft/vscode
