### ISSUE TITLE
JavaScript not working and page not running

### ISSUE THREAD

**Issue by CYB33** [microsoft/vscode-edge-devtools#2499]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**
 So my Javascript isn't working, and when I try to run it the problems in the terminal say there's nothing wrong, AI says that there's nothing wrong, and I don't know whether it's because of my own computer. I  don't know if I have any reasons to be suspicious of my own computer but I do know that my page isn't running anymore and my JavaScript is not running as well. Any tips?

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by vidorteg** [comment]
Hi @CYB33,

Could you please provide more details on the issue you are facing?

- Extension version, OS version and some repro steps?
- Are you having issues with headless or non-headless mode?
- Is this report for Edge browser or for the Edge Devtools VSCode extension?

Feel free to reopen once more details are added.
