### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by ANYANTUNK04** [microsoft/vscode-edge-devtools#2503]
I made a complaint about html. When I create a website, it can't be read by this system, it's ridiculous even though the original file is very complete and it's in the right folder to access this web page

**Comment by ANYANTUNK04** [comment]
I made a complaint about html. When I create a website, it can't be read by this system, it's ridiculous even though the original file is very complete and it's in the right folder to access this web page

**Comment by vidorteg** [comment]
Could you please provide more details on the issue you are facing?

- Extension version, OS version and some repro steps?
- Are you having issues with headless or non-headless mode?
- Is this report for Edge browser or for the Edge Devtools VSCode extension?

Feel free to reopen once more details are added.
