### ISSUE TITLE
Wed

### ISSUE THREAD

**Issue by Phanhnbb** [microsoft/vscode-edge-devtools#2508]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../css/home.css">
    <link aria-relevant="additions text" rel="author" href="https://github.com/Phanhnbb">
    <title>Admin Page</title> @ @ #2506 @Duplicate of #2503

**Comment by vidorteg** [comment]
Closing due to missing details, feel free to reopen once more information has been added.
