### ISSUE TITLE
wed maywed

### ISSUE THREAD

**Issue by Phanhnbb** [microsoft/vscode-edge-devtools#2509]
> [New Text Document.txt](https://github.com/user-attachments/files/17450041/New.Text.Document.txt)
> ![Image](https://github.com/user-attachments/assets/f3c249de-8905-4130-b16f-3bd95f39b747)
>  

 _Originally posted by @Phanhnbb in [#2507](https://github.com/microsoft/vscode-edge-devtools/issues/2507#issuecomment-2424866264)_

**Comment by vidorteg** [comment]
Closing due to missing details, feel free to reopen once more information has been added.
