### ISSUE TITLE
snack game

### ISSUE THREAD

**Issue by Moaz0155** [microsoft/vscode-edge-devtools#2512]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Moaz0155** [comment]
i

**Comment by Moaz0155** [comment]
u

**Comment by Moaz0155** [comment]
j

**Comment by vidorteg** [comment]
Closing due to missing details, feel free to reopen once more information has been added.
