### ISSUE TITLE
report

### ISSUE THREAD

**Issue by Phanhnbb** [microsoft/vscode-edge-devtools#2517]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

[New.zip](https://github.com/user-attachments/files/17485618/New.zip)

**Comment by vidorteg** [comment]
Closing due to missing details, feel free to reopen once more information has been added.
