### ISSUE TITLE
NOBI WEBSITE

### ISSUE THREAD

**Issue by NOBITA-PRIVETE-ACCOUNT** [microsoft/vscode-edge-devtools#2558]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by NOBITA-PRIVETE-ACCOUNT** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NOBITA HACKER</title>
    <link rel="stylesheet" href="assets/css/styles.css">
    <script src="assets/js/cart.js" defer></script> 
</head>
<body>

    
    <header>
        <div class="NOBITA HACKER">
            <img src="https://envs.sh/_GX.png" alt="Logo">
        </div>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#categories">Categories</a></li>
                <li><a href="#products">Shop</a></li>
                <li><a href="#about">About Us</a></li>
                <li><a href="#contact">Contact Us</a></li>
                <li><a href="#cart">Cart (<span id="cart-count">0</span>)</a></li>
            </ul>
        </nav>
    </header>

    
    <section id="products" style="background-color: #e0ffe0;">
        <h2>Featured Products</h2>
        <div class="product-list">

            
            <div class="product-card">
                <img src="assets/images/rdp-meaning-bg.jpg" alt="RDP Product">
                <h3>
                    <img src="https://envs.sh/_zD.png" alt="RDP Icon" style="width: 24px; height: 24px; vertical-align: middle;">
                    RDP (Remote Desktop Protocol)
                </h3>
                <p>High-performance Remote Desktop Protocol (RDP) services, perfect for businesses and personal use.</p>
                
                
                <div>
                    <p>
                        <img src="https://envs.sh/_zD.png" alt="RDP Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        1 Month - ₹120.00
                    </p>
                    <button onclick="addToCart('RDP 1 Month', 120)">Add to Cart</button>
                </div>
                <div>
                    <p>
                        <img src="https://envs.sh/_zD.png" alt="RDP Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        3 Months - ₹300.00
                    </p>
                    <button onclick="addToCart('RDP 3 Months', 300)">Add to Cart</button>
                </div>
            </div>

            
            <div class="product-card">
                <img src="assets/images/heroku-product.jpg" alt="Heroku Product">
                <h3>
                    <img src="https://envs.sh/_Kx.png" alt="Heroku Icon" style="width: 24px; height: 24px; vertical-align: middle;">
                    Heroku Cloud Services
                </h3>
                <p>Flexible and scalable cloud platform for deploying and managing applications.</p>
                
                
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Heroku Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        1 Month - ₹150.00
                    </p>
                    <button onclick="addToCart('Heroku 1 Month', 150)">Add to Cart</button>
                </div>
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Heroku Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        Team Account - ₹350.00
                    </p>
                    <button onclick="addToCart('Heroku Team Account', 350)">Add to Cart</button>
                </div>
            </div>

            
            <div class="product-card">
                <img src="assets/images/telegram-product.jpg" alt="Telegram Product">
                <h3>
                    <img src="https://envs.sh/_Kx.png" alt="Telegram Icon" style="width: 24px; height: 24px; vertical-align: middle;"> 
                    Telegram Account Services
                </h3>
                <p>Choose a country-specific Telegram account to suit your needs.</p>

                
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Telegram Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        Indian Telegram Account - ₹60.00
                    </p>
                    <button onclick="addToCart('Indian Telegram Account', 60)">Add to Cart</button>
                </div>
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Telegram Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        USA Telegram Account - ₹180.00
                    </p>
                    <button onclick="addToCart('USA Telegram Account', 180)">Add to Cart</button>
                </div>
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Telegram Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        South Africa Telegram Account - ₹100.00
                    </p>
                    <button onclick="addToCart('South Africa Telegram Account', 100)">Add to Cart</button>
                </div>
                <div>
                    <p>
                        <img src="https://envs.sh/_Kx.png" alt="Telegram Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                        Russia Telegram Account - ₹130.00
                    </p>
                    <button onclick="addToCart('Russia Telegram Account', 130)">Add to Cart</button>
                </div>
            </div>

        </div>
    </section>

    
    <section id="cart">
        <h2>Your Cart</h2>
        <div id="cart-items">
            
        </div>
        <button onclick="proceedToCheckout()">Proceed to Checkout</button>
    </section>

    <script>
        // JavaScript for managing the cart
        const cart = [];
        const cartCountElement = document.getElementById('cart-count');
        const cartItemsElement = document.getElementById('cart-items');

        function addToCart(product, price) {
            cart.push({ product, price });
            updateCart();
        }

        function updateCart() {
            cartCountElement.textContent = cart.length;
            cartItemsElement.innerHTML = '';
            cart.forEach((item, index) => {
                const cartItem = document.createElement('div');
                cartItem.className = 'cart-item';
                cartItem.innerHTML = `<p>${item.product} - ₹${item.price}</p><button onclick="removeFromCart(${index})">Remove</button>`;
                cartItemsElement.appendChild(cartItem);
            });
        }

        function removeFromCart(index) {
            cart.splice(index, 1);
            updateCart();
        }

        function proceedToCheckout() {
            if (cart.length === 0) {
                alert('Your cart is empty!');
                return;
            }
            window.open('https://envs.sh/_GM.png', '_blank'); // Open the QR code for payment
        }
    </script>

</body>
</html>

**Comment by vidorteg** [comment]
Closing due to missing details, feel free to reopen once more information has been added.
