### ISSUE TITLE
Outdated error message

### ISSUE THREAD

**Issue by maame-18** [microsoft/vscode-edge-devtools#2571]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

There has been an error message pop up that talks about outdated codeAction
I have uninstalled the extensions I'm using and reinstalled but it still shows up

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by maame-18** [comment]
Please I need urgent assisstance

**Comment by vidorteg** [comment]
Hi @maame-18 

Could you please provide more details on the issue you are facing?

- Extension version, OS version and some repro steps?
- Are you having issues with headless or non-headless mode?
- Is this report for Edge browser, Edge Devtools VSCode extension or for VSCode?

**Comment by maame-18** [comment]
Hello Vidorteg
I would make sure to provide these vital information for further understanding. 
Thank you

**Comment by vidorteg** [comment]
closing due inactivity please feel free to reopen if more information is available
