### ISSUE TITLE
"Jump to file" could behave more like the Edge developer tools in the browser

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-edge-devtools#259]
When clicking on a style property in the styles pane of the extension, you jump to the corresponding CSS file. This is very nice, but I would suggest to align this click behaviour with the behaviour in the Edge devtools in the browser:

- when clicking on a style property, don't jump to the file
- when clicking on the filename, do jump to the file
- when control-clicking on a selector, style property or value, do jump to the corresponding file and line

The reason for this suggestion is that I sometimes just want to alter a value and do some minor CSS tweaking on a related component, while working in the context of another component. I don't want to switch context to the related component, because I'm just temporarily trying some things out to see how it interacts with the component I'm working on. Therefore, I think it could be nice if the file-jumping is a bit more of an explicit user action (by only jumping to the file when the user clicks on the filename, or when CTRL is used).

**Comment by codepo8** [comment]
This should work when you have your files synced. As we don't have the sources tab like we have in the developer tools, I wonder where the link should go. I agree though that it shouldn't be a link if it doesn't go anywhere.

**Comment by mliao95** [comment]
Hi billie-spektor.  After testing around, I can see your frustration with this behavior.  I'll take a look and try implementing a better workflow for this.  Thanks for filing this issue!

**Comment by billie-spektor** [comment]
Thanks :) The gif in the pull request looks good!
