### ISSUE TITLE
Does not recognize MSEdge on my mac

### ISSUE THREAD

**Issue by damerms** [microsoft/vscode-edge-devtools#260]
I am on a 2010 Mac running the last version of High Sierra (10.13.6) and the latest version of VS Code. When I click the + icon, I get the following notification. 

Microsoft Edge could not be found. Ensure you have installed Microsoft Edge and that you have selected 'default' or the appropriate version of Microsoft Edge in the extension settings panel.

**Comment by codepo8** [comment]
Sorry to ask, but you did install Edge on your computer, right? High Sierra is supported.
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems

**Comment by mliao95** [comment]
Hi damerms,

We currently look for the default Edge application at:
`/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge` for MacOS.
Could you verify if the path for your Edge browser differs from this?

**Comment by damerms** [comment]
Here is where mine is located.

Applications/Browsers

Thanks,
David Mermelstein
Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760
▲ Plan ● Design ■ Code

ᐧ

**Comment by codepo8** [comment]
Hello, David, 

this is where the app package is stored, which isn't where your Mac puts all the parts of the browser code. 

Can you try the following, and see if it brings the results we expect?

Open the Terminal:

Press Command+Space together and type in "Terminal" - hit enter.

You should get a terminal window
![image](https://user-images.githubusercontent.com/13508/106530415-8e74a280-64ec-11eb-9cf5-9ce23bcf7166.png)

type "cd /Applications/Microsoft\ Edge.app/Contents/MacOS/"

What do you get?

**Comment by damerms** [comment]
Hello -

I get no such directory. I had submitted an issue and stated all my
browsers are in a custom folder called browsers.

Thanks,
David Mermelstein
Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760
▲ Plan ● Design ■ Code

ᐧ

**Comment by codepo8** [comment]
Ah, so you customised your install to a certain folder. That's unfortunate. It might be interesting to make this customisable in the extension settings, but we don't have that yet. As the extension has no way to know where you installed your Edge, could you try to create a symlink to point to the bespoke location?

ln -s /Applications/Microsoft\ Edge.app/Contents/MacOS/ Applications/Browsers/

**Comment by damerms** [comment]
How do I do that?

Thanks,
David Mermelstein
Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760
▲ Plan ● Design ■ Code

ᐧ

**Comment by codepo8** [comment]
https://www.switchingtomac.com/tutorials/osx/how-to-create-symlinks-on-your-mac/

**Comment by flynnolivia** [comment]
Hey @codepo8, I tried out this symlink approach and it didn't seem to work; I think puppeteer doesn't know how to handle a symlink at the executable path instead of an actual executable.

A custom executable location isn't supported by the extension right now so I'm going to close the issue, but this is probably something we should add in the future. We'd just need to make sure the exe they point to is actually Edge and not a different browser-- not sure how easy or difficult that would be.
