### ISSUE TITLE
Enhancement: Add React to Edge DevTools 

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-edge-devtools#265]
Add react functionality from https://github.com/facebook/react/tree/master/packages/react-devtools

**Comment by pcjmfranken** [comment]
Browser extensions are massive security and data governance liabilities, and therefore not even allowed anywhere near many environments. Default inclusion of browser extensions or any automated installation mechanisms would make this extension a definite no-go.

Adding/fixing support for manually installed browser extensions would be fine though (but performance profiling tabs integration first please!). Currently this extension fails to attach to or launch Edge with extensions (well, at least the two I tested).

**Comment by captainbrosset** [comment]
Turns out we already have an issue tracking this: #1039. So closing this one as a duplicate.
