### ISSUE TITLE
Multiple buttons are not rendering in the DevTools

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode-edge-devtools#280]
![extension-buttons-not-rendering](https://user-images.githubusercontent.com/14304598/107310534-7bf4ee80-6a41-11eb-9771-a22706d30db7.gif)

**Comment by mliao95** [comment]
This is most likely due to some change in permissions on the VSCode side.  This is repro-ing in the marketplace extension and older versions of the extension where it was known to be working before.

This issue is caused because the resource loading is being blocked by the client.
![image](https://user-images.githubusercontent.com/14304598/107310779-f32a8280-6a41-11eb-9bcc-0b91a4674e65.png)

Note: VSCode is at version 1.53.0

**Comment by mliao95** [comment]
Working fine in 1.52.1
![image](https://user-images.githubusercontent.com/14304598/107411765-c28b2d00-6ac3-11eb-852b-9d3dd84a66bd.png)

**Comment by mliao95** [comment]
Appears to also be working fine in VSCode insiders (1.54.0).  Hopefully this is a transient issue, but will keep an eye on it

**Comment by vidorteg** [comment]
it is working for me on the latest stable 1.53.2
![image](https://user-images.githubusercontent.com/43078681/107702284-e0e15c00-6c6e-11eb-9e71-a2c8f6d3537a.png)

hopefully this was a one off, as it is working on stable lets close this and reopen if needed.

**Comment by mliao95** [comment]
Reopening this bug as we are still seeing this issue after stable has upgraded to 1.54.1.

After some investigation, I figured out that this is caused by the `"webview.experimental.useIframes": true` flag.  This makes this issue less urgent as we are not expecting our users to have this experimental flag enabled.

We can track the issue on the vscode side here:
https://github.com/microsoft/vscode/issues/118181

**Comment by codepo8** [comment]
What is the state of this?
