### ISSUE TITLE
How to setup for Angular?

### ISSUE THREAD

**Issue by snebjorn** [microsoft/vscode-edge-devtools#285]
I'm having some issues getting the "auto attach debugger" feature to work.

I generated a fresh angular project and added this `launch.json` config

```jsonc
{
  "configurations": [
    // this one works. It opens a chrome window and hits my break points.
    {
      "type": "pwa-chrome",
      "name": "http://localhost:4200/",
      "request": "launch",
      "url": "http://localhost:4200/"
    },
    // this one does not works. It opens a headless edge window, but it does not hit my break points.
    {
      "type": "vscode-edge-devtools.debug",
      "request": "launch",
      "name": "Launch Microsoft Edge and open the Edge DevTools",
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/1266245/108288056-2e3c5c80-718c-11eb-8d8b-067dd921ac46.png)

I tried fiddling around with `sourceMapPathOverrides` but I can't seem to get it right.

The `webpack:///` content looks like this
![image](https://user-images.githubusercontent.com/1266245/108288561-16b1a380-718d-11eb-8bb9-666fbd9c509b.png)

**Comment by snebjorn** [comment]
I'm at a loose here. This configuration hits my break points just fine

```jsonc
{
  "type": "edge", // not vscode-edge-devtools.debug
  "request": "launch",
  "name": "Edge DevTools",
  "url": "http://localhost:4200",
  "port": 9222,
  "webRoot": "${workspaceFolder}"
}
```

What am I doing wrong?

**Comment by snebjorn** [comment]
@vidorteg sorry to bother you, but I noticed you've been assigned to this issue. Perhaps you can help me.

In the latest release v1.1.6 this was mentioned "Removed Debugger for Microsoft Edge as a dependency". Along side this change all documentation of how to configure/launch the debugger was also removed. All that is left is a few bullet points in the ToC that point to nothing :/

Anyway, I updated `ms-edgedevtools.vscode-edge-devtools` and removed the `msjsdiag.debugger-for-edge` extension from my VSCode and ran with the previous config (see OP). But the debugger still doesn't attach.

Can you point me in the direction of the documentation that shows how to configure `vscode-edge-devtools.debug` if that's what it's still called.

**Comment by bgoddar** [comment]
Hi snebjorn. So sorry for the long delay here.

With version 1.2.0, we have integrated elements inspect functionality into JavaScript Debugging provided natively by VSCode. So, if you configure your launch.json with "pwa-msedge", you will now be able to set breakpoints in your source code, and then use the new inspect icon to attach the Elements/network tools for additional debugging:

![image](https://user-images.githubusercontent.com/42152559/130515333-e32562c5-c5ab-4e74-9980-09de0c4036fd.png)

Previously, we were unable to inform vscode to attach the js debugger and our extension at the same time, but now it should be straight forward to attach our extension to a process already being debugged.

Hopefully this solution works for you. If not please feel free to re-open this issue and we will take a closer look!
```
{
  "type": "pwa-msedge",
  "request": "launch",
  "name": "Launch Edge",
  "url": "http://localhost:4200",
  "port": 9222,
  "webRoot": "${workspaceFolder}",
  "runtimeArgs" [
      "--headless" // if you still want edge to launch in headless mode. Otherwise remove the runtimeArgs option
  ]
}
```
