### ISSUE TITLE
Favicon is flaky

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode-edge-devtools#293]

**Comment by vidorteg** [comment]
I see favicon breaking the side panel from time to time, usually the loading bar just keeps moving forever and no targets are shown, I was able to repro this a lot by setting 127.0.0.1/test as the default open page. So it could be that is not the test the one which is flaky but the favicon

**Comment by vidorteg** [comment]
![image](https://user-images.githubusercontent.com/43078681/110740833-86dda300-81e8-11eb-9184-9f5adcb8e4f4.png)
