### ISSUE TITLE
Visual Studio Code - Insiders: Running the contributed command: 'vscode-edge-devtools-view.launch' failed.

### ISSUE THREAD

**Issue by abusada** [microsoft/vscode-edge-devtools#295]
Hello, I am unable to run the extension, clicking "Open new tab"

![CleanShot 2021-03-10 at 13 50 14](https://user-images.githubusercontent.com/2572320/110625012-95f03100-81a7-11eb-99f4-a50dbe939eae.jpg)

I see the following message
> Running the contributed command: 'vscode-edge-devtools-view.launch' failed.

![CleanShot 2021-03-10 at 13 47 45](https://user-images.githubusercontent.com/2572320/110624782-53c6ef80-81a7-11eb-8950-9f502457ccf3.jpg)

vscode specs
![CleanShot 2021-03-10 at 13 48 47](https://user-images.githubusercontent.com/2572320/110624798-588ba380-81a7-11eb-92ad-8adfd5f9c204.jpg)

Machine specs
![CleanShot 2021-03-10 at 13 48 57](https://user-images.githubusercontent.com/2572320/110624818-5fb2b180-81a7-11eb-854c-040fc2f8c5ae.jpg)

**Comment by mliao95** [comment]
Hi!  Thanks for reporting this.  We actually have a bug and a fix open for this already.  Going to close the issue.

Bug: https://github.com/microsoft/vscode-edge-devtools/issues/277

PR: https://github.com/microsoft/vscode-edge-devtools/pull/287

**Comment by mliao95** [comment]
As a note, the workaround for this is to wait a couple more seconds and it should work.  The issue I was running into was that VSCode would generate the button before it could be instantiated on our end.

Let me know if waiting a couple seconds doesn't work and it stays broken.  I can re-open this issue in that case.

**Comment by abusada** [comment]
Hello @mliao95 .. waiting a couple of seconds doesn'tt solve the issue

**Comment by mliao95** [comment]
Re-opening the issue.

**Comment by mliao95** [comment]
Could you expand the error and post what it says?

**Comment by abusada** [comment]
I think this should be helpful?
note that I have node version: v12.20.2, do I need to upgrade nodejs maybe? 

![CleanShot 2021-03-12 at 11 36 55](https://user-images.githubusercontent.com/2572320/110921503-4769a080-8327-11eb-9054-1d6fab6fb553.jpg)

**Comment by flynnolivia** [comment]
This is likely an issue the extension is having with ARM devices. We can reference #301 to track the progress on this bug.

**Comment by flynnolivia** [comment]
Hi @abusada, we just released v1.1.6 of the extension which fixes the issue with ARM devices. If you're still unable to launch, let me know and we can re-open the issue. Thanks!
