### ISSUE TITLE
Fix ESlint issues

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode-edge-devtools#324]

**Comment by mliao95** [comment]
PR containing all auto-fix resolutions: https://github.com/microsoft/vscode-edge-devtools/pull/323#pullrequestreview-621654845
712 errors to 296 errors

**Comment by flynnolivia** [comment]
PR migrating rules from browser DevTools to our extension: #335 -> 3956 errors
PR containing auto-fix resolutions: #339 -> 142 errors

**Comment by flynnolivia** [comment]
PR containing manual fixes: #346 -> 0 errors

**Comment by flynnolivia** [comment]
Going to close the issue, as all the linting errors have been fixed and linting is re-enabled.
