### ISSUE TITLE
The extension should have an intro call to action when opening the side bar

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-edge-devtools#331]
When you click the debugger you get calls to action what to do next. The extension needs to do the same. Can we add a start document.

![idebugger information when you start it](https://user-images.githubusercontent.com/13508/112887752-d589a900-90d3-11eb-84de-f833167002e5.png)

**Comment by flynnolivia** [comment]
Is this a duplicate of #337 or is there some separate work here?

**Comment by mliao95** [comment]
Looks like it.  We can probably close this one out and use the other one.
