### ISSUE TITLE
Updates to resource loading in VSCode Insiders breaks the extension

### ISSUE THREAD

**Issue by flynnolivia** [microsoft/vscode-edge-devtools#359]
VSCode is switching from custom resource loading using `vscode-webview-resource:` to using service workers to load resources. This means that resources will now be loaded into a structure like `<iframe><iframe></iframe></iframe>` instead of `<webview><iframe></iframe></webview>`.

To repro: Within VSCode Insiders, use the extension to launch an instance of edge
Expected result: The devtools appear in a new pane to the right
Actual result: The pane that typically holds the devtools is blank, except for an error message like `ResourceNotFoundThe specified resource does not exist. RequestId:68872f37-801e-0011-5c5c-353d11000000 Time:2021-04-19T20:43:37.3899983Z`

Commits containing the breaking changes:
https://github.com/microsoft/vscode/commit/de9887d9e0eaf402250d2735b3db5dc340184b74
https://github.com/microsoft/vscode/commit/d05ded6d3b64fed4a3cc74106f9b6c72243b18de

**Comment by bgoddar** [comment]
Related VSCode issue: https://github.com/microsoft/vscode/issues/121479
