### ISSUE TITLE
Unclear how to close Drawer in devtools inside VSCode extension

### ISSUE THREAD

**Issue by bgoddar** [microsoft/vscode-edge-devtools#394]
Describe the bug
Without the x button on panes in the drawer, there are no visual indicators on how to dismiss the drawer in the extension (when what's new and Network Request Blocking are visible)

To Reproduce

Enable network in the extension
Toggle drawer using ESC
We should consider adding a tooltip on the drawer panel or similar

**Comment by codepo8** [comment]
Why isn't there an x button? Couldn't we just add it?
