### ISSUE TITLE
Hide DevTools Console output when attached to a debug session

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-edge-devtools#403]
This seems to cause some confusion (https://github.com/microsoft/vscode/issues/125071) and is redundant when launching from a js-debug session which already has output in the Debug Console

**Comment by bgoddar** [comment]
Honestly, I don't think it makes much sense for us to include a limited/one-way console when instead we should just direct users to JS debug. I'll update with a Deprecation notice directing users to JS Debug, and we can remove entirely in a future update.

**Comment by bgoddar** [comment]
Hmmm. Actually, I guess the one case it might be useful is attaching to a target we are not using a debug session for. I'll discuss with the team if the best course of action is removing entirely or just disabling when attached to active target

**Comment by codepo8** [comment]
This is an upcoming scenario now.

**Comment by bgoddar** [comment]
@codepo8 this is already checked in. Re-closing

**Comment by bgoddar** [comment]
My mistake. Not checked in yet, but will be checked in today :)

**Comment by codepo8** [comment]
Added in the latest version of the extension
