### ISSUE TITLE
You can only have one instance of the Elements Tool open at a time

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#41]
When I have two tabs open with --remote-debugging enabled, I can only connect the Elements Tool to one tab at a time. I have to close the Elements tool in VS Code, selected the next tab and then it opens against that tab.
![image](https://user-images.githubusercontent.com/33229964/59389746-fa0c6980-8d23-11e9-878f-c8fdc5329190.png)

I can't have two instances of the Elements tool attached to two different tabs at one time.

**Comment by codepo8** [comment]
This looks like sensible behaviour to me. Can you verify.

**Comment by codepo8** [comment]
This has been fixed.
