### ISSUE TITLE
Unable to use the extension with VS Code remote

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/vscode-edge-devtools#413]
_This is a companion to https://github.com/microsoft/vscode-js-debug/issues/1024, but I thought it best to have here as well for tracking._

**Issue**

When using the new inspector feature of `js-debug` to add an Edge inspector to an existing browser, it fails in remote environments as it doesn't detect the extension is installed. This would be due to [`vscode.extensions.all` not working as expected in remotes](https://github.com/microsoft/vscode/issues/82633).

To test a workaround, I created a custom build of `js-debug`, but while it is able to show the inspector panel as expected, the inspector doesn't connect to Edge in a way that you can see the DOM or Network information (the JS console is connected though, so anything written with `console.*` by the browser appears in VS Code).

You can see the issue in action in the following video:

https://user-images.githubusercontent.com/434140/121441596-7696b900-c9cd-11eb-8522-af5d3f205d8b.mp4

It's worth noting that you can use the Edge extension to launch a remotely controlled version of Edge and use the DOM/network inspectors from a remote, so it's likely something to do with the integration between the Edge extension and `js-debug`.

**Comment by codepo8** [comment]
Thank you, this is an interesting problem, we'll add it to the current bug sprint.

**Comment by aaronpowell** [comment]
Make sure you are across the discussion on https://github.com/microsoft/vscode-js-debug/issues/1024 as there's some more insights into it there 😁

**Comment by vidorteg** [comment]
Doing some cleaning. I tested the reported scenario and seems it is working with the latest version of the extension and I also see work done to fix this. Seems the only remaining work was to close this item, please feel free to reopen if this issue is still present
