### ISSUE TITLE
Closing a tab does not close the Elements tool in VS Code

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#42]
When I close a tab in the Edge browser, the Elements Tool in VS Code does not close. It just disconnects from the target tab.
![image](https://user-images.githubusercontent.com/33229964/59389825-422b8c00-8d24-11e9-8729-20a906a57d09.png)

**Comment by vidorteg** [comment]
Addressing this in:
https://github.com/microsoft/vscode-edge-devtools/pull/89

**Comment by codepo8** [comment]
Thanks, @vidorteg.

**Comment by vidorteg** [comment]
Merged so closing.
