### ISSUE TITLE
Is it possible to debug JS with Edge in headless mode?

### ISSUE THREAD

**Issue by gmcquistin** [microsoft/vscode-edge-devtools#428]
Is it possible to debug JS with Edge in headless mode?

I'm not sure if there is a configuration that allows this. It'd be great to have the debugger and Edge in the same VS Code window.

**Comment by codepo8** [comment]
Right now the debugger always opens a windowed version of the browser, we're looking into this, thanks for your feedback.

**Comment by bgoddar** [comment]
Hey! sorry this took so long to get back to. I did some digging and it is possible to configure JS Debug to launch in headless mode. To do this, set up your launch.json config for "pwa-msedge" to have a "runtimeArgs": ["--headless"] parameter. something like:
```
      {
            "name": "Launch Edge",
            "request": "launch",
            "type": "pwa-msedge",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "runtimeArgs": [
                "--headless"
            ]
        },
```
Then when launching edge, you will be able to hit the inspect icon in the debugger bar: 
![image](https://user-images.githubusercontent.com/42152559/130132015-56fd72ec-6dd7-484d-b1b1-8f220b28c33d.png)

And attach the Edge Devtools. Let us know if that works for you!

**Comment by gmcquistin** [comment]
That works perfectly, thank you so much for looking into this for me. This works great especially for large screens because I can really make the most of the screen real estate and keep everything in one window! 🎉 Thanks again!

**Comment by bgoddar** [comment]
Glad to hear it! Thanks again for the feedback.
