### ISSUE TITLE
[FEATURE] Would like access to console in dev tools

### ISSUE THREAD

**Issue by marcoseiza** [microsoft/vscode-edge-devtools#429]

**Comment by prometheas** [comment]
Same! It would be very useful to have the console messages from my React Native app surfaced directly in the IDE, as this would allow me to split screen between VS Code and my simulator, whilst keeping an eye on the console output.

**Comment by codepo8** [comment]
You can, if you use the debugging workflow to launch the extension the  debugging console is the console of the Edge instance. You can [see it in action in this video](https://www.youtube.com/watch?v=IF69nJ7El2Y).

I'll be updating the documentation accordingly, thank you for flagging this up.

**Comment by codepo8** [comment]
TODO: @codepo8
