### ISSUE TITLE
Mouse hover on DOM element or node should highlight it in the browser

### ISSUE THREAD

**Issue by jurijsk** [microsoft/vscode-edge-devtools#445]
When debugging something related to DOM it is quite handy to know why element you currently have in your scope (in TS of JS file) Browser DevTools allows you to mouse over it and highlight in on the page. VSC DevTools do not. Same is true for the console in the browser and in vscode.

![image](https://user-images.githubusercontent.com/351671/128673691-90236cab-9acb-4f03-9fe2-7af6ade75626.png)

Would be great to have this feature in vs code.

**Comment by bgoddar** [comment]
Thank you for filing this issue! I've opened a feature request on the JavaScript debugging crew. However, it may require some changes on our part as well, so I'll leave this open in the meantime

**Comment by bgoddar** [comment]
Hi jurjisk, Looks like we are blocked on a limitation from Visual Studio Code itself. There are more details in the mentioned bug that I've linked above. In the meantime, closing out this issue
