### ISSUE TITLE
In-browser mouse over is smarter about calculating values of expressions

### ISSUE THREAD

**Issue by jurijsk** [microsoft/vscode-edge-devtools#446]
When one mouse over in in-browser DevTools over `array[i]` it can calculate values for `array`, `i`, and `array[i]`.

Vscode DevTools only can do first two and not the last. The problem is even more prominent when you need to iterate over string, all you can see in this case is just the whole string and current index.

**Comment by bgoddar** [comment]
Thank you for reporting the issue, I have filed a request on the javascript debugging team: https://github.com/microsoft/vscode-js-debug/issues/1082
