### ISSUE TITLE
No UI to get the in-tool Elements settings

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#45]
In order to toggle in-tool Element settings you need to press F1. There's no UI to bring them up.
![image](https://user-images.githubusercontent.com/33229964/59390255-9a16c280-8d25-11e9-880d-67ef1a0973de.png)

Possibly we could migrate the settings to the VS Code extension settings instead.

**Comment by codepo8** [comment]
This is a tricky one as we want - if possible - to get the settings from VSCode.
