### ISSUE TITLE
Better screencast

### ISSUE THREAD

**Issue by erilod** [microsoft/vscode-edge-devtools#453]
Suggestion after some time using the devtools

When working with design it would be nice to be able to resize the "screencast view" so you can test the Media Queries and responsive layouts. In current version it also resize the browser tab so you cant make design decisions upon it, and has to witch to the browser all the time. It also very laggy.

**Comment by bgoddar** [comment]
Thank you for the suggestion! We are tracking screencasting improvements with #243 and hope to tackle these suggestions there!
