### ISSUE TITLE
Debug Console's typeahead behavior deferens from conventinal

### ISSUE THREAD

**Issue by jurijsk** [microsoft/vscode-edge-devtools#457]
Hi, this one if form UX department.

Behavior of typeahead/autocomplete behavior if debug console is different from behavior of intellisense in vscode or console typeahead in the browser. It requires user to hit Tab to complete the suggestion and then enter to accept, while everywhere else enter (along with tab) works to accept/complete the suggestion. In the browser second 'Enter' hit causes execution.

Would be great to sync the interactions, because ... muscle memory :)
 
![typeahead](https://user-images.githubusercontent.com/351671/129494845-669dffb6-84b0-4ced-a0b4-2ce7edb9911b.gif)

**Comment by bgoddar** [comment]
Thank you for reporting this issue/request. I have filed a feature request on the team that owns the "Debug Console". Thanks!
