### ISSUE TITLE
I can't launch the Elements tool for debugging nor combine it with a debugger extension through a launch.json config

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#47]
I want to be able to combine launching the Elements tool extension with the Debugger tool extension: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge in my launch.json config

**Comment by paulgildea** [comment]
Dupe of #54

**Comment by jalissia** [comment]
I feel this is actually a separate issue now that I've started implementation. So I'm going to reopen (since I have a fix for the other but not this one yet)

**Comment by vidorteg** [comment]
Duplicate of #68 , although this was reported first, I'm closing this one as #68 provides more details and it has the same author.
