### ISSUE TITLE
CSS Mirror Editing: Known Issues and Feedback

### ISSUE THREAD

**Issue by flynnolivia** [microsoft/vscode-edge-devtools#476]
CSS mirror editing is an experimental feature that automatically applies changes made in the DevTools panel to CSS files in your workspace. See the GIF below for a small demonstration!

**Enabling CSS Mirror Editing**
This feature is available starting in v1.3.1. To enable CSS mirroring you will need to target Canary (Settings->Browser Flavor->Canary), then look for the "CSS Mirror Editing" section in the sidebar after opening the DevTools.

**This issue is a central location where we will collect:**
- Known issues/bugs
- Typical workflows surrounding this tool (i.e., how do you use this tool, or how would you like to be able to use it?)
- Other feedback / suggestions to improve the feature

![cssMirrorContent](https://user-images.githubusercontent.com/80795982/130849255-9369fe8a-4bf6-4b4e-a3c3-89f8e4be9f27.gif)

**Comment by codepo8** [comment]
The mirroring explanation and button also shows up when Canary isn't the browser flavour and doesn't work. We should check the version number and only light it up when an Edge of the right version is used as the target.

**Comment by mok-liee** [comment]
oh my god 😱 i actually have to sleep but still briefly browse the web and see THIS. wow, i'll test it out tomorrow right away! but i want to get rid of my questions now. all questions that are answered with no are automatically feature requests:

- [ ] does it work with bundler like webpack? (cause the output css is not everytime the src css/scss)
- [ ] is there a plan for firefox and chrome support?

thank you so much 🙏🎉

**Comment by Steve6030** [comment]
What am I doing wrong that I don't have the option for css mirroring?


`
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z (1 day ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0`

`Microsoft Edge
Version 93.0.961.52 (Official build) (x86_64)
`

`Microsoft Edge Tools for VS Code
v1.3.1
`
<img width="1904" alt="Screen Shot 2021-09-23 at 9 26 25 PM" src="https://user-images.githubusercontent.com/20916993/134604707-1be5d227-6459-42f3-b00a-0b870f4a33f8.png">


Thanks in advance!

**Comment by patrick-lemanski** [comment]
@Steve6030 Your Edge Version must be >= 94.0.988.0

**Comment by codepo8** [comment]
> What am I doing wrong that I don't have the option for css mirroring?

> `Microsoft Edge Version 93.0.961.52 (Official build) (x86_64) `
> 
> Thanks in advance!

Hi there, currently this only works with a newer version of Edge. You need to set the target of the extension to "Canary" in the settings and get a Canary version. Once stable hits 96, this will not be needed any longer.

![image](https://user-images.githubusercontent.com/13508/134660068-0daf3cac-286d-4918-a730-3ba5a25d1745.png)

**Comment by mok-liee** [comment]
Hi, my css is not reflecting to the src :(

i am using:

- `Edge Browser: Version 96.0.1025.0 (Offizielles Build) canary (64-Bit)`
- `Microsoft Edge Tools for VS Code v1.3.1`
- `vscode 1.60.1`

my launch.json is like: 

```json
    {
      "name": "Launch Microsoft Edge and open the Edge DevTools",
      "request": "launch",
      "type": "vscode-edge-devtools.debug",
      "url": "http://localhost:3000"
    }
``` 

and my settings.json is like:

```json
  "vscode-edge-devtools.browserFlavor": "Canary",
  "vscode-edge-devtools.pathMapping": {
    "/": "${workspaceFolder}\\frontend"
  },
  "vscode-edge-devtools.mirrorEdits": true
```

the browser is launching, dev tools are running in vscode, if i click on a class in dev tools the src scss is opening in vscode but every change that i made in the devtools are not reflecting to the scss file.

what can i do more?

**Comment by codepo8** [comment]
> the browser is launching, dev tools are running in vscode, if i click on a class in dev tools the src scss is opening in vscode but every change that i made in the devtools are not reflecting to the scss file.
> 
> what can i do more?

Hey there, SCSS is currently not supported, the mirroring only works with plan CSS files. We're working on it but we're hitting some issues with going backwards on the transpilation.

**Comment by omarragab1219** [comment]
VS Code Version: Version: 1.60.2 (Universal)
Version 94.0.992.31 (Official build) (x86_64)
 macOS Big Sur

when i run my index.html file on localhost:8080 for example and try to edit the CSS in the dev tools, the extension properly tracks my location within the CSS file(highlights the correct area) BUT it does NOT edit anything in my CSS file as I change things within the dev tools(yes i checked that css mirroring was enabled in settings and in the sidebar). (also stable and default are the only settings that let me launch an instance without an error).

**Comment by viswatejavissamsetty** [comment]
Hi Team,
This feature was so nice but its not changing style parameters for frame works like React and Angular. Will you please update it to work smoothly with frameworks like react and Angular.
Thanks.

**Comment by Enteleform** [comment]
I want to set `vscode-edge-devtools.mirrorEdits` to `false`, but when I reload VSCode, it automatically gets reset to `true`.

**Comment by chickenwing** [comment]
I am using styled components inside jsx files. Any hope to get that working there?

**Comment by vanowm** [comment]
Love this feature. Unfortunately it's constantly loosing connection, I have to refresh within the browser to get it restored which also not 100% proof. But that is not the worst of the problems, the worst offender is that it corrupts CSS files when enabling/disabling an item, it randomly inserts end of a comment `blah */`, so I constantly have to monitor with jshint, which shows when file gets corrupted. Again, this happens randomly and from what I could tell after a long time using VSCode (an hour or so). Restarting the browser usually helps for a bit, but restarting vscode itself helps for much longer time.

My launche.json:
```json
{
  "name": "Launch Edge",
  "request": "launch",
  "type": "pwa-msedge",
  "url": "http://storage/experiments/tcone/",
  "webRoot": "${workspaceFolder}",
  "outputCapture": "console",
  "console": "internalConsole",
  "attach": "restart",
  "restart": true,
//   "trace": true,
  "sourceMap": false,
  "runtimeArgs": [
      "--auto-open-devtools-for-tabs"
  ]
},
```

```
Visual Studio Code

Version: 1.61.2
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Edge: 95.0.1020.30 (Official build) (64-bit)
OS: Windows_NT x64 10.0.19043
```

**Comment by KillDozerX2** [comment]
Any updates on sass support?

**Comment by ak5k** [comment]
> WSL

Also having problems with projects running in WSL.

Even when project root is set to corresponding Windows filesystem path in Edge developer tools workspace settings, VSCode still tries to open files for Mirror editing through URL (e.g. http://localhost:8080/index.html), when running in WSL. 

Following this guide in [Microsoft Edge DevTools Extension docs](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension#setting-up-your-project-to-show-live-changes-in-the-extension). This works as expected in non-WSL environment.

**Comment by imranisdev** [comment]
Does this work with React?

**Comment by chadmoore** [comment]
Is this supposed to work w/ WSL at this point?

**Comment by HenryGetz** [comment]
Chrome has had this forever, but it's been a nightmare and I have had so many projects ruined, so hopefully Microsoft can pull this off!

From my testing, it seems like whenever I try to do mirror editing another window of the file opens up even if I have one already open? It's super annoying. It seems like it is trying to open up the file right next to edge devtools, so that you can see the changes being made in your CSS file as you type in devtools, but if code mirroring works well then I would see no point to that. Hopefully this is just a bug (or only there for testing), as it would be nice to make and save changes to CSS files through code mirroring and not have it open up a new window at all...

**Comment by muhammadsalmanafzal** [comment]
Just started today with HTML/CSS. Not working with WSL.

**Comment by flyyuan** [comment]
Does this work with postcss?

**Comment by henrikvilhelmberglund** [comment]
It would be nice if this extension could disable autosave with afterDelay while editing CSS with mirror editing enabled because it seems like this combination doesn't really work, I had to disable autosave or my edits would get deleted instantly.

**Comment by codepo8** [comment]
> It would be nice if this extension could disable autosave with afterDelay while editing CSS with mirror editing enabled because it seems like this combination doesn't really work, I had to disable autosave or my edits would get deleted instantly.

Could you explain what you mean by AutoSave? CSS Mirroring as it stands does not automatically save the file, it just modifies it. Could it be that you are using live server or other extensions that do the live reload and save of the file instead?

**Comment by henrikvilhelmberglund** [comment]
> > It would be nice if this extension could disable autosave with afterDelay while editing CSS with mirror editing enabled because it seems like this combination doesn't really work, I had to disable autosave or my edits would get deleted instantly.
> 
> Could you explain what you mean by AutoSave? CSS Mirroring as it stands does not automatically save the file, it just modifies it. Could it be that you are using live server or other extensions that do the live reload and save of the file instead?

I'm using the native (I think) autosave feature in VS Code, the thing you find when searching for autosave in the settings.
If you enable it and change the type to afterDelay and the delay to 400ms VS Code will just save after 400ms which doesn't really work with CSS Mirroring because it seems like it expects you to not save the file while you're editing in Edge Devtools. For example just setting a background color in Edge Devtools and clicking the color picker and quickly selecting a few different colors will desync the mirroring (until you go back to the stylesheet itself and give it a new value and save). 

I changed it to onFocusChange instead and it works better but it's still possible to break if you click around a lot. Not really sure how to explain it but I hope this helps!

**Comment by lopugit** [comment]
Oh damn yo impressive 🤤🤤🤤

**Comment by BIGDATACENTE** [comment]
J'ai essayé, ça marche !

**Comment by sleelakbar80-star** [comment]
> CSS mirror editing is an experimental feature that automatically applies changes made in the DevTools panel to CSS files in your workspace. See the GIF below for a small demonstration!
> 
> **Enabling CSS Mirror Editing** This feature is available starting in v1.3.1. To enable CSS mirroring you will need to target Canary (Settings->Browser Flavor->Canary), then look for the "CSS Mirror Editing" section in the sidebar after opening the DevTools.
> 
> **This issue is a central location where we will collect:**
> 
> * Known issues/bugs
> * Typical workflows surrounding this tool (i.e., how do you use this tool, or how would you like to be able to use it?)
> * Other feedback / suggestions to improve the feature
> 
> ![cssMirrorContent](https://user-images.githubusercontent.com/80795982/130849255-9369fe8a-4bf6-4b4e-a3c3-89f8e4be9f27.gif) [ ![cssMirrorContent](https://user-images.githubusercontent.com/80795982/130849255-9369fe8a-4bf6-4b4e-a3c3-89f8e4be9f27.gif) ](https://user-images.githubusercontent.com/80795982/130849255-9369fe8a-4bf6-4b4e-a3c3-89f8e4be9f27.gif) [ ](https://user-images.githubusercontent.com/80795982/130849255-9369fe8a-4bf6-4b4e-a3c3-89f8e4be9f27.gif)

**Comment by stasyu2009-ux** [comment]
Дорого дня я зможу вам допомагати в проектах.

**Comment by stasyu2009-ux** [comment]
Вища веб розробка знаю декілька мов
