### ISSUE TITLE
Navigation bar in the middle of the screencast window

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#477]
**Environment (please complete the following information):**
 - OS: Windows
 - Extension version : > 1.3.0

**Describe the bug:**
When using screencast and resizing the window (on the browser side) a bar appears on the middle of the screen leaving the browser and the screencast in a non-usable state.

**Repro steps:**
1. Open the extension in non headless mode
2. Navigate to any page
3. Open screencast
4. Resize the browser window (from the browser not the extension)

**Expected behavior:**
Screencast and browser window should resize accordingly

**Additional context:**
A navigation bar appears in the middle of the screen and does not goes away (or is inspectable) until screencast is turned off.

![image](https://user-images.githubusercontent.com/43078681/131367127-708d5c7d-0f8b-47a0-9022-e447cf20beb9.png)

**Comment by bgoddar** [comment]
Hey @vidorteg, I can't repro this. Maybe we should sync this week to discuss?

**Comment by captainbrosset** [comment]
I can't repro this either. So I'll go ahead and close the issue for now. Feel free to re-open if this still occurs.
