### ISSUE TITLE
Toggling inline styles from Styles pane does not work correctly due to malformed commenting/uncommenting

### ISSUE THREAD

**Issue by hxlnt** [microsoft/vscode-edge-devtools#480]
**Environment (please complete the following information):**
 - OS: Windows (Insider build)
 - Extension version 1.3.0

**Describe the bug:**
When inline styles are added through the styles panel, toggling them on and off causes odd comment formatting, resulting in buggy behavior. The duplicate entries created sometimes cannot be deleted, meaning I have to refresh the page to get rid of them. Please see GIF. 

**Repro steps:**
1. Add new style rules to `element.style{}` in Styles pane.
2. Toggle them on and off repeatedly.

**Expected behavior:**
1. When styles are toggled, they should be correctly commented or uncommented in the inline HTML.

**Additional context:**
![css](https://user-images.githubusercontent.com/9647195/131697803-b1ade935-5156-4572-a0e7-f61c5ef0c18e.gif)

**Comment by codepo8** [comment]
Verified, that is a problem.

**Comment by mliao95** [comment]
Looks like this has been fixed.

![css-toggle-fixed](https://user-images.githubusercontent.com/14304598/157106329-bb086e33-4d54-4703-86e7-6b419fe5898d.gif)

Please comment and reactivate it this repros
