### ISSUE TITLE
Search/filter text is invisible in dark theme - white on white

### ISSUE THREAD

**Issue by johncrim** [microsoft/vscode-edge-devtools#483]
**Environment:**
 - OS: Windows 10
 - Extension version 1.3.0

**Describe the bug:**
I use the standard dark theme in VS Code. Running Edge DevTools in VS Code, text is invisible in search and filter boxes. The background is white, and the text color is white. If I select the text, I can see that the text works but is white.

![image](https://user-images.githubusercontent.com/3312127/131730680-1dc11aeb-d6a5-4e24-89c3-93902f3bbafc.png)

**Repro steps:**
1. Set a dark theme for VS Code - I use "Dark+ (default dark)"
2. Add Edge DevTools, latest version
3. Launch edge against any web page
4. In Edge DevTools, type "Ctrl + F" to launch the search box
5. Type any query - text is invisible

The same problem exists for the "Styles filter" box, and any other text entry with a white background.

**Expected behavior:**
Entered text is visible.

**Comment by bgoddar** [comment]
Thank you for reporting this issue! Sorry that this is happening for you. Looks like this is part of a larger set of issues around applying themes to the extension after a switch. There are lots of components within the devtools, and when switching themes, sometimes they are not properly updated. We have just landed an architecture update that should hopefully address these kinds of issues, but it requires targeting newer versions of Edge.

As a workaround, you can try restarting the devtools and your vscode window a couple of times to hopefully get the theme state synchronized. The search bar should match the dark theme like this:
![image](https://user-images.githubusercontent.com/42152559/131873562-574d10db-7882-4368-a4ef-f7a9bf444cd1.png)

Additionally, if you would like to try out the new changes that increase our theme support, you can try targeting Edge Canary or Dev (if you have either installed) by updating your extension settings: 
![image](https://user-images.githubusercontent.com/42152559/131873831-d31e0bf8-7331-4787-8540-1e66d7fa3bfd.png)
Targeting newer Edge versions will allow the extension to most all standard VSCode themes (Dark+, Solarized Dark, etc). These changes will roll out to stable Edge in the coming weeks as well, so hopefully this should resolve soon!

**Comment by johncrim** [comment]
Thank you @bgoddar - the problem is as you described. While I did restart VS Code yesterday, and continued to see the same problem, when I started VS Code today the problem no longer appears. Thank you.

Closing.

**Comment by bgoddar** [comment]
Glad that worked for you!
