### ISSUE TITLE
Please allow an option to toggle the DevTools panel  independently from the screencast

### ISSUE THREAD

**Issue by denik1981** [microsoft/vscode-edge-devtools#484]
**THE PROBLEM**
I came to this extension mainly for the **screencast** feature  while I stil knowledge the value of having a DevTools panel available at one side inside VSCODE.  The screencast allows me to have a quick eye live preview of what I'm doing while coding and prevents me having to switch back and forth from different GUI windows ( also prevents me the need of having an extra monitor).

The **problem** is that there is no way to toggle the DevTools panel and by itself does not give me any quick visual feedback as the screencast does, and when they are both displayed together the space left for the editor gets compromised drastically.      

**THE PROPOSAL**
The same way a toggle screencast feature is available for us I would like to have a Toggle DevTools panel option as well so that the screencast can sit alone at one side of my editor and turn on the DevTools panel when I really need it.
  

**AN ALTERNATIVE**
An alterantive might be a vertical docking layout but still while this offers a solution to prevent a compromised space on the editor, it runs at the cost of having a smaller space available to render the screencast.

**Comment by antross** [comment]
Thanks for the feedback @denik1981!

To add to your list of alternatives, one other option we've been discussing is trying to break the screencast into a separate top-level tab in VS Code (it's better isolated from the rest of the tools). This would allow us to take advantage of VS Code's windowing capabilities to snap it side by side, show it without showing the DevTools tab, etc.

What do you think?

**Comment by denik1981** [comment]
@antross Absolutely. It's probably an even better idea. Mixing up the live preview with the Editor Group doesn't seem quite right and requires a lot of integration workload for any future change on the Editor's pane

Morover to better translate the side-by-side 2 monitors setup some devs already have, the terminal will still cutting out some footer space from the preview and I can imagine most of us using this won't complain about losing space in there because a minor adjustment with hidding the left pane can bring up an important part of  the lost space. 

This clearly won't replace a full-width extra monitor but for a lot of us having a decent zoom-out preview is more than fine and very welcome to feel confident that our code is looking as we expected while we re working on it.

An improvised sketch version for the layout could be:

RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | EEEEEEEEEEE  | PPPPPPPP
RRRR | TTTTTTTTTTT | PPPPPPPP
RRRR | TTTTTTTTTTT | PPPPPPPP

**R:** Right Panel | **E:** Editor/s | **T:** Terminal | **P:** Preview

The right panel can be easily hidden and  the Preview Pane also gains more room to relocate the DevTools at the footer of the preview.

**Comment by codepo8** [comment]
This should be fixed with the latest version, You can now move the screencast anywhere, independent of the devtools panel.  Thanks again for your request, this makes a lot of sense.
