### ISSUE TITLE
Microsoft Edge could not be found. Ensure you have installed Microsoft Edge and that you have selected 'default' or the appropriate version of Microsoft Edge in the extension settings panel.

### ISSUE THREAD

**Issue by bagus-stimata** [microsoft/vscode-edge-devtools#486]
**Environment (please complete the following information):**
 - Extension version [e.g. 22]

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Hello there, can you please give us some more information about that issue? It seems either you haven't got Edge installed yet, or you need to tell the extension where the binary is, which changes from OS to OS.

Happy to help!

**Comment by captainbrosset** [comment]
This has unfortunately gotten stale, and we can't really investigate without more information. So closing for now.
