### ISSUE TITLE
When launching using the debugger extension does not correctly attach until the 3rd of 4th try. 

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#488]
**Environment (please complete the following information):**
 - OS: Windows
 - Extension version 1.3.0

**Describe the bug:**
When launching using the debugger extension does not correctly attach until the 3rd of 4th try. 

**Repro steps:**
- Open a test project
- Launch Edge using the debugger
- Launch devtools extension using debugger entrypoint

**Expected behavior:**
Devtools should launch and the debugger should attach

**Additional context:**
Sometimes the devtools launch but the debugger is not attached, you can also observe that screencast does not shows anything until extension is closed and relaunched.

A gif showing the issues located in here:
https://imgur.com/a/MrJhldq

**Comment by captainbrosset** [comment]
@vidorteg does this still happen? If so, should we add the `tracked` label so that it shows up on our internal backlog?

**Comment by antross** [comment]
Closing as this doesn't appear to repro anymore.
