### ISSUE TITLE
CSS style not working

### ISSUE THREAD

**Issue by FiefieBez** [microsoft/vscode-edge-devtools#490]
**Is your feature request related to a problem? Please describe.**
I am busy writing a cv project and I have done my HTML file and the Style.css but my style is not implementing on the outcome

**Describe the solution you'd like:**
What am I doing wrong? 

**Describe alternatives you've considered:**
I have changed the styles and redone it. Checked google for some possible mistakes I could've made

**Additional context:**

*{
    font-style: normal;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    list-style: none; 
    font-family: 'Montserrat', sans-serif;
}

body{
    background: #585c68;
    font-size: 14px;
    line-height: 22px;
    color: #555555;
}

**Comment by vidorteg** [comment]
Hi @FiefieBez 

If I understand correctly you are doing some changes to the CSS but those changes are not being reflected in the screencast panel or the Microsoft Edge instance associated with the session?

If this is the case can you try this?
On the "network panel", please check the "Disable cache" checkbox, then reload the screencast view.
![image](https://user-images.githubusercontent.com/43078681/133524673-3747de11-3498-4cf6-81bf-d566dd2e107e.png)

If this does not resolve the issue, could you please provide more details like some repro steps, operating system and version?

Thanks for the reporting the issue and for using the extension.

**Comment by FiefieBez** [comment]
Thanks very much for your response

**Comment by captainbrosset** [comment]
Closing as it seems like the problem was addressed.
