### ISSUE TITLE
Mirror editing having weird bug when toggling settings

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-edge-devtools#493]
**Environment (please complete the following information):**
 - OS: MacOS
 - Extension version 1.3.1

**Describe the bug:**
When you toggle settings in the CSS, the source file gets broken by repeating a few characters.

**Repro steps:**
Open a CSS file. 
Use the checkboxes to toggle a CSS setting

**Expected behavior:**
The line gets commented and uncommented

**Additional context:**
See attached screencast 

https://user-images.githubusercontent.com/13508/133339219-3ce04007-8a43-48a5-9f3a-517e42c18754.mp4

**Comment by bgoddar** [comment]
might be related to #480 @mliao95  fyi

**Comment by captainbrosset** [comment]
I can't repro this problem anymore. I think this got fixed, so I'm closing the issue now. But @codepo8 feel free to reopen if this still occurs to you.
