### ISSUE TITLE
input

### ISSUE THREAD

**Issue by hasaaq2** [microsoft/vscode-edge-devtools#507]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Hi, thank you for the feedback. Unfortunately there isn't enough information for us to investigate the issue here. I will close the issue for now, feel free to come back with more information and we can re-open it.
