### ISSUE TITLE
I am prompted to set root folder, but button does nothing

### ISSUE THREAD

**Issue by hxlnt** [microsoft/vscode-edge-devtools#539]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11
 - Extension version (*e.g.,* 1.2.3): 1.0.15

**Describe the bug:**
When running the extension against localhost, an infobar appears. Clicking "Set root folder" does not seem to do anything.
![setrootfolder](https://user-images.githubusercontent.com/9647195/135640255-f023a155-55d0-4f08-9cdc-5b61a7e5ac1e.gif)

**Repro steps:**
Launch an instance against localhost using Canary channel.

**Expected behavior:**
Guessing this infobar should not appear at all if it is only relevant outside of VS Code?

**Comment by bgoddar** [comment]
Should be resolved with recent change to DevTools
