### ISSUE TITLE
webRoot attribute in launch.json configuration

### ISSUE THREAD

**Issue by zoherghadyali** [microsoft/vscode-edge-devtools#54]
So when I use the Debugger for Edge VS Code extension, my launch config looks like: 
```json 
      {
            "type": "edge",
            "request": "launch",
            "version": "canary",
            "name": "Launch Edge",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
```

We use the webRoot attribute to point to the directory that files are served from. It can be either an absolute path or a path using ${workspaceFolder} (the folder open in Code). webRoot is used to resolve urls (like "http://localhost/app.js") to a file on disk (like /Users/me/project/app.js).

Please add the webRoot property so that I don't have to think about different launch.json configs for my 2 Edge extensions.

**Comment by codepo8** [comment]
This is fixed.
