### ISSUE TITLE
dss

### ISSUE THREAD

**Issue by damu316** [microsoft/vscode-edge-devtools#541]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately this issue does not contain enough information for us to investigate the problem.
I will close it for now, but feel free to come back with more information.
