### ISSUE TITLE
[Feature request] Enable edge flags for launch target from launch.json

### ISSUE THREAD

**Issue by nahomebssa** [microsoft/vscode-edge-devtools#547]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

An way to turn on specific flags from `edge://flags`. The `launch.json` could have a configuration option named flags which accepts an array of strings with the hash url of the flag.

```
{
    "configurations": [
        {
            "name": "Launch Microsoft Edge and open the Edge DevTools",
            "request": "launch",
            "type": "vscode-edge-devtools.debug",
            "url": "", // Provide your project's url to finish configuring,
            "flags": [
                "#enable-force-dark",
                "#edge-overlay-scrollbars-win-style",
            ]
        }
    ]
}
```

**Describe alternatives you've considered:**

Manually setting the flags every time on launch would be ineffective and unproductive.

**Additional context:**

I need to test websites when dark mode is enabled by default.

**Comment by codepo8** [comment]
This has just been released as a part of the new release. Thank you for bringing it up!
https://github.com/microsoft/vscode-edge-devtools/pull/689
