### ISSUE TITLE
Remove ts and lint exceptions from src/utils.ts

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#551]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): NA

**Describe the bug:**
 file src/utils.ts line 229 handles the case for ECONNREFUSED, some ts and linting exceptions have been added to allow the unsafe access of the variable, this needs to be refactored to take the comments out.

**Repro steps:**
NA

**Expected behavior:**
NA

**Additional context:**
NA

**Comment by captainbrosset** [comment]
@vidorteg is this still something that needs to be done? If so, please add the `tracked` label so we can track this on the internal backlog.
