### ISSUE TITLE
Especify custom executable for Edge.

### ISSUE THREAD

**Issue by oxk4r01** [microsoft/vscode-edge-devtools#568]
Hi, could it be possible to especify a custom path for the Edge launcher? I would like to use a portable version of Edge.
Regards

**Comment by hkal** [comment]
@codepo8, what do you think about pulling this into our backlog? We could probably do something like add `customEdgePath` to settings json so we don't need to design new UI.

**Comment by codepo8** [comment]
Sounds good to me.

**Comment by antross** [comment]
@oxk4r01 this should now be possible using the `launch.json` flow for the extension. You can have the extension create a launch.json for you and customize it to add a `runtimeExecutable` entry with the path you want to use:

```diff

        {
            "type": "pwa-msedge",
            "name": "Launch Microsoft Edge in headless mode",
            "request": "launch",
+           "runtimeExecutable": "path/to/edge",
            "runtimeArgs": [
                "--headless",
                "--remote-debugging-port=9222"
            ],
            "url": "http://localhost:3002", // Provide your project's url to finish configuring
            "presentation": {
                "hidden": true
            }
        },
```
