### ISSUE TITLE
Launch Edge Tools along the current workspace

### ISSUE THREAD

**Issue by HawkFest** [microsoft/vscode-edge-devtools#576]
I have to paste the file's full name, or web URL (mainly within my localhost) in order to see my work and use DevTools.

My default browser being Firefox, it would be nice if when we launch Edge DevTools, the Edge browser also automatically opens the current file we're working on. Or at least some button we could click from within VS Code or the Edge DevTools panel to make the Edge browser open that file.

Maybe also have Edge DevTools to automatically open along a saved Workspace we'd be loading ? For instance, when we save a workspace having the tool opened, this could also save that information as part of the workspace "environment".

**Comment by captainbrosset** [comment]
I think creating a `launch.json` file is what you need here, unless I misunderstood.
To do it easily, go to the extension sidebar (by clicking the Edge logo in VS Code's activity bar), and then click on **Generate launch.json**.

This file lives in your workspace, and in it you can define the URL of your app. So after that, you can just press `F5` to launch DevTools and the browser at that URL whenever you want.

Let me know if this works for you.

**Comment by codepo8** [comment]
By using a launch.json you can make that happen.

**Comment by captainbrosset** [comment]
I think this can now be closed. Please comment again if the issue isn't solved.
