### ISSUE TITLE
Unable to connect in remote scenarios

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-edge-devtools#58]
Environment:

- VS Code stable @ latest
- Remote - SSH extension @ latest
- Remote - WSL extension @ latest
- Edge Chromium on Dev channel @ latest
- Windows 10 Insiders (18922) with WSL 2 Ubuntu (unlikely but may be related to why this isn't working)

The extension is installed as a UI extension and I'm using the default launch config:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Microsoft Edge and open the Elements tool",
      "request": "launch",
      "type": "vscode-edge-devtools.debug",
      "url": "http://localhost:8080"
    }
  ]
}
```

Working on a vue.js app.

### WSL

1. Open the integrated terminal and run `$ npm run serve` to start the app
1. Launch into the debugger

#### Result:

The browser launches and loads the page. In VS Code, an empty quick pick shows up along with the following error:

> Couldn't attach to http://localhost:8080.
onDidNotificationChange @ workbench.main.js:2379

### SSH

I'm using an Azure VM with Ubunt 16.04.

1. Connect to VM and forward ports 8080 and 9222 to localhost (see below)
1. Open the integrated terminal and run `$ npm run serve` to start the app
1. Launch into the debugger

![image](https://user-images.githubusercontent.com/1186948/60379580-57720d00-99ea-11e9-91d4-fe30c43077cd.png)

#### Results in the same behavior as WSL:

The browser launches and loads the page. In VS Code, an empty quick pick shows up along with the following error:

> Couldn't attach to http://localhost:8080.
onDidNotificationChange @ workbench.main.js:2379

Feel free to ping me on teams with any questions, I'm happy to help however I can!

**Comment by paulgildea** [comment]
@fiveisprime Thanks for the feedback! We haven't done testing with WSL or VMs yet. 

We'll follow up to understand your specific workflows. Thanks!

**Comment by jalissia** [comment]
I'll take a look into this and see if I can figure out what is going on here.

**Comment by jalissia** [comment]
This looks to be another case of the browser not launching with the --remote-debugging-port set if you already have an instance open.

The workaround is to close all instances of Edge before you launch via VS Code.

I'll leave the issue open until we can find a better fix for this.

**Comment by paulgildea** [comment]
@fiveisprime What would you expect the default behavior to be for the "Launch Microsoft Edge and open the Elements tool" configuration? Launch a new instance every time? 

We're having a similar discussion about the default behavior on Issue #57 😊

**Comment by fiveisprime** [comment]
I'll comment on #57 and close this one
