### ISSUE TITLE
Side panel does not show the site

### ISSUE THREAD

**Issue by adebiyial** [microsoft/vscode-edge-devtools#59]
I'm stuck. It connects to my live server but attaching a then it shows nothing in the Elements for Microsoft Edge pane.

![bummer](https://user-images.githubusercontent.com/18689106/60386263-a7081580-9a8a-11e9-8209-b6df3a5eb5d2.jpg)

**Comment by jalissia** [comment]
Hmm. If pressing the refresh button in the side panel still doesn't show anything my guess is that Edge didn't start with the correct remote-debugging-port set.

Can you try closing all instances of Edge and then launching via VS Code again?

**Comment by adebiyial** [comment]
You were right. It works like a charm now!
![image](https://user-images.githubusercontent.com/18689106/60389708-ab4e2600-9abe-11e9-909f-527bbdf20c5d.png)
