### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by lancehammondjr** [microsoft/vscode-edge-devtools#618]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'webpack://src/App.css'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/748

**Comment by jaywankhade99** [comment]
Where is a solution for this
