### ISSUE TITLE
Error when I Launch Project of Edge in vscode Apache Tomcat appears but not my Working Directory list of targets

### ISSUE THREAD

**Issue by madaanvaibhav** [microsoft/vscode-edge-devtools#620]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Error: socket hang up

        **Additional context:**

**Comment by madaanvaibhav** [comment]
when I Launch Project of Edge in vscode Apache Tomcat appears but not my Working Directory

**Comment by codepo8** [comment]
Hi there, could you tell us about your launch.json? All the extnsion does is point to a URL that you provide. So if your Tomcat server points to localhost but doesn't send the right folder through, this seems to be a configuration issue of the server.

**Comment by captainbrosset** [comment]
This has unfortunately gotten stale and we don't have more information to investigate. So I'll close the issue now. Feel free to comment with more information if you have any.
