### ISSUE TITLE
finding a way to enable cors

### ISSUE THREAD

**Issue by gp5251** [microsoft/vscode-edge-devtools#622]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

I'm looking for a convenient way to enable cors, and i tried using args with ["--disable-web-security"] in launch.json like blow, but it not work.

```json
{
	"name": "Launch Microsoft Edge and open the Edge DevTools",
	"request": "launch",
	"type": "vscode-edge-devtools.debug",
	"args": [
		"--disable-web-security"
	],
	"url": "" // Provide your project's url to finish configuring
}
```

**Describe alternatives you've considered:**

**Additional context:**

**Comment by gp5251** [comment]
I have created a pr to resolve this, waiting to be merged... [https://github.com/microsoft/vscode-edge-devtools/pull/623](https://github.com/microsoft/vscode-edge-devtools/pull/623)

**Comment by codepo8** [comment]
Thanks for this, great stuff!

**Comment by Naxos84** [comment]
I don't know why but this seems not to work.
I'm using version 2.1.4 of the extension.
My userssettings are:

```json
"vscode-edge-devtools.browserArgs": [
        "--disable-web-security"
    ],
```

But it is failing to load my local javascript

```html
<!DOCTYPE html>
<html lang="de">

<head>
	<title>Demo</title>
	<link rel="stylesheet" href="style.css">
</head>

<body>
	<canvas id="myCanvas"></canvas>
	<script src="main.js" type="module"></script>

</body>

</html>
```

them html file is loaded with url `file://C:/............../main.js`

**Comment by captainbrosset** [comment]
@vidorteg do you know if the extension works with `file://` URLs?
