### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by jw3215** [microsoft/vscode-edge-devtools#633]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://maxcdn.bootstrapcdn.com/bootstrap/scss/_reboot.scss'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/618
