### ISSUE TITLE
Extension does not respect vscode theme

### ISSUE THREAD

**Issue by hkal** [microsoft/vscode-edge-devtools#66]
I would expect the Elements panel to display in the same theme as other vscode panels. Currently it looks like this:
<img width="1127" alt="elements" src="https://user-images.githubusercontent.com/3802753/60548712-9dbfb880-9cd7-11e9-825c-1ede72233951.png">

It looks like there is enough infrastructure in vscode to make this happen, since colors appear to be exported to vscode webviews: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/webview/common/themeing.ts#L33

**Comment by paulgildea** [comment]
Great feature request. Definitely something we should go look at.

**Comment by codepo8** [comment]
This is currently not possible, but we'll keep it in mind for further investigation. The issue is that VS Code themes are a different format to the devtools ones and traditionally devtools weren't style-able at all, so we're in the process of improving that.

**Comment by marblewraith** [comment]
Looks like this feature is in the pipeline.

The presentation for win11, note the theme parity between VScode and edge browser tools (26:23)

https://youtu.be/egZ82QGshX8?t=1583

**Comment by codepo8** [comment]
Yes that is in the making for devtools and will come to the extension once
we updated to this version. Currently it only works in the Canary version
of the browser and only with the in-buily themes.
