### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by haruperi** [microsoft/vscode-edge-devtools#661]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not mirror css changes to document. No workspace mapping was found for 'http://127.0.0.1:5555/assets/css/styles.css%3F_cacheOverride=1637214831392'.

        **Additional context:**

**Comment by codepo8** [comment]
Seems to me you have a bundled version of CSS there, that doesn't allow for writing.
