### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by anindya127** [microsoft/vscode-edge-devtools#664]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/scss/_reboot.scss'.

        **Additional context:**

**Comment by codepo8** [comment]
Currently we don't support Sass files, only plain CSS. We're working on it though.
