### ISSUE TITLE
I want console functionality

### ISSUE THREAD

**Issue by 1091515459** [microsoft/vscode-edge-devtools#667]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by adarwash** [comment]
This would be amazing

**Comment by codepo8** [comment]
If you launch the extension via the debugger workflow in VS Code, the Debug Console is the browser console. 

Described in the docs here:
https://docs.microsoft.com/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension#console-integration

There's also a [one minute video here](https://www.youtube.com/watch?v=00MNtSzasSQ).

**Comment by TTSKarlsson** [comment]
> If you launch the extension via the debugger workflow in VS Code, the Debug Console is the browser console.

No, you can easily see here that the Debug Console does not work with this extension.

https://user-images.githubusercontent.com/9962943/145381442-354f18b0-add5-4dd5-bd58-b589d2765034.mp4
