### ISSUE TITLE
extension marketplace not opening xhr faild

### ISSUE THREAD

**Issue by UNNIKRISHNANmca** [microsoft/vscode-edge-devtools#671]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
Hi there, could you provide us some more information what happened?

**Comment by UNNIKRISHNANmca** [comment]
MARKET Place is not working error 4h4 not found

**Comment by codepo8** [comment]
Can't repro, must have been an outage. Sorry for the inconvenience.
