### ISSUE TITLE
Elements default "attach" behavior with Debuggers

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#68]
Say you have a debugger like [Debugger for Edge](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge) extension installed AND the Elements for Edge extension installed. You launch a debugging session, what would you expect the default behavior of the Elements for Edge extension to be?

1. Would you expect it to auto "attach" using the same settings from the Debugger launch config? 
2. Would you expect that you would have to manually connect the two extensions together some how?
3. Would you expect that you just use the side panel, find the url that you are actively debugging, and attach the Elements extension that way?

We're curious if folks would be using these types of extensions together most of the time or not and provide the most helpful default experience when they are both installed.

Feedback welcome...
@solankisamir @fiveisprime @hxlnt

**Comment by dkent600** [comment]
I totally want to use these extensions at the same time.  That seems to me like the most natural use case for Elements.
 
(BTW I've been trying to figure out how to do that and the existing docs aren't helping and the "Elements for Microsoft Edge: Attach to a target" command does nothing except put up an unproductive edit field.)

To me, ideally, the default behavior out of the box, is option 1), but of course options 2) and 3) should be available as well.

The ability to fire up its own browser instance, as it does now, should also be available.

**Comment by codepo8** [comment]
I'd also vote for allowing both as we don't want to interfere with current users of the debugger extension.

**Comment by codepo8** [comment]
This now happens.
