### ISSUE TITLE
Can anyone help me why my microsoft edge tools visual code extension is not working? im already install microsoft edge stable version 85

### ISSUE THREAD

**Issue by Caps3012** [microsoft/vscode-edge-devtools#682]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you give us more information what isn't working for you? Where in the process are you getting stuck? And do you mean 95?

**Comment by Caps3012** [comment]
> Can you give us more information what isn't working for you? Where in the process are you getting stuck? 

it said "Microsoft Edge could not be found. Ensure you have installed Microsoft Edge and that you have selected 'default' or the appropriate version of Microsoft Edge in the extension settings panel."
 
>And do you mean 95?
yesterday it has updated to 96

**Comment by codepo8** [comment]
What OS are you on? Do you have a special version of the browser and selected the corresponding flavour in the settings?
![image](https://user-images.githubusercontent.com/13508/144293355-f6ed8021-c8fe-46cb-9711-fed20cab5d27.png)
