### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by ChriceMouanda** [microsoft/vscode-edge-devtools#685]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'http://172.20.5.27:5000/dist/vendor.css%3Fv=YyAxSYcBZiTfzS2n0_fWfvnrGFbshdBR05T28PuWCdM'.

        **Additional context:**

**Comment by codepo8** [comment]
It seems you are working with a CSS bundle and we're not having support for sourcemaps yet.
