### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by Joseph478** [microsoft/vscode-edge-devtools#694]
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not mirror css changes to document. No workspace mapping was found for 'inspector:///J:/Enviroment/HTML-CSS/first_steps/inspector-stylesheet'.

        **Additional context:**

**Comment by codepo8** [comment]
The feature doesn't work for non-http or file:// URLs. thanks for flagging this up, we'll look into it.
