### ISSUE TITLE
Couldn't find the package 'tslib' in tsconfig.json

### ISSUE THREAD

**Issue by omostan** [microsoft/vscode-edge-devtools#708]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): v1.4.1

 Marketplace panel. -->

**Describe the bug:**
Couldn't find package 'tslib' shows up as error even when tslib package is installed in the project.

**Repro steps:**
@angular/core v13.0.2 project

**Expected behavior:**
If 'tslib' is installed, this error should not show up.

**Additional context:**
none

**Comment by gigabet** [comment]
Same issue with create-react-app. I'm using Yarn 3 as package manager, with the VS Code SDK plugin, if that helps.

**Comment by SHIXUNXUN** [comment]
same issue

**Comment by captainbrosset** [comment]
Thanks for reaching out. I'm not certain how this is related to the VS Code Edge DevTools extension.
Could you please provide more information about what you were doing with the extension when this error occurred?

**Comment by captainbrosset** [comment]
Thanks for coming back to me. This bug is now tracked on our internal backlog.

**Comment by antross** [comment]
@captainbrosset - FYI this is a webhint issue that's tracked by https://github.com/webhintio/hint/issues/4526 where we've decided to disable this hint by default. Closing this issue in favor of that one.
