### ISSUE TITLE
not loading any img

### ISSUE THREAD

**Issue by Maro2036** [microsoft/vscode-edge-devtools#717]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Are the images in the extension not showing up, or what do you mean? Could you provide us with a screenshot?

**Comment by captainbrosset** [comment]
This has unfortunately gotten stale, and without more information, we can't really investigate. So closing this issue. Feel free to comment if you have more information that could help.
