### ISSUE TITLE
Add infrastructure to test Edge DevTools code integration

### ISSUE THREAD

**Issue by jalissia** [microsoft/vscode-edge-devtools#73]
Right now all the tests only run against the extension half of the project. 

Ideally the test infrastructure would also be able to download/build the opensource version of the Edge DevTools and run integration tests against there, to check things like the post build step patching, etc.

See comments in: https://github.com/microsoft/vscode-edge-devtools/pull/72

**Comment by codepo8** [comment]
Isn't that related to Brendyn's request?

**Comment by codepo8** [comment]
This is now happening
