### ISSUE TITLE
No console in edge DevTools

### ISSUE THREAD

**Issue by dongkingdom** [microsoft/vscode-edge-devtools#736]
**Is your feature request related to a problem? Please describe.**
Please put console in Edge Devtools. I would love to run everything i need in VSCODE rather than having edge up on different window. Thank you.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by TTSKarlsson** [comment]
I saw this open issue, but I answered first in a closed issue. Anyway, Here's proof Debug Console does not work with this extension.

https://user-images.githubusercontent.com/9962943/145382190-07ade5ef-7cc4-4dba-bc6e-26baa21d47a3.mp4

**Comment by codepo8** [comment]
Thank you for that. Currently the console functionality doesn't work with the DevTools target, but needs the pwa one instead. So in your launch.json you need to use:

``` JavaScript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-msedge",
            "request": "launch",
            "name": "Launch Edge against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

**Comment by dongkingdom** [comment]
> Thank you for that. Currently the console functionality doesn't work with the DevTools target, but needs the pwa one instead. So in your launch.json you need to use:
> 
> ```js
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "pwa-msedge",
>             "request": "launch",
>             "name": "Launch Edge against localhost",
>             "url": "http://localhost:8080",
>             "webRoot": "${workspaceFolder}"
>         }
>     ]
> }
> ```

Still doesn't work. Maybe I am doing something wrong?
![hmm](https://user-images.githubusercontent.com/40304874/146245040-09a80675-43f6-4ed0-9d78-71778c0a6a60.PNG)
