### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by iammursal** [microsoft/vscode-edge-devtools#737]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not mirror css changes to document. No workspace mapping was found for 'http://127.0.0.1:8000/assets/front/css/all.css'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/628
