### ISSUE TITLE
Refused to apply style from 'http://127.0.0.1:5500/public/css-practice.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by shields6** [microsoft/vscode-edge-devtools#749]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
This seems to be a problem with your server setup, I don't know how we can help with that? Can you ensure that your server sends the right MIME type?

**Comment by shields6** [comment]
I was using Visual Studio Code, I personally didn't setup the server.

**Comment by codepo8** [comment]
Well, the server needs to send the right MIME type it seems, and the bug needs fixing there. You can use the reload server as described here: https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension#setting-up-your-project-to-show-live-changes-in-the-extension
