### ISSUE TITLE
In Edge-DevTools, I can't enable/disable css styles

### ISSUE THREAD

**Issue by DonPangPang** [microsoft/vscode-edge-devtools#753]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

Like this, I disabled background-color, but nothing has changed.
![image](https://user-images.githubusercontent.com/49866401/145612610-1f84605d-7b65-4be1-baa3-d41e87f13312.png)

AB#49009863

**Comment by codepo8** [comment]
Hello there, is that in the browser or in the extension?

**Comment by DonPangPang** [comment]
> Hello there, is that in the browser or in the extension?

It's in the entension. I used vscode to open the code editor(left), Edge-DevTools(center) and the built-in browser(right). like this:
![image](https://user-images.githubusercontent.com/49866401/146236903-2515e002-e45e-4acd-8242-8d935950f542.png)
When I use Edge-DevTools to turn off some CSS styles, it doesn't work, the styles still exist.

**Comment by DonPangPang** [comment]
> Hello there, is that in the browser or in the extension?

Wait, I seem to have found a way to reproduce this problem.
1. Open like my actions.
2. Now it works fine. but when I edited something later, like:
![image](https://user-images.githubusercontent.com/49866401/146238570-b7826926-b62c-46c5-b071-5cc89a38f8fa.png)
This error occurs:
![image](https://user-images.githubusercontent.com/49866401/146238820-5736638c-f89d-4fff-ae9d-51ead01e4ccc.png)
3. Needed me to refresh the page again and it was back to normal again.

**Comment by codepo8** [comment]
Thanks for the reproducing information, we will look into this.

**Comment by DonPangPang** [comment]
> Hello there, we tried to repro this on our end and we can't see the problem, even with the editing step. What local server are you running? Are there any conversion/build steps that might delay the changes of the CSS?

All right, I used a VSCode extension named "Live Server" as the server, had no other steps.

**Comment by codepo8** [comment]
Hello there, it seems there is a compatibilty issue with the live server extension that it reloads the document before our changes are applied. Also see #872 for reference. We will try to reach out to the live server team and see what we can do. 
@digitarald can you give some more information?

**Comment by DonPangPang** [comment]
> Hello there, it seems there is a compatibilty issue with the live server extension that it reloads the document before our changes are applied. Also see #872 for reference. We will try to reach out to the live server team and see what we can do. @digitarald can you give some more information?

Nothing else, thanks for your help! And before that, I will try some other ways.

**Comment by digitarald** [comment]
I would recommend filing an issue on https://github.com/ritwickdey/vscode-live-server/ , @codepo8. Maybe there is also a fix possible on this extension, as live server has wide adoption?

**Comment by codepo8** [comment]
Would love to, yes.

**Comment by captainbrosset** [comment]
Closing this issue now. Our dev team tried reproducing it but couldn't. Let me know if there's still a problem here and we can reopen the issue.
