### ISSUE TITLE
how we can use css as js

### ISSUE THREAD

**Issue by kovidshah** [microsoft/vscode-edge-devtools#758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
We are working on support for sourcemaps and would love to get some examples on how people use them. Can you share more where you get stuck?

**Comment by kovidshah** [comment]
yes,when I write some code for making a website I write more and more css
but I need to use algorithms for css to apply like If I want to see some
text show after 3s  I need to use algorithms.😀

**Comment by codepo8** [comment]
Not really, you can use CSS transition and animation with delay.

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay

This is not a bug, it is a feature request and we are working on it, so I am closing this issue. One of the next versions will have support for CSS in JS with sourcemaps.

**Comment by kovidshah** [comment]
Cool, thanks!
