### ISSUE TITLE
my vs code is not open any folder any one help me

### ISSUE THREAD

**Issue by sanju-thakur** [microsoft/vscode-edge-devtools#773]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
This is not a problem with this extension but with VS code itself, I assume.
