### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by sniper425** [microsoft/vscode-edge-devtools#775]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://px2021.landarun.com/static/css/app.39fdc9940bff248394e1b26ad3c71d2d.css'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/618
