### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by Zorro58** [microsoft/vscode-edge-devtools#781]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://docs.microsoft.com/_themes/docs.theme/master/fr-fr/_themes/styles/node_modules/@microsoft/atlas-css/src/core/themes.scss'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/618
