### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by Zorro58** [microsoft/vscode-edge-devtools#782]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'inspector://docs.microsoft.com/fr-fr/microsoft-edge/devtools-guide-chromium/inspector-stylesheet'.

        **Additional context:**

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/618
