### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by zfhassaan** [microsoft/vscode-edge-devtools#785]
**Version:**
        1.4.2

        **OS:**
        Windows 10 Enterprise - Version 21H2 - Build No. 19044.1415 - Windows Feature Experience Pack 120.2212.3920.0

        **Stack:**
        Could not mirror CSS changes to the document. No workspace mapping was found for 'inspector://127.0.0.1/inspector-stylesheet'.

**Comment by mliao95** [comment]
Duping issue to https://github.com/microsoft/vscode-edge-devtools/issues/628
