### ISSUE TITLE
Error while opening CSS file in editor

### ISSUE THREAD

**Issue by riks1233** [microsoft/vscode-edge-devtools#787]
**Version:**
        1.4.2

        **OS:**
        Windows 10

        **Stack :**
        Could not open document. No workspace mapping was found for 'http://ecalendar-admin-panel/css/styles.css'.

        **Additional context:**
        

## Problem description

I have a project `ecalendar-admin-panel` running on `http://ecalendar-admin-panel:80`. The web root (or "docroot" or whatever) is pointing to `ecalendar-admin-panel/public` folder. Just for clarity, when I go to `http://ecalendar-admin-panel:80` in my browser, I actually request files from `ecalendar-admin-panel/public` folder. 

I use "Launch Edge" configuration to use Edge DevTools. My `launch.json` looks like this:

```json
{
    "configurations": [
        {
            "name": "Launch Edge",
            "request": "launch",
            "type": "pwa-msedge",
            "url": "http://ecalendar-admin-panel:80",
            "webRoot": "${workspaceFolder}/public/",
        }
    ]
}
```

I start a debugging session by pressing this button:

![image](https://user-images.githubusercontent.com/32734275/147852357-3fc827bb-a686-4e25-8140-7d29fc972d9e.png)

And when clicking on `styles.css` in "Edge DevTools" panel I get two errors:

![image](https://user-images.githubusercontent.com/32734275/147852598-db60b55d-c06b-46cc-9b7c-2c8068b95c34.png)
![image](https://user-images.githubusercontent.com/32734275/147852404-578c0005-4152-4a0f-b893-7e799540dda5.png)

- ```An error occurred: Error while opening file in editor. Could not open document. No workspace mapping was found for 'http://ecalendar-admin-panel/css/styles.css'..```
- ```Unable to open file in editor. http://localhost/css/styles.css does not map to a local file.```

## Additional info

I've also tried some other `launch.js` configurations, none of which worked, like:

- `"webRoot": "C:/<fullpath>/ecalendar-admin-panel/public/"`
- `"webRoot": "${workspaceFolder}/public"` - No forward slash at the end.
- `"pathMapping": {
    "/": "${workspaceFolder}/public/",
    "http://ecalendar-admin-panel/": "${workspaceFolder}/public/",
  }`

I've also created a folder and a file `css/styles.css` in project root folder (`ecalendar-admin-panel/css/styles.css`) just to test that and then Edge DevTools forwarded me to that file, when I clicked styles.css (i.e. it did work!). But I need Edge DevTools to open the actual `ecalendar-admin-panel/public/css/styles.css` file.

## Suggestion

If I configured everything properly, then "webRoot" and "pathMapping" parameters are ignored by the extension.

**Comment by riks1233** [comment]
Forgot to mention (if that matters), that I use Wampserver (64-bit) to run the project locally.

**Comment by collinanderson** [comment]
I'm having a simliar issue on my Mac, though I'm using `Remote - SSH`. I'm using the `vscode-edge-devtools.debug` type, but it still just says:

```
Unable to open file in editor. https://dev.example.com/static/common.css does not map to a local file.
```

```
An error occurred: Error while opening file in editor. Could not open document. No workspace mapping was found for 'https://dev.example.com/static/common.css'.
```

Here's my `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch Microsoft Edge and open the Edge DevTools",
            "request": "launch",
            "type": "vscode-edge-devtools.debug",
            "url": "https://dev.example.com/",
            "webRoot": "${workspaceFolder}",
            "pathMapping": {
                "/": "${workspaceFolder}/",
                "https://dev.example.com/": "${workspaceFolder}/",
                "https://dev.example.com/static/common.css": "${workspaceFolder}/static/common.css",
            }
        }
    ]
}
```

OS: `MacOS Big Sur 11.6.1 (20G224)`

VS Code info:
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

Local Extensions:
`Microsoft Edge Tools for VS Code` `v1.4.2`
`Remote - SSH` `v0.70.0`

Edge is `Version 97.0.1072.55 (Official build) (x86_64)`

`Remote - SSH` is connected to `Ubuntu 20.04.3 LTS (Focal Fossa)`

**Comment by riks1233** [comment]
Thank you!

**Comment by AlfredoDinunzioTR** [comment]
I am still having this exact same issue.  I cannot tell if this is user-error, since the issue looks like it should be resolved. Or if it is regression.
