### ISSUE TITLE
please add console to edge VS code Dev Tools

### ISSUE THREAD

**Issue by bekzatzamirbekov** [microsoft/vscode-edge-devtools#805]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
Hi there, if you launch the tools from the debugger in VS code, you get the console inside the editor. This is documented here: https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension#console-integration 

Having the console output in the lower drawer seems to be a better fit, as you can keep using the visual tools alongside it.

**Comment by codepo8** [comment]
Commented and working on a more obvious solution.
