### ISSUE TITLE
Browser theme infobar shows even though there are no settings available to change

### ISSUE THREAD

**Issue by brendyna** [microsoft/vscode-edge-devtools#81]
![image](https://user-images.githubusercontent.com/4712801/61889737-d1e35f00-aeba-11e9-9b6c-3a3c074b8094.png)

**Comment by brendyna** [comment]
You can see in the image above the "Dark theme is enabled by default..." toolbar that makes sense in the browser DevTools but not the Code extension.

**Comment by hkal** [comment]
In the latest roll of DevTools the dark theme InfoBar tip is removed, so I'm closing this issue. The bit about settings being unavailable should be fixed with #45
