### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by jim-turner** [microsoft/vscode-edge-devtools#811]
**Version:**
        1.4.2

        **OS:**
        
        Mac OSX 10.15.7

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://uncrate.com/css/min.css%3Fv=326'.

        **Additional context:**

**Comment by codepo8** [comment]
Right now we need to access local files and as we can't edit remote ones, this error is thrown.
