### ISSUE TITLE
I Can't debug vue project by using vue extension on edge

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [microsoft/vscode-edge-devtools#816]
**Is your feature request related to a problem? Please describe.**

I want to debug vue with the devtools. However, all extensions are forbidden on edge
**Describe the solution you'd like:**

I want to use vue extension on edge
**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
Hi there, we're sorry that you run into this issue, and will look into what we can do to enable vue debugging. Am I right in assuming that you want to install the vue extension in the DevTools extension or do you have issues doing that in the browser developer tools?
