### ISSUE TITLE
Localize the extension to match VS Code language when selected

### ISSUE THREAD

**Issue by brendyna** [microsoft/vscode-edge-devtools#82]
The extension should support a localized experience, matching whatever display language VS Code is set to.

**Comment by vidorteg** [comment]
I'm working on this one :)

**Comment by vidorteg** [comment]
This is addressed in this PR:
https://github.com/microsoft/vscode-edge-devtools/pull/88

**Comment by bgoddar** [comment]
closing in favor of #341
