### ISSUE TITLE
False positive from axe/text-alternatives for SVGs with title element content

### ISSUE THREAD

**Issue by tobybaratta** [microsoft/vscode-edge-devtools#824]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11
 - Extension version (*e.g.,* 1.2.3): 1.4.2

**Describe the bug:**
When defining an SVG in JSX, Microsoft Edge Tools throws an error "<svg> elements with an img role must have an alternative text: Element child title is empty Element has no title attribute" if the text for the title attribute is passed in as a required prop. While the title prop passed in could, technically, be an empty string (thus making this a valid error), the extension should assume that you are passing in something valid rather than assuming you are throwing garbage in. 

**Repro steps:**
1. Make a React FC with an SVG element in it, with the `role="img` property on it.
2. Make the FC take a prop of `title`, a required string.
3. In your SVG, have `<title>{props.title}</title>`. 
4. See VS Code error message.

**Expected behavior:**
At maximum, I'd expect a warning in this situation - since it _technically_ could be an empty string. However, I think this should just not raise an error if the title attribute contains a defined variable within it. It's barely an error scenario and certainly not guaranteed as one.

**Additional context:**
Screenshot of Title Element & svg getting a squiggly red marker:
![Screenshot showing line with 'title' element within an SVG](https://user-images.githubusercontent.com/6365705/150058302-b1166973-8253-4500-9b27-71b092c33e4a.png)

Screenshot of Error with line number:
![Screenshot showing VSC error message about missing titles](https://user-images.githubusercontent.com/6365705/150058338-88f8bc83-0245-4aee-b9c3-03d42eb623c0.png)

[Deque SVG IMG Docs](https://dequeuniversity.com/rules/axe/4.3/svg-img-alt?application%3DaxeAPI)

**Comment by codepo8** [comment]
Thanks for your feedback. It seems to me this is out of scope for the extension and a problem with the issues/webhint/axe reporting all up, so we will file a bug for you with this team.

**Comment by captainbrosset** [comment]
Filed here: https://github.com/webhintio/hint/issues/5030
So closing this issue now. Thanks for the report @tobybaratta.
