### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by SD-naoki-yamamoto** [microsoft/vscode-edge-devtools#827]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not mirror css changes to document. No workspace mapping was found for 'http://192.168.1.177/siseidodesign/wordpress/wp-content/themes/siseidodesign/css/index-style.css%3Fver1.3'.

        **Additional context:**

**Comment by codepo8** [comment]
Seems you need to mirror this file locally to make it editable.
