### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by STORMCOM** [microsoft/vscode-edge-devtools#841]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'chrome-error://chromewebdata/'.

        **Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately this issue does not contain enough information for us to investigate the problem.
I will close it for now, but feel free to come back with more information, including specific steps to reproduce and anything else that might be useful, and we can re-open the issue.
