### ISSUE TITLE
auto reload

### ISSUE THREAD

**Issue by smileyismail** [microsoft/vscode-edge-devtools#848]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by smileyismail** [comment]
plz add auto reload option sir

**Comment by smileyismail** [comment]
auto reload

**Comment by ertoorule** [comment]
better question! at least extension has keybind or keymap for reloading thing?
