### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Nicholas-Scafe** [microsoft/vscode-edge-devtools#851]
![CSSMEDGE](https://user-images.githubusercontent.com/68162497/152269638-1c901828-f015-49c4-a751-b9365d5e0e02.png)

**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
@Nicholas-Scafe thanks for reaching out. Could you please explain what is the issue you are seeing.
The screenshot is helpful, thank you for providing it, but without knowing what problem you're having, we can't really investigate or fix it.

**Comment by captainbrosset** [comment]
I unfortunately will have to close this issue as there is not enough information to help the team investigate and fix a potential issue. Feel free to comment back with more info.
