### ISSUE TITLE
BFM

### ISSUE THREAD

**Issue by bfm90** [microsoft/vscode-edge-devtools#853]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by bfm90** [comment]
![Uploading img-5.png…]()

**Comment by captainbrosset** [comment]
There isn't any actionable information in this bug for us to investigate, so I'll have to close it. Sorry about this, but please come back with more info if there is a problem that needs resolving.
