### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by bfm90** [microsoft/vscode-edge-devtools#855]
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'.

        **Additional context:**

**Comment by bfm90** [comment]
h

**Comment by codepo8** [comment]
Dupe
