### ISSUE TITLE
need to set mobile view and pc view in html file

### ISSUE THREAD

**Issue by Polo0145** [microsoft/vscode-edge-devtools#862]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
@Polo0145 could you please provide more information about what you mean exactly?
It seems like you are asking for a new feature to be implemented, but for us to start thinking about it, we need more information about the problem you are trying to solve.
