### ISSUE TITLE
no ¡¡¡¡¡¡¡

### ISSUE THREAD

**Issue by reinasalondra** [microsoft/vscode-edge-devtools#863]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
There is unfortunately not enough information in this bug for us to investigate a potential problem. I'll close the issue now.
