### ISSUE TITLE
Feature request for console in edge dev tools

### ISSUE THREAD

**Issue by aayushchugh** [microsoft/vscode-edge-devtools#866]
**Is your feature request related to a problem? Please describe.**

When I use Microsoft edge dev tools extension, I can only use Elements, styles, Network tab but if I want to use console I either have to open browser developer tools or open vscode's debug console which use a lot of real estate of monitor

**Describe the solution you'd like:**

It will be helpful if we option of console in edge dev tools panel itself

**Comment by codepo8** [comment]
We are working on getting the Console tool turned on in one of the next versions. For now, you need to use the debugger and the console in the VS Code debug console pane. Thanks for bringing this up.

**Comment by aayushchugh** [comment]
Waiting to see this feature
