### ISSUE TITLE
always remind me lost a file, but I dont know how to recover it.

### ISSUE THREAD

**Issue by fanyy0418** [microsoft/vscode-edge-devtools#870]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):win 11
 - Extension version (*e.g.,* 1.2.3):1.4.3

**Describe the bug:**

The tools always remind me lost a file which is named "Chrome user data dir not found at 'C:\Users\FANYUY~1\AppData\Local\Temp\vscode-edge-devtools-userdatadir_9222' ",but I dont know how to recover it and I didnt remeber that I had del this file.

**Repro steps:**

launch vs code, click this tools bar,and click this button at the top of this bar,then will remind me lost file and dont have any other response.

**Expected behavior:**

In pass days,when I click this button, tools will open a new tab to preview my html file.

**Additional context:**

I had install this tools again, but this tools still not work and report the same  error.

**Comment by codepo8** [comment]
See https://github.com/microsoft/vscode-edge-devtools/issues/861 and https://github.com/microsoft/vscode-edge-devtools/pull/871 for solution. Create a directory/folder with the name of vscode-edge-devtools-userdatadir_9222 inside C:\Users\%username%\AppData\Local\Temp\ for now while we wait for the merge to be released as an update.

**Comment by hkal** [comment]
This issue should be fixed in 1.4.5 (#888). Re-open if that is not the case.
