### ISSUE TITLE
I'm trying to open it, but its not opening. It's better to make a officail tutorial on this extension

### ISSUE THREAD

**Issue by Mohammad-Awais456** [microsoft/vscode-edge-devtools#875]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by ChrisG661** [comment]
See #861 and #871 for solution. Create a directory/folder with the name of `vscode-edge-devtools-userdatadir_9222` inside `C:\Users\%username%\AppData\Local\Temp\` for now while we wait for the merge to be released as an update.

**Comment by codepo8** [comment]
Thanks @ChrisG661, this helps!

**Comment by hkal** [comment]
This issue should be fixed in 1.4.5 (#888). Re-open if that is not the case.
