### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by K4la9** [microsoft/vscode-edge-devtools#876]
<![CDATA[  
	        text { filter: url(#filter);
	        fill: white;        
			font-family: Courier;        
			font-weight: bold;       
			font-style: italic;   
			font-size: 45px;        
			-webkit-font-smoothing: antialiased;
	        -moz-osx-font-smoothing: grayscale }
	 ]]></style> 

**Describe the bug:**
at-rule or selector expected
] expected
] expected
at-rule or selector expected

**Comment by codepo8** [comment]
Hello there, we don't quite understand what you mean by that bug report, could you explain in more detail please?

**Comment by captainbrosset** [comment]
Closing as @K4la9 did not get back with more information.
