### ISSUE TITLE
Clicking on Launch Project blinks a tab and then nothing. No reactions 

### ISSUE THREAD

**Issue by bobcozzi** [microsoft/vscode-edge-devtools#880]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by bobcozzi** [comment]
Installed Edge, relaunched VSCODE added a .JSON then clicked Launch Project but only a brief blink of a tab appeared and then immediately vanished before I could see what it was.

**Comment by codepo8** [comment]
We just released a hotfix to the extension that should fix that problem, get the lastest version and it should go away.
