### ISSUE TITLE
uncaught referenceerror always show

### ISSUE THREAD

**Issue by Tusharwatmode** [microsoft/vscode-edge-devtools#884]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you please explain more what you mean by that? We can't replicate the issue this way.

**Comment by captainbrosset** [comment]
Unfortunately, we can't do much about this issue at the moment. No bug description or repro steps were provided.
Please feel free to comment with more information. But in the meantime, I'll close the issue.
