### ISSUE TITLE
Does not work at all 

### ISSUE THREAD

**Issue by wasem-ibrahim** [microsoft/vscode-edge-devtools#887]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Could you give us more information where and when it fails? there is a current bug as a pinned issue that might be the problem.

**Comment by wasem-ibrahim** [comment]
Literally immediately honestly.

Whenever I try to launch it, it just says “ the blobs weren’t found”.

It has been happening since the moment i installed the extension. I cant
get it to work at all.

If u need any more screenshots let me know please.

**Comment by codepo8** [comment]
We currently had a bug and the current version should fix that. Can you tell us what OS you are on? On Windows, all should be OK, I am still seeing issues on MacOS and with Canary as the browser build. 

If your version of Edge is showing that a new update is available, you need to install this update first. This fixed it for me.

**Comment by wasem-ibrahim** [comment]
Yeah im on mac os, and should be on the latest version.

But imma try checking if there is an update for Edge in a sec, I will let
you know

**Comment by codepo8** [comment]
Thank you, please comment on #882  where we track all answers!

**Comment by wasem-ibrahim** [comment]
I did update, and i think that it kinda fixed the issue, and now it
launches wothout saying that there is an error. However, i cant get the
file i want to run.

Can u plz help me on that?

I open the project
Then head to the extension, and hit “ launch project”, and it opens the
edge welcoming page, but not the file i want.

**Comment by codepo8** [comment]
Did you set up the launch.json file accordingly?

Here is what I use:

https://dev.to/codepo8/a-launchjson-to-turn-vs-code-into-a-full-web-development-ide-36ge
