### ISSUE TITLE
visual studio says it cannot attach to the main target when i try to run a project. i have reinstalled it and still no change

### ISSUE THREAD

**Issue by simonumma** [microsoft/vscode-edge-devtools#894]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you give us more information about your setup? Is this Mac or PC?

**Comment by captainbrosset** [comment]
Unfortunately, we can't do much about this issue at the moment. No detailed bug description or repro steps were provided.
Please feel free to comment with more information. But in the meantime, I'll close the issue.
