### ISSUE TITLE
Unable to run HTML

### ISSUE THREAD

**Issue by saip007** [microsoft/vscode-edge-devtools#897]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

I'm Unable to run the html files in Edge and while running the HTML files it is showing unable to locate localhost
previously I didn't do any configuration of Username and Password

**Repro steps:**

Create a html and try to configure and Run the file.

**Expected behavior:**

![Screenshot (182)](https://user-images.githubusercontent.com/67538794/154830367-a26a4ae6-8150-4fc3-9051-8ca732ce4046.png)

**Additional context:**

![Screenshot (183)](https://user-images.githubusercontent.com/67538794/154830374-8bd3c113-e10d-41ea-969b-b31dbdc0311d.png)

**Comment by captainbrosset** [comment]
This seems similar to #898 so closing this one in favor of the other.
