### ISSUE TITLE
Opt-out of Webhint for Internet Explorer

### ISSUE THREAD

**Issue by petedavisdev** [microsoft/vscode-edge-devtools#899]
**Is your feature request related to a problem? Please describe.**

Webhint errors and warnings relating to Internet Explorer, are irrelevant distractions if your project intentionally does not support IE.

**Describe the solution you'd like:**

Either:
1. An option to turn off all Webhint errors and warnings relating to IE.

Or, ideally:

2. Webhint works with [browserlist](https://github.com/browserslist/browserslist) (either in package.json or .browserslistrc) to automatically show only relevant warnings and errors.

**Describe alternatives you've considered:**

**Additional context:**

IE is already [not support by several Microsoft products and will be retired on Windows 10 in June](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/). These errors and warnings are not useful for most projects going forward.

**Comment by codepo8** [comment]
This is in the making and should be coming soon. We are working on making it easier to filter the results of the Issues tool in the browser itself, and this will be part of this extension, too.

Thanks for validating that need!

**Comment by antross** [comment]
@petedavisdev webhint issues reported directly in source code should already respond to a browserslist config today. I shared one example of a package.json to do this here: https://github.com/microsoft/vscode-edge-devtools/issues/663#issuecomment-1042378169. Let us know if this isn't working for you.

**Comment by captainbrosset** [comment]
Closing this issue based on Tony's comment above. But feel free to comment if this isn't working for you and we can re-open the issue.
