### ISSUE TITLE
Closing the extension does not close the associated browser

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#90]
When I close the extension I (would) expect that the target is closed too.

**Comment by codepo8** [comment]
Thanks for your feedback, can you verify one of my assumptions here? Do you only want to close the target when you opened it in the extension or any target you connected to?

**Comment by vidorteg** [comment]
Hmm you brought a good point. I would expect that : 
- any target launched through the extension gets closed when I close Elements for Edge
- any target attached through the extension should keep open when I close Elements for Edge.
