### ISSUE TITLE
CHECKPOINT.HTML

### ISSUE THREAD

**Issue by Delanoalfredyao** [microsoft/vscode-edge-devtools#902]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Unfortunately, we can't do much about this issue at the moment. No bug description or repro steps were provided.
Please feel free to comment with more information. But in the meantime, I'll close the issue.
