### ISSUE TITLE
Language not Supported

### ISSUE THREAD

**Issue by MissemRaza** [microsoft/vscode-edge-devtools#906]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you tell us more what you mean by this bug report? Are you looking for a certain locale (developer tools in different languages) or programming language?
