### ISSUE TITLE
Vertical Scaling

### ISSUE THREAD

**Issue by pot-of-coffee** [microsoft/vscode-edge-devtools#908]
I am experiencing an issue where when the webpage(s) are run in headless mode, the Screencast editor group does not shrink its rendering dimension vertically. The rendering dimensions will increase vertically as I increase the editor group's vertical size (shrinking any editor group(s) below it). However, when I need more space for a group below it (Console, DevTools, etc.), the Screencast editor group's height will shrink but not the dimensions it is rendered in. It continues to render the webpage at the greatest height it had been increased to across webpages, allowing the editor group below it to cut off the rest. This occurs until a new Edge instance is launched. I tested this with local files, local webpages, and public webpages (for example: Google or this GitHub page).

**In short:** Horizontal growing/shrinking works normally as the editor group's size is increased or decreased along that axis. The issue I have is the vertical size it renders in, where the editor group's vertical dimension will decrease, but will still render the webpage at whatever greatest height the editor group used to be at.

I can confirm this as the webpages get cut off (can't scroll any further) and when the editor group's dimensions are adjusted, the top right displays the dimensions the webpage is rendered in when updated.

The DevTools editor group (along with other VS Code editor groups) scales itself properly, as well as having it in a separate Edge window (headless disabled), just not the Screencast's rendering in VS Code.

I'm not sure if this is intended (perhaps for performance or technical reasons), but as I don't know how to launch DevTools instances (DevTools and Screencast) in a specific layout/size, I manually change it around. The webpages are cut off vertically. I'm new to this, so I don't know if there's an option/work around to resolve this, or if it's a bug. I apologize for wasting anyone's time if it's the former (or if it's intended to be this way).

**Comment by pot-of-coffee** [comment]
### _For additional info:_

### Headless Mode: Enabled

- Opens webpage in a separate Edge window (as intended)
- Website's rendering dimensions are correctly adjusted both vertically and horizontally according to Edge's window
- DevTools window correctly adjusts both vertically and horizontally according to window's dimensions

### Headless Mode: Disabled

- Website's rendering dimensions are correctly adjusted horizontally according to the Screencast window in the editor
- Website's rendering dimensions will increase with the window, but not decrease with the Screencast window
- Editor window below (for example, Terminal) will cover webpage's contents when vertically increased
- DevTools window correctly adjusts both vertically and horizontally according to window's (tab) dimensions

### Using DevTools Device Emulation in personal Edge window:
- Website's rendering dimensions are correctly adjusted both vertically and horizontally, regardless whether it's adjusted within Edge's window or Edge's window itself is adjusted
- DevTools window correctly adjusts both vertically and horizontally according to window's dimensions

### Flavour: Tested: No selection, Default, Stable, Dev

- No effect

### User Data Dir: Any (true, false)

- No effect

### To do my best to convey this, here's a scenario with random page values:

Launched in: 559px x 462px
Renders webpage in: 559px x 462px

Resized to: 559px x 600px
Renders webpage in: 559px x 600px

Resized to: 559px x **462px**
Renders webpage in: 559px x **600px**

Resized to: 559px x **510px**
Renders webpage in: 559px x **600px**

Resized to: 650px x 650px
Renders webpage in: 650px x 650px

Resized to: 559px x **462px**
Renders webpage in: 559px x **650px**

**Comment by pot-of-coffee** [comment]
Thank you for the input.
Since this has been marked as a bug, I figured I'd provide a bug report template filled out:





**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11
 - Extension version (*e.g.,* 1.2.3): 1.4.5

**Describe the bug:**
"Edge DevTools: Screencast" does not decrease the vertical dimension it renders a webpage in when the editor group's vertical dimension decreases.

**Repro steps:**

1. Launch instance of Edge DevTools with the `Vscode-edge-devtools: Headless` option enabled in the settings
2. Vertically shrink the "Edge DevTools: Screencast" editor group (for example, drag up VS Code's integrated console or resize the VS Code window)

**Expected behavior:**
The webpage will be rendered at the new lower vertical size of the editor group to allow the webpage to adjust to the dimensions and/or provide scrolling to what is now cut off. This would be similar behaviour to the already functional horizontal scaling.

**Additional context:**
This also does not scale when the size of the VS Code window itself is vertically decreased (or going from maximized to windowed mode).

**Comment by antross** [comment]
Thanks again for the report @pot-of-coffee. We were able to figure this out and checked in a fix in #968. It should be available in our next update.
