### ISSUE TITLE
no puedo tener git como extension 

### ISSUE THREAD

**Issue by jomer710** [microsoft/vscode-edge-devtools#911]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
What do you mean by not being able to have git as an extension? Are you using a DevTools extension that works with git, or the file extension?

**Comment by codepo8** [comment]
No answer, closing
