### ISSUE TITLE
vscode-edge-devtools

### ISSUE THREAD

**Issue by Trade-Help** [microsoft/vscode-edge-devtools#913]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Unfortunately this issue does not contain any information for the team to help resolve a potential issue.
I'll close the issue for now. Feel free to comment with more information and we can re-open it.
