### ISSUE TITLE
Titagr

### ISSUE THREAD

**Issue by Andy1412** [microsoft/vscode-edge-devtools#918]
![ACFrOgAqTnFdNB0B8VOr_vxBUKG8mefOTCS_HIoO8ZLoa1MgUkQ0hv6e67xXtLcQi6VGLEuMOvaGsqFP8RzB-1qeeTKSBWQgSlPUtS1Kwc4KQUKMPXKZbpheoO6-_6c=](https://user-images.githubusercontent.com/18255858/157654484-6a8dfec0-5817-4395-a701-f448df8278af.png)

**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Closing as invalid. Feel free to come back with information about the issue you are encountering.
