### ISSUE TITLE
Add Support for Vue, React, Angular frameworks

### ISSUE THREAD

**Issue by davidcrandall99** [microsoft/vscode-edge-devtools#919]
**Is your feature request related to a problem? Please describe.**

Currently, as a react, Angular, or Vue developer, there is no way for me to modify precompiled CSS or HTML markup from the Edge Devtools. Currently, only runtime HTML and CSS are supported, with the exception of external scss/sass.

**Describe the solution you'd like:**

In the same way I can click, open, and apply changes a pre-compiled SCSS stylesheet and see it updating in the browser, I would like to be able to click and open a react, vue, and/or angular component precompiled within dev tools, make changes, and have the changes interpreted in the browser and apply the changes to the source files.

**Describe alternatives you've considered:**

I've tried using framework specific browser extensions within Edge, but this is not supported for many reasons.
I've enabled source maps in local environments for scss and vue components, but the dev tools do not interpret vue components.

**Additional context:**

This is probably a very complex task, but would dramatically simplify developer workflows, given how the industry has evolved to adopt these frameworks for many web-based projects, whether that's a website or a SAAS application. This would probably help increase adoption of this tool, and be useful for developers building things beyond static html webpages.

It can also be useful for migratory projects, where one or more frameworks may be used within a single UI. Many web projects go through transitional phases where multiple UI frameworks exist as a means to deprecate one over the other, or the first UI framework is being implemented piecemeal into a project.

This is something that's missing from devtools in general, but since you're able to allow VSCode to read source files in a local project, there should be no reason to not support HTML markup and SCSS changes for precompiled React, Vue, or Angular projects.

**Comment by codepo8** [comment]
Hello David, we're working on Sourcemaps support for CSS, and should have that in the extension to try out soon. We understand your issue, and the main problem is to have good sourcemaps generated by different frameworks to allow the developer tools to get access to the sources.

**Comment by codepo8** [comment]
> Could you possibly provide at least rough ETA for this feature? I am running angular 13 monorepo with multiple projects and I can debug just fine all of the files but whenever I try to edit anything within my scss files i get errors such as `Error while mirroring css content to document. Could not mirror css changes to document. No workspace mapping was found for 'http://localhost:4200/XXXXX.component.scss'.`
> 
> I tried using Vscode-edge-devtools: Source Map Path Overrides and/or Path Mapping but it doesn't seem to do the job for multiple projects under one repo

This should work, if you have set up your sourcemaps the right way. @mliao95 @hkal can you help?

**Comment by codepo8** [comment]
Also @Mkurkow there is a scenario where this is tracked with a demo app that has the right sourcemaps setup:
https://github.com/microsoft/vscode-edge-devtools/issues/965

**Comment by captainbrosset** [comment]
Based on what Chris said, this should now work. So closing the issue.

**Comment by wysisoft** [comment]
I'm not seeing this work at all in vue, I have a single file component with scoped css, as well as inline styles in the template, and i'm not seeing either change when I change the style in devtools?
