### ISSUE TITLE
Microsoft / vscode-edge-devtools

### ISSUE THREAD

**Issue by Jacquelinevv0693** [microsoft/vscode-edge-devtools#923]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment]
This appears to be an empty issue. Let me close it for now. Please do add steps to reproduce and a description of the issue you encountered, and we can then re-open the issue.
