### ISSUE TITLE
`Elements for Microsoft Edge: Attach to a target` command does nothing

### ISSUE THREAD

**Issue by dkent600** [microsoft/vscode-edge-devtools#93]
I've been trying to figure out how to attach Elements to my running browser instance launched by Debugger for Edge.

The existing docs aren't helping and the "Elements for Microsoft Edge: Attach to a target" command does nothing except put up an unproductive edit field.  I expect that, according to the docs, it will put up a dropdown allowing me to select the browser instance to which to attach.

**Comment by jalissia** [comment]
We have worked planned to make integration with the Debugger for Edge extension more seamless as right now (as you are finding out), it's a bit of a pain.

It should be possible though.

When you run the "Elements for Microsoft Edge: Attach to a target" command, the Elements extension will attempt to look for all targets using the settings specified for your current workspace. The fact that the dropdown is showing up blank suggests that Elements is using a different port to the one Debugger for Edge is using (so it can't find any targets).

Could you try the following:
- Open VS Code settings (File ->Preferences -> Settings)
- In the settings dialog, Expand `Extensions`
- Under Extensions, Select `Elements for Microsoft Edge`
- In the Elements settings, Find `Port`
- Update the Port value to be `2015`

I believe 2015 is the port that Debugger for Edge uses by default, if you have set a different port in your `launch.json` for the Debugger for Edge config, use that port number in the Elements settings above.

That should allow the Elements attach command to find the targets that the Debugger for Edge extension is using and so the dropdown will let you pick the right one.
