### ISSUE TITLE
my live server in vs code dose not work and i did not receive any error and every time i code , i should tap on the go live button 

### ISSUE THREAD

**Issue by mahdiyar98** [microsoft/vscode-edge-devtools#941]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Can you explain in more detail what you mean by that? The newest version of the extension should play well with live server.
