### ISSUE TITLE
New emulation bar for screencast - please tell us what design you'd prefer

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-edge-devtools#942]
We're currently working on improving the findability of emulation features in the Microsoft Edge developer tools. Did you know that you can [emulate different vision deficiences](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/accessibility/emulate-vision-deficiencies), [dark and light schemes](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation), [forced colours](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/whats-new/2022/02/devtools) and [print layout](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/css/print-preview) amongst other things? 

If you don't, then the problem is that they are hard to find and hidden in the `Rendering` menu. 

![Emulation options in the rendering tool](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nzig91359bgkegq6ohua.png)

To improve this, we are working on a new emulation bar inside the screencast of the [Edge DevTools for Visual Studio Code](https://aka.ms/devtools-for-edge) as a testing ground to change it in the main browser. 

We now need to know [what you'd prefer to see](https://forms.office.com/r/b86Sp3PBA4):

# CSS features emulation

A prioritised set of emulation features:
![Option showing only a few](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/spjwnh41prtv76xqa46z.png)
 
All options as a flat list:

![Long list of emulations](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/rzo74bvxbggetmmeybqp.png)
 
A nested list:

![Nested menus to choose CSS emulation feature](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/n6noqg9cn2m37mrytsyl.png)
 
# Vision deficiences

Furthermore, we'd like to know if you prefer the vision deficiencies emulation as part of this menu:

![Vision deficiency emulation as part of the main menu](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/81dvt6jpnt6h5hnpt6sp.png)

Or as a separate button/menu:

![Vision deficiency as an own button](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/mysef84wjjcgygx5ykrw.png)
 
You can [fill out this quick survey](https://forms.office.com/r/b86Sp3PBA4) or comment here.

Thanks so much!

**Comment by nclm** [comment]
Ideally something between flat and nested list: compact like the nested, but with the ability to see which option is currently set (possibly only for the ones that are not on “no”).

Could be the nested list, with the active option written in small/gray next to the option name. And with the list unfolding to the right, not the left.

**Comment by hkal** [comment]
> Could be the nested list, with the active option written in small/gray next to the option name. And with the list unfolding to the right, not the left.

Thanks for the suggestion. I think this is a good idea 👍
