### ISSUE TITLE
Console is not visible in Edge Devtools on macOS

### ISSUE THREAD

**Issue by vronkain** [microsoft/vscode-edge-devtools#948]
In docs.microsoft.com it shows pictures of having VScode with Edge tools extension. There are the Edge browses devtools, with labeled functions such as [elements] [console] [issues].

But when I install Edge tools extension on my VSCode (on a Macbook) I can only see [elements] [network] but no console in the devtools. There is a " + " sign so you can add functionality, such as [issues], but there is no console to add. 

I would like to have a console in there, on a Macbook. 

![](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/media/edge-devtools-for-vscode-console-full.png)

**Comment by codepo8** [comment]
Hi there, I am also on a Mac and it does work, however, you need to use the Canary Edge as the debugging browser right now as this feature is only available from Edge 101 onwards. If you need help setting that up, I can guide you along.

If you use a launch.json, you can do it like so:

``` 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-msedge",
            "request": "launch",
            "name": "webdebug",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "runtimeExecutable": "canary",
            "runtimeArgs": ["--headless"],
        },
    ]
}
```

**Comment by vronkain** [comment]
Thank you! This bird CAN fly! It all works perfectly with this launch.json and the --headless option nicely opens it solely in the VScode and omits opening the browser.
