### ISSUE TITLE
How to disable "not supported in Edge/Internet Explorer" warnings in css/less/sass files?

### ISSUE THREAD

**Issue by tkafka** [microsoft/vscode-edge-devtools#950]
Since installing VS Code Edge dev tools, all CSS editors in VS code are underlining commonly used CSS properties as not supported by IE. I don't care about such warnings, I just need Edge tools to help with debugging in Edge.

Is there a way to turn off these warnings? I have read through https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension and browsed through dev tools settings, but I haven't found any hint about the warnings being possible to turn off.

The warnings are now actively hostile in visually drowning the actual issues in the project, and non-actionable (yes, I know IE doesn't support `word-break: break-word;`, but I need it for other browsers, and it won't harm IE since it will happily ignore it).

![Screenshot 2022-03-30 at 17 20 28](https://user-images.githubusercontent.com/876717/160871304-4ea0082a-219b-4c1f-9626-7ea1a018ed91.png)

**Comment by antross** [comment]
Thanks for the feedback @tkafka! 

I think the discussion in #596 should help:
* If you want to turn off all such warnings, see https://github.com/microsoft/vscode-edge-devtools/issues/596#issuecomment-956362709. 
* If you want to selectively disable specific warnings, see https://github.com/microsoft/vscode-edge-devtools/issues/596#issuecomment-961496154

**Comment by tkafka** [comment]
@antross Thank you very much, this seems to do what I want - I didn't know about webhint until this moment, and I didn't recognize it in preferences.

**Comment by antross** [comment]
Glad this helped! 

I think we can still improve discoverability here with some in-context options for jumping to the correct setting and/or updating configuration files to disable specific feedback. We're tracking some ideas along these lines separately, so I'll add this as another instance where they would've potentially been beneficial.

**Comment by tkafka** [comment]
Thank you! I understand it's not easy, as more repeated information in a popup could be distracting, even though the popup was the first place I tried looking for 'disable/manage this hint'.
