### ISSUE TITLE
Error loading "hint" package from "f:\Workspace\Visual Studio Code\XXX" Trying to load shared version

### ISSUE THREAD

**Issue by mxp131011** [microsoft/vscode-edge-devtools#952]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): win11
 - Extension version (*e.g.,* 1.2.3):1.4.6

**Describe the bug:**

Unable to launch plug-in

**Repro steps:**

There was a problem when I upgraded vscode to v1.66.0 today. It was ok before the upgrade   

**Expected behavior:**

Normal boot

**Additional context:**

![image](https://user-images.githubusercontent.com/31055355/160972642-af74aae0-2c2e-43fb-be68-552529233e34.png)

**Comment by antross** [comment]
Thanks for the report @mxp131011!

Good news is we're already tracking this issue in #910 and have PR up with a fix in #951.
