### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by Haleymiranda79** [microsoft/vscode-edge-devtools#961]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

I'm sure we can make an AI that can teach you to code. Let's get one.

**Comment by captainbrosset** [comment]
Sure, it probably can be done, but I'm not seeing how this relates to the vscode-edge-devtools extension. I'm closing this issue for now as it is unrelated to this repo. Feel free to open a new one if you encounter any issue with using the extension or have an idea for a new feature. Thanks.
