### ISSUE TITLE
reture

### ISSUE THREAD

**Issue by lcyandc** [microsoft/vscode-edge-devtools#969]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Unfortunately, there is not enough information in this issue for the team to investigate a potential problem.
I'll close the issue now, feel free to comment with more information if you have any.
