### ISSUE TITLE
VScode Edge Devtools - The proactive code completion has changed behavior

### ISSUE THREAD

**Issue by vronkain** [microsoft/vscode-edge-devtools#970]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Macos 11.6.5 Big Sur
 - Extension version (*e.g.,* 1.2.3): 1.4.7

** VSCODE ** 
Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:49:47.400Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.6.0

**Describe the bug:**

In VSCode Edge devtools console. Yesterday/day before it performed differently. It used to proactively offer code just like intellisense. Now it is as if it's showing me history? 

**Repro steps:**

Normal use

**Expected behavior:**

It's expected to autocomplete fill code 

**Additional context:**

![telegram-cloud-photo-size-4-5945042900641495778-y](https://user-images.githubusercontent.com/14953272/162473041-e33827c1-4693-427b-8f49-e28e8deddce3.jpg)

Yesterdays behavior above, I could do similar things as in this video.

![telegram-cloud-photo-size-4-5945042900641495777-y](https://user-images.githubusercontent.com/14953272/162473185-0cf291e0-e491-42c5-8ba6-e808794298c6.jpg)

Now today, it looks and feels different

**Comment by codepo8** [comment]
Hello there, this could be a quick bug, but just to be sure, and sorry for bringing this up, but could it be the missing "."?

**Comment by codepo8** [comment]
Thanks for flagging that up, we'll investigate what's going on there.

**Comment by jpaulin** [comment]
@codepo8 Is blob (blobs) part of the VSCode editor, or Edge dev tools, organically? I've got similar toolchain, but on Windows 10 - not Mac. Just curious and following the issue. thanks!

**Comment by codepo8** [comment]
Yes, this is part of the architecture. We're working on that bug, it should reload after a few seconds and work right now.

**Comment by vronkain** [comment]
The devtools commences now, but with reduced intellisense as originally described.

**Comment by vronkain** [comment]
And now it's back to the error message, then it shuts itself off

**Comment by jpaulin** [comment]
@codepo8 hey thx, great! Do the blobs store completion data related to Intellisense? Just my hunch. If you got docs or similar pointers, would be great. I can check more there and leave this thread to actually resolving the bug. :)

**Comment by vronkain** [comment]
I believe this is still an issue

**Comment by vronkain** [comment]
It seems to be working now, at least on the part I know.

**Comment by codepo8** [comment]
@antross can you help?
