### ISSUE TITLE
Ability to edit Webhints browsers

### ISSUE THREAD

**Issue by AuracleTech** [microsoft/vscode-edge-devtools#973]
#### Is your feature request related to a problem?
I do not consider Internet Explorer worthy of haggle.
I do not support old technology.
![image](https://user-images.githubusercontent.com/40531871/162645212-7015ce15-1369-4080-a817-c32e7d58b794.png)

#### The solution you'd like
A set of sub-options to be able to control which browsers you want to support.
Or just disable IE, it's old. If someone use IE in 2022, not our problem.

#### Alternatives you've considered
Removing edge extension, but its nice to see the other tips.

#### Additional context
Crab 🦀.

**Comment by captainbrosset** [comment]
I believe this is already possible. See @antross' message [here](https://github.com/microsoft/vscode-edge-devtools/issues/663#issuecomment-1042378169), also quoted below:

> if you also want to just turn off feedback for Internet Explorer, you can update your target browsers either in your package.json or .hintrc file.
> E.g. this package.json will do the trick (you may have to restart VS Code after updating it for the change to take effect, though)
> {
>  "browserslist": "defaults, not IE 11"
> }

**Comment by AuracleTech** [comment]
Strange, I did not see it when I checked the docs...

**Comment by codepo8** [comment]
That's true, we haven't added that to the docs yet, I am working on that. Also on a video tutorial.
