### ISSUE TITLE
Opened a console popup to execute npm when the extension was enabled

### ISSUE THREAD

**Issue by 2A5F** [microsoft/vscode-edge-devtools#980]
**Environment:**
 - OS: Windows 11 21H2
 - Extension version: 1.4.7

**Describe the bug:**

Opened a console popup to execute npm when the extension was enabled

**Repro steps:**

Install and enable the extension

**Expected behavior:**

Execute npm silently

**Comment by capegreg** [comment]
Is this fixed?

**Comment by antross** [comment]
@capegreg not yet, but we're working on it. We're tracking the issue in #976.
