### ISSUE TITLE
The "Check32BitScanner" in AccessAnyWare64.exe.config needs to be set as "Yes". 2. The LeadtoolsThunk Server need to be installed and registered.    Copy the LeadtoolsThunk to some folder (for example C:\LeadtoolsThunk) at the client workstation where AccessAnyWare64 is installed.    Run windows command with administrator privilege, and then run the following command:    C:\LeadtoolsThunk\Ltthunkserver.exe /regserver

### ISSUE THREAD

**Issue by blouper** [microsoft/vscode-edge-devtools#987]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by blouper** [comment]
protections pour file:///c:User/paqcel/Dowloads/Courriel%20hameconnage-R%C3%A9seau%20SSS%2020200806.pdf

**Comment by blouper** [comment]
<embed id="plugin" type="application/x-google-chrome-pdf" original-url="file:///C:/Users/paqcel/Downloads/19-030f%20(1).pdf" src="chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/cbda6fb8-2cc6-487b-b1d0-f7d5596987a8" background-color="0xFFE6E6E6" first-page-separator="4" style="position: relative !important; top: 0px; min-height: calc(100% - 0px);" javascript="allow" stream_timestamp="512876789950" embed-top-offset="0" width="742" height="58496" full-frame pdfviewrecoveryenabled pdffreetextenabled data-docheight="58492" data-docwidth="742">

**Comment by codepo8** [comment]
No idea what that means,  filing as potential spam.
