### ISSUE TITLE
clipboard functionality isn't working

### ISSUE THREAD

**Issue by AnthonyLenglet** [microsoft/vscode-edge-devtools#99]
As of right now, it is seemingly impossible to use the clipboard to copy for exemple styles from elements into code, which is a bummer as it stands :/

**Comment by codepo8** [comment]
Thanks for verifying. We're looking into this.

**Comment by SergiArias** [comment]
Does not work for me neither. I think it's one of the most important features that should work, as it slows down a lot having to retype everything.

**Comment by Sovai** [comment]
still having this problem on Edge Dev
